export const sAmuelChapter8 = {
  '8:1': { verse: '8:1', text: 'And it came to pass, when Samuel was old, that he made his sons judges over Israel.', lemmas: { Samuel: "Shemu'el", judges: 'shaphat' } },
  '8:2': { verse: '8:2', text: 'Now the name of his firstborn was Joel; and the name of his second, Abiah: they were judges in Beer-sheba.', lemmas: { firstborn: 'bekor', 'Beer-sheba': "Be'er Sheba'" } },
  '8:3': { verse: '8:3', text: 'And his sons walked not in his ways, but turned aside after lucre, and took bribes, and perverted judgment.', lemmas: { lucre: "betsa'", bribes: 'shochad' } },
  '8:4': { verse: '8:4', text: 'Then all the elders of Israel gathered themselves together, and came to Samuel unto Ramah,', lemmas: { elders: 'zaqen', Ramah: 'Ramah' } },
  '8:5': { verse: '8:5', text: 'And said unto him, Behold, thou art old, and thy sons walk not in thy ways: now make us a king to judge us like all the nations.', lemmas: { king: 'melek', nations: 'goy' } },
  '8:6': { verse: '8:6', text: 'But the thing displeased Samuel, when they said, Give us a king to judge us. And Samuel prayed unto the LORD.', lemmas: { prayed: 'palal', LORD: 'YHWH' } },
  '8:7': { verse: '8:7', text: 'And the LORD said unto Samuel, Hearken unto the voice of the people in all that they say unto thee: for they have not rejected thee, but they have rejected me, that I should not reign over them.', lemmas: { Hearken: "shama'", rejected: "ma'as" } },
  '8:8': { verse: '8:8', text: 'According to all the works which they have done since the day that I brought them up out of Egypt even unto this day, wherewith they have forsaken me, and served other gods, so do they also unto thee.', lemmas: { Egypt: 'Mitsrayim', forsaken: "'azab" } },
  '8:9': { verse: '8:9', text: 'Now therefore hearken unto their voice: howbeit yet protest solemnly unto them, and shew them the manner of the king that shall reign over them.', lemmas: { protest: "'ud", king: 'melek' } },
  '8:10': { verse: '8:10', text: 'And Samuel told all the words of the LORD unto the people that asked of him a king.', lemmas: { LORD: 'YHWH', people: "'am" } },
  '8:11': { verse: '8:11', text: 'And he said, This will be the manner of the king that shall reign over you: He will take your sons, and appoint them for himself, for his chariots, and to be his horsemen; and some shall run before his chariots.', lemmas: { chariots: 'rekeb', horsemen: 'parash' } },
  '8:12': { verse: '8:12', text: 'And he will appoint him captains over thousands, and captains over fifties; and will set them to ear his ground, and to reap his harvest, and to make his instruments of war, and instruments of his chariots.', lemmas: { captains: 'sar', harvest: 'qatsir' } },
  '8:13': { verse: '8:13', text: 'And he will take your daughters to be confectionaries, and to be cooks, and to be bakers.', lemmas: { daughters: 'bat', cooks: 'tabbach' } },
  '8:14': { verse: '8:14', text: 'And he will take your fields, and your vineyards, and your oliveyards, even the best of them, and give them to his servants.', lemmas: { fields: 'sadeh', servants: "'ebed" } },
  '8:15': { verse: '8:15', text: 'And he will take the tenth of your seed, and of your vineyards, and give to his officers, and to his servants.', lemmas: { tenth: "ma'aser", seed: "zera'" } },
  '8:16': { verse: '8:16', text: 'And he will take your menservants, and your maidservants, and your goodliest young men, and your asses, and put them to his work.', lemmas: { maidservants: 'shiphchah', asses: 'chamor' } },
  '8:17': { verse: '8:17', text: 'He will take the tenth of your sheep: and ye shall be his servants.', lemmas: { sheep: 'tson', servants: "'ebed" } },
  '8:18': { verse: '8:18', text: 'And ye shall cry out in that day because of your king which ye shall have chosen you; and the LORD will not hear you in that day.', lemmas: { king: 'melek', LORD: 'YHWH' } },
  '8:19': { verse: '8:19', text: 'Nevertheless the people refused to obey the voice of Samuel; and they said, Nay; but we will have a king over us;', lemmas: { refused: "ma'en", obey: "shama'" } },
  '8:20': { verse: '8:20', text: 'That we also may be like all the nations; and that our king may judge us, and go out before us, and fight our battles.', lemmas: { nations: 'goy', battles: 'milchamah' } },
  '8:21': { verse: '8:21', text: 'And Samuel heard all the words of the people, and he rehearsed them in the ears of the LORD.', lemmas: { ears: "'ozen", LORD: 'YHWH' } },
  '8:22': { verse: '8:22', text: 'And the LORD said to Samuel, Hearken unto their voice, and make them a king. And Samuel said unto the men of Israel, Go ye every man unto his city.', lemmas: { Hearken: "shama'", king: 'melek' } },
};
