export const sAmuelChapter5 = {
  '5:1': { verse: '5:1', text: 'And the Philistines took the ark of God, and brought it from Ebenezer unto Ashdod.', lemmas: { Philistines: "Pəlištî", ark: "'ārōn" } },
  '5:2': { verse: '5:2', text: 'When the Philistines took the ark of God, they brought it into the house of Dagon, and set it by Dagon.', lemmas: { Dagon: "Dāgōn", ark: "'ārōn" } },
  '5:3': { verse: '5:3', text: 'And when they of Ashdod arose early on the morrow, behold, Dagon was fallen upon his face to the earth before the ark of the LORD. And they took Dagon, and set him in his place again.', lemmas: { Ashdod: "'Ašdōd", LORD: "YHWH" } },
  '5:4': { verse: '5:4', text: 'And when they arose early on the morrow morning, behold, Dagon was fallen upon his face to the ground before the ark of the LORD; and the head of Dagon and both the palms of his hands were cut off upon the threshold; only the stump of Dagon was left to him.', lemmas: { threshold: "miphtān", LORD: "YHWH" } },
  '5:5': { verse: '5:5', text: 'Therefore neither the priests of Dagon, nor any that come into Dagon\'s house, tread on the threshold of Dagon in Ashdod unto this day.', lemmas: { priests: "kōhēn", threshold: "miphtān" } },
  '5:6': { verse: '5:6', text: 'But the hand of the LORD was heavy upon them of Ashdod, and he destroyed them, and smote them with emerods, even Ashdod and the coasts thereof.', lemmas: { hand: "yād", emerods: "'ōphel" } },
  '5:7': { verse: '5:7', text: 'And when the men of Ashdod saw that it was so, they said, The ark of the God of Israel shall not abide with us: for his hand is sore upon us, and upon Dagon our god.', lemmas: { ark: "'ārōn", hand: "yād" } },
  '5:8': { verse: '5:8', text: 'They sent therefore and gathered all the lords of the Philistines unto them, and said, What shall we do with the ark of the God of Israel? And they answered, Let the ark of the God of Israel be carried about unto Gath. And they carried the ark of the God of Israel about thither.', lemmas: { lords: "serēn", Gath: "Gath" } },
  '5:9': { verse: '5:9', text: 'And it was so, that, after they had carried it about, the hand of the LORD was against the city with a very great destruction: and he smote the men of the city, both small and great, and they had emerods in their secret parts.', lemmas: { LORD: "YHWH", emerods: "'ōphel" } },
  '5:10': { verse: '5:10', text: 'Therefore they sent the ark of God to Ekron. And it came to pass, as the ark of God came to Ekron, that the Ekronites cried out, saying, They have brought about the ark of the God of Israel to us, to slay us and our people.', lemmas: { Ekron: "'Eqrōn", ark: "'ārōn" } },
  '5:11': { verse: '5:11', text: 'So they sent and gathered together all the lords of the Philistines, and said, Send away the ark of the God of Israel, and let it go again to his own place, that it slay us not, and our people: for there was a deadly destruction throughout all the city; the hand of God was very heavy there.', lemmas: { hand: "yād", God: "'ĕlōhîm" } },
  '5:12': { verse: '5:12', text: 'And the men that died not were smitten with the emerods: and the cry of the city went up to heaven.', lemmas: { emerods: "'ōphel", heaven: "šāmayim" } },
}
