export const sAmuelChapter3 = {
  '3:1': { verse: '3:1', text: 'And the child Samuel ministered unto the LORD before Eli. And the word of the LORD was precious in those days; there was no open vision.', lemmas: { Samuel: "Shemu'el", LORD: 'YHWH' } },
  '3:2': { verse: '3:2', text: 'And it came to pass at that time, when Eli was laid down in his place, and his eyes began to wax dim, that he could not see;', lemmas: { Eli: "'Eli", eyes: "'ayin" } },
  '3:3': { verse: '3:3', text: 'And ere the lamp of God went out in the temple of the LORD, where the ark of God was, and Samuel was laid down to sleep;', lemmas: { lamp: 'ner', ark: "'aron" } },
  '3:4': { verse: '3:4', text: 'That the LORD called Samuel: and he answered, Here am I.', lemmas: { LORD: 'YHWH', called: "qara'" } },
  '3:5': { verse: '3:5', text: 'And he ran unto Eli, and said, Here am I; for thou calledst me. And he said, I called not; lie down again. And he went and lay down.', lemmas: { Eli: "'Eli", calledst: "qara'" } },
  '3:6': { verse: '3:6', text: 'And the LORD called yet again, Samuel. And Samuel arose and went to Eli, and said, Here am I; for thou didst call me. And he answered, I called not, my son; lie down again.', lemmas: { LORD: 'YHWH', called: "qara'" } },
  '3:7': { verse: '3:7', text: 'Now Samuel did not yet know the LORD, neither was the word of the LORD yet revealed unto him.', lemmas: { LORD: 'YHWH', revealed: 'galah' } },
  '3:8': { verse: '3:8', text: 'And the LORD called Samuel again the third time. And he arose and went to Eli, and said, Here am I; for thou didst call me. And Eli perceived that the LORD had called the child.', lemmas: { LORD: 'YHWH', perceived: 'bin' } },
  '3:9': { verse: '3:9', text: 'Therefore Eli said unto Samuel, Go, lie down: and it shall be, if he call thee, that thou shalt say, Speak, LORD; for thy servant heareth. So Samuel went and lay down in his place.', lemmas: { Speak: 'dabar', servant: "'ebed" } },
  '3:10': { verse: '3:10', text: 'And the LORD came, and stood, and called as at other times, Samuel, Samuel. Then Samuel answered, Speak; for thy servant heareth.', lemmas: { LORD: 'YHWH', Speak: 'dabar' } },
  '3:11': { verse: '3:11', text: 'And the LORD said to Samuel, Behold, I will do a thing in Israel, at which both the ears of every one that heareth it shall tingle.', lemmas: { Israel: "Yisra'el", ears: "'ozen" } },
  '3:12': { verse: '3:12', text: 'In that day I will perform against Eli all things which I have spoken concerning his house: when I begin, I will also make an end.', lemmas: { Eli: "'Eli", house: 'bayith' } },
  '3:13': { verse: '3:13', text: 'For I have told him that I will judge his house for ever for the iniquity which he knoweth; because his sons made themselves vile, and he restrained them not.', lemmas: { judge: 'shaphat', iniquity: "'avon" } },
  '3:14': { verse: '3:14', text: 'And therefore I have sworn unto the house of Eli, that the iniquity of Eli\'s house shall not be purged with sacrifice nor offering for ever.', lemmas: { sacrifice: 'zebach', offering: 'minchah' } },
  '3:15': { verse: '3:15', text: 'And Samuel lay until the morning, and opened the doors of the house of the LORD. And Samuel feared to shew Eli the vision.', lemmas: { LORD: 'YHWH', feared: "yare'" } },
  '3:16': { verse: '3:16', text: 'Then Eli called Samuel, and said, Samuel, my son. And he answered, Here am I.', lemmas: { Eli: "'Eli", called: "qara'" } },
  '3:17': { verse: '3:17', text: 'And he said, What is the thing that the LORD hath said unto thee? I pray thee, hide it not from me: God do so to thee, and more also, if thou hide any thing from me of all the things that he said unto thee.', lemmas: { LORD: 'YHWH', hide: 'kachad' } },
  '3:18': { verse: '3:18', text: 'And Samuel told him every whit, and hid nothing from him. And he said, It is the LORD: let him do what seemeth him good.', lemmas: { Samuel: "Shemu'el", LORD: 'YHWH' } },
  '3:19': { verse: '3:19', text: 'And Samuel grew, and the LORD was with him, and did let none of his words fall to the ground.', lemmas: { Samuel: "Shemu'el", words: 'dabar' } },
  '3:20': { verse: '3:20', text: 'And all Israel from Dan even to Beer-sheba knew that Samuel was established to be a prophet of the LORD.', lemmas: { prophet: "nabi'", LORD: 'YHWH' } },
  '3:21': { verse: '3:21', text: 'And the LORD appeared again in Shiloh: for the LORD revealed himself to Samuel in Shiloh by the word of the LORD.', lemmas: { Shiloh: 'Shiloh', revealed: 'galah' } },
}
