import { ChapterData } from "@/lib/bible-data"

export const exodusChapter13: ChapterData = {
  "Exodus-13": {
    book: "Exodus",
    chapter: 13,
    twoWordSummary: "Firstborn Consecration",
    themeSummary: "God commands the consecration of the firstborn and the memorial of unleavened bread, then leads Israel toward the Red Sea by the pillar of cloud and fire.",
    sentenceDescription: "God commands the consecration of the firstborn and the memorial of unleavened bread, then leads Israel toward the Red Sea by the pillar of cloud and fire.",
    themeWords: [
      { word: "firstborn", strongNumber: "H1060", language: "Hebrew", lemma: "bekor", meaning: "firstborn; the eldest offspring" },
      { word: "unleavened", strongNumber: "H4682", language: "Hebrew", lemma: "matstsah", meaning: "unleavened bread; bread without yeast" }
    ],
    verses: [
      { verse: 1, text: "And the LORD spake unto Moses, saying,", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "Yehovah", meaning: "the personal name of Israel's God" }, { word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; Israelite leader and prophet" }] },
      { verse: 2, text: "Sanctify unto me all the firstborn, whatsoever openeth the womb among the children of Israel, both of man and of beast: it is mine.", highlightedWords: [{ word: "firstborn", strongNumber: "H1060", lemma: "bekor", meaning: "firstborn; the eldest offspring" }, { word: "womb", strongNumber: "H7358", lemma: "rechem", meaning: "womb; matrix" }] },
      { verse: 3, text: "And Moses said unto the people, Remember this day, in which ye came out from Egypt, out of the house of bondage; for by strength of hand the LORD brought you out from this place: there shall no leavened bread be eaten.", highlightedWords: [{ word: "Remember", strongNumber: "H2142", lemma: "zakar", meaning: "to remember; call to mind" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt; the land of the Nile" }] },
      { verse: 4, text: "This day came ye out in the month Abib.", highlightedWords: [{ word: "Abib", strongNumber: "H0024", lemma: "Abib", meaning: "Abib; the first month of the year" }, { word: "day", strongNumber: "H3117", lemma: "yom", meaning: "day; time period" }] },
      { verse: 5, text: "And it shall be when the LORD shall bring thee into the land of the Canaanites, and the Hittites, and the Amorites, and the Hivites, and the Jebusites, which he sware unto thy fathers to give thee, a land flowing with milk and honey, that thou shalt keep this service in this month.", highlightedWords: [{ word: "Canaanites", strongNumber: "H3669", lemma: "Kena'aniy", meaning: "Canaanites; inhabitants of Canaan" }, { word: "sware", strongNumber: "H7650", lemma: "shaba'", meaning: "to swear; take an oath" }] },
      { verse: 6, text: "Seven days thou shalt eat unleavened bread, and in the seventh day shall be a feast to the LORD.", highlightedWords: [{ word: "unleavened", strongNumber: "H4682", lemma: "matstsah", meaning: "unleavened bread; bread without yeast" }, { word: "feast", strongNumber: "H2282", lemma: "chag", meaning: "festival; pilgrimage feast" }] },
      { verse: 7, text: "Unleavened bread shall be eaten seven days; and there shall no leavened bread be seen with thee, neither shall there be leaven seen with thee in all thy quarters.", highlightedWords: [{ word: "leavened", strongNumber: "H2557", lemma: "chamets", meaning: "leavened; fermented" }, { word: "leaven", strongNumber: "H7603", lemma: "se'or", meaning: "leaven; sourdough starter" }] },
      { verse: 8, text: "And thou shalt shew thy son in that day, saying, This is done because of that which the LORD did unto me when I came forth out of Egypt.", highlightedWords: [{ word: "shew", strongNumber: "H5046", lemma: "nagad", meaning: "to declare; make known" }, { word: "son", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 9, text: "And it shall be for a sign unto thee upon thine hand, and for a memorial between thine eyes, that the LORD'S law may be in thy mouth: for with a strong hand hath the LORD brought thee out of Egypt.", highlightedWords: [{ word: "sign", strongNumber: "H0226", lemma: "'oth", meaning: "sign; token" }, { word: "law", strongNumber: "H8451", lemma: "torah", meaning: "instruction; law" }] },
      { verse: 10, text: "Thou shalt therefore keep this ordinance in his season from year to year.", highlightedWords: [{ word: "ordinance", strongNumber: "H2708", lemma: "chuqqah", meaning: "statute; prescribed rule" }, { word: "season", strongNumber: "H4150", lemma: "mo'ed", meaning: "appointed time; season" }] },
      { verse: 11, text: "And it shall be when the LORD shall bring thee into the land of the Canaanites, as he sware unto thee and to thy fathers, and shall give it thee,", highlightedWords: [{ word: "Canaanites", strongNumber: "H3669", lemma: "Kena'aniy", meaning: "Canaanites; inhabitants of Canaan" }, { word: "sware", strongNumber: "H7650", lemma: "shaba'", meaning: "to swear; take an oath" }] },
      { verse: 12, text: "That thou shalt set apart unto the LORD all that openeth the matrix, and every firstling that cometh of a beast which thou hast; the males shall be the LORD'S.", highlightedWords: [{ word: "matrix", strongNumber: "H7358", lemma: "rechem", meaning: "womb; matrix" }, { word: "firstling", strongNumber: "H1060", lemma: "bekor", meaning: "firstborn; firstling" }] },
      { verse: 13, text: "And every firstling of an ass thou shalt redeem with a lamb; and if thou wilt not redeem it, then thou shalt break his neck: and all the firstborn of man among thy children shalt thou redeem.", highlightedWords: [{ word: "redeem", strongNumber: "H6299", lemma: "padah", meaning: "to ransom; redeem" }, { word: "ass", strongNumber: "H2543", lemma: "chamor", meaning: "donkey; ass" }] },
      { verse: 14, text: "And it shall be when thy son asketh thee in time to come, saying, What is this? that thou shalt say unto him, By strength of hand the LORD brought us out from Egypt, from the house of bondage:", highlightedWords: [{ word: "asketh", strongNumber: "H7592", lemma: "sha'al", meaning: "to ask; inquire" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt; the land of the Nile" }] },
      { verse: 15, text: "And it came to pass, when Pharaoh would hardly let us go, that the LORD slew all the firstborn in the land of Egypt, both the firstborn of man, and the firstborn of beast: therefore I sacrifice to the LORD all that openeth the matrix, being males; but all the firstborn of my children I redeem.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh; title of Egyptian king" }, { word: "firstborn", strongNumber: "H1060", lemma: "bekor", meaning: "firstborn; the eldest offspring" }] },
      { verse: 16, text: "And it shall be for a token upon thine hand, and for frontlets between thine eyes: for by strength of hand the LORD brought us forth out of Egypt.", highlightedWords: [{ word: "token", strongNumber: "H0226", lemma: "'oth", meaning: "sign; token" }, { word: "frontlets", strongNumber: "H2903", lemma: "totafoth", meaning: "frontlets; forehead bands" }] },
      { verse: 17, text: "And it came to pass, when Pharaoh had let the people go, that God led them not through the way of the land of the Philistines, although that was near; for God said, Lest peradventure the people repent when they see war, and they return to Egypt:", highlightedWords: [{ word: "Philistines", strongNumber: "H6430", lemma: "Pelishtim", meaning: "Philistines; people of Philistia" }, { word: "war", strongNumber: "H4421", lemma: "milchamah", meaning: "battle; war" }] },
      { verse: 18, text: "But God led the people about, through the way of the wilderness of the Red sea: and the children of Israel went up harnessed out of the land of Egypt.", highlightedWords: [{ word: "wilderness", strongNumber: "H4057", lemma: "midbar", meaning: "wilderness; desert" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; name of the nation" }] },
      { verse: 19, text: "And Moses took the bones of Joseph with him: for he had straitly sworn the children of Israel, saying, God will surely visit you; and ye shall carry up my bones away hence with you.", highlightedWords: [{ word: "bones", strongNumber: "H6106", lemma: "etsem", meaning: "bone; substance; self" }, { word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "Joseph; son of Jacob" }] },
      { verse: 20, text: "And they took their journey from Succoth, and encamped in Etham, in the edge of the wilderness.", highlightedWords: [{ word: "Succoth", strongNumber: "H5523", lemma: "Sukkoth", meaning: "Succoth; a place of booths" }, { word: "Etham", strongNumber: "H0864", lemma: "Etham", meaning: "Etham; a place in the wilderness" }] },
      { verse: 21, text: "And the LORD went before them by day in a pillar of a cloud, to lead them the way; and by night in a pillar of fire, to give them light; to go by day and night:", highlightedWords: [{ word: "pillar", strongNumber: "H5982", lemma: "'ammud", meaning: "pillar; column" }, { word: "fire", strongNumber: "H0784", lemma: "esh", meaning: "fire" }] },
      { verse: 22, text: "He took not away the pillar of the cloud by day, nor the pillar of fire by night, from before the people.", highlightedWords: [{ word: "cloud", strongNumber: "H6051", lemma: "'anan", meaning: "cloud; mass of vapor" }, { word: "people", strongNumber: "H5971", lemma: "'am", meaning: "people; nation" }] }
    ]
  }
}
