import { ChapterData } from "@/lib/bible-data"

export const exodusChapter33: ChapterData = {
  "Exodus-33": {
    book: "Exodus",
    chapter: 33,
    twoWordSummary: "Divine Presence",
    themeSummary: "God promises His presence with Israel, meets with Moses, and reveals His glory while safeguarding Moses from seeing His full face.",
    sentenceDescription: "God promises His presence with Israel, meets with Moses, and reveals His glory while safeguarding Moses from seeing His full face.",
    themeWords: [
      { word: "presence", strongNumber: "H6440", lemma: "panim", meaning: "face, presence" },
      { word: "glory", strongNumber: "H3519", lemma: "kabod", meaning: "glory, honor, weight" },
    ],
    verses: [
      { verse: 1, text: "And the LORD said unto Moses, Depart, and go up hence, thou and the people which thou hast brought up out of the land of Egypt, unto the land which I sware unto Abraham, to Isaac, and to Jacob, saying, Unto thy seed will I give it:", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "Yehovah", meaning: "the personal name of Israel's God" }, { word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out" }] },
      { verse: 2, text: "And I will send an angel before thee; and I will drive out the Canaanite, the Amorite, and the Hittite, and the Perizzite, the Hivite, and the Jebusite:", highlightedWords: [{ word: "angel", strongNumber: "H4397", lemma: "malak", meaning: "messenger, angel" }, { word: "Canaanite", strongNumber: "H3669", lemma: "Kenaani", meaning: "inhabitant of Canaan" }] },
      { verse: 3, text: "Unto a land flowing with milk and honey: for I will not go up in the midst of thee; for thou art a stiffnecked people: lest I consume thee in the way.", highlightedWords: [{ word: "land", strongNumber: "H776", lemma: "eretz", meaning: "land, earth" }, { word: "stiffnecked", strongNumber: "H7186", lemma: "qasheh", meaning: "hard, severe, stiff" }] },
      { verse: 4, text: "And when the people heard these evil tidings, they mourned: and no man did put on him his ornaments.", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "am", meaning: "people, nation" }, { word: "mourned", strongNumber: "H56", lemma: "abal", meaning: "to mourn" }] },
      { verse: 5, text: "For the LORD had said unto Moses, Say unto the children of Israel, Ye are a stiffnecked people: I will come up into the midst of thee in a moment, and consume thee: therefore now put off thy ornaments from thee, that I may know what to do unto thee.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "Yehovah", meaning: "the personal name of Israel's God" }, { word: "consume", strongNumber: "H3615", lemma: "kalah", meaning: "to finish, consume" }] },
      { verse: 6, text: "And the children of Israel stripped themselves of their ornaments by the mount Horeb.", highlightedWords: [{ word: "children", strongNumber: "H1121", lemma: "ben", meaning: "son, child" }, { word: "Horeb", strongNumber: "H2722", lemma: "Choreb", meaning: "Horeb, the mountain of God" }] },
      { verse: 7, text: "And Moses took the tabernacle, and pitched it without the camp, afar off from the camp, and called it the Tabernacle of the congregation. And it came to pass, that every one which sought the LORD went out unto the tabernacle of the congregation, which was without the camp.", highlightedWords: [{ word: "tabernacle", strongNumber: "H168", lemma: "ohel", meaning: "tent, tabernacle" }, { word: "sought", strongNumber: "H1875", lemma: "darash", meaning: "to seek, inquire" }] },
      { verse: 8, text: "And it came to pass, when Moses went out unto the tabernacle, that all the people rose up, and stood every man at his tent door, and looked after Moses, until he was gone into the tabernacle.", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "am", meaning: "people, nation" }, { word: "tent", strongNumber: "H168", lemma: "ohel", meaning: "tent" }] },
      { verse: 9, text: "And it came to pass, as Moses entered into the tabernacle, the cloudy pillar descended, and stood at the door of the tabernacle, and the LORD talked with Moses.", highlightedWords: [{ word: "cloudy", strongNumber: "H6051", lemma: "anan", meaning: "cloud" }, { word: "LORD", strongNumber: "H3068", lemma: "Yehovah", meaning: "the personal name of Israel's God" }] },
      { verse: 10, text: "And all the people saw the cloudy pillar stand at the tabernacle door: and all the people rose up and worshipped, every man in his tent door.", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "am", meaning: "people, nation" }, { word: "worshipped", strongNumber: "H7812", lemma: "shachah", meaning: "to bow down, worship" }] },
      { verse: 11, text: "And the LORD spake unto Moses face to face, as a man speaketh unto his friend. And he turned again into the camp: but his servant Joshua, the son of Nun, a young man, departed not out of the tabernacle.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "Yehovah", meaning: "the personal name of Israel's God" }, { word: "Joshua", strongNumber: "H3091", lemma: "Yehoshua", meaning: "Joshua, the LORD is salvation" }] },
      { verse: 12, text: "And Moses said unto the LORD, See, thou sayest unto me, Bring up this people: and thou hast not let me know whom thou wilt send with me. Yet thou hast said, I know thee by name, and thou hast also found grace in my sight.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out" }, { word: "grace", strongNumber: "H2580", lemma: "chen", meaning: "grace, favor" }] },
      { verse: 13, text: "Now therefore, I pray thee, if I have found grace in thy sight, shew me now thy way, that I may know thee, that I may find grace in thy sight: and consider that this nation is thy people.", highlightedWords: [{ word: "grace", strongNumber: "H2580", lemma: "chen", meaning: "grace, favor" }, { word: "nation", strongNumber: "H1471", lemma: "goy", meaning: "nation, people" }] },
      { verse: 14, text: "And he said, My presence shall go with thee, and I will give thee rest.", highlightedWords: [{ word: "presence", strongNumber: "H6440", lemma: "panim", meaning: "face, presence" }, { word: "rest", strongNumber: "H4496", lemma: "manuach", meaning: "rest, resting place" }] },
      { verse: 15, text: "And he said unto him, If thy presence go not with me, carry us not up hence.", highlightedWords: [{ word: "presence", strongNumber: "H6440", lemma: "panim", meaning: "face, presence" }, { word: "carry", strongNumber: "H5927", lemma: "alah", meaning: "to go up, ascend" }] },
      { verse: 16, text: "For wherein shall it be known here that I and thy people have found grace in thy sight? is it not in that thou goest with us? so shall we be separated, I and thy people, from all the people that are upon the face of the earth.", highlightedWords: [{ word: "grace", strongNumber: "H2580", lemma: "chen", meaning: "grace, favor" }, { word: "separated", strongNumber: "H6395", lemma: "palah", meaning: "to distinguish, separate" }] },
      { verse: 17, text: "And the LORD said unto Moses, I will do this thing also that thou hast spoken: for thou hast found grace in my sight, and I know thee by name.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "Yehovah", meaning: "the personal name of Israel's God" }, { word: "grace", strongNumber: "H2580", lemma: "chen", meaning: "grace, favor" }] },
      { verse: 18, text: "And he said, I beseech thee, shew me thy glory.", highlightedWords: [{ word: "glory", strongNumber: "H3519", lemma: "kabod", meaning: "glory, honor" }, { word: "beseech", strongNumber: "H4994", lemma: "na", meaning: "I pray, please" }] },
      { verse: 19, text: "And he said, I will make all my goodness pass before thee, and I will proclaim the name of the LORD before thee; and will be gracious to whom I will be gracious, and will shew mercy on whom I will shew mercy.", highlightedWords: [{ word: "goodness", strongNumber: "H2898", lemma: "tub", meaning: "goodness, kindness" }, { word: "gracious", strongNumber: "H2603", lemma: "chanan", meaning: "to be gracious" }] },
      { verse: 20, text: "And he said, Thou canst not see my face: for there shall no man see me, and live.", highlightedWords: [{ word: "face", strongNumber: "H6440", lemma: "panim", meaning: "face, presence" }, { word: "see", strongNumber: "H7200", lemma: "raah", meaning: "to see, behold" }] },
      { verse: 21, text: "And the LORD said, Behold, there is a place by me, and thou shalt stand upon a rock:", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "Yehovah", meaning: "the personal name of Israel's God" }, { word: "rock", strongNumber: "H6697", lemma: "tsur", meaning: "rock, stone" }] },
      { verse: 22, text: "And it shall come to pass, while my glory passeth by, that I will put thee in a clift of the rock, and will cover thee with my hand while I pass by:", highlightedWords: [{ word: "glory", strongNumber: "H3519", lemma: "kabod", meaning: "glory, honor" }, { word: "clift", strongNumber: "H5366", lemma: "niqrah", meaning: "cleft, fissure" }] },
      { verse: 23, text: "And I will take away mine hand, and thou shalt see my back parts: but my face shall not be seen.", highlightedWords: [{ word: "hand", strongNumber: "H3027", lemma: "yad", meaning: "hand" }, { word: "back", strongNumber: "H268", lemma: "achor", meaning: "back, behind" }] }
    ]
  }
}
