import { ChapterData } from "@/lib/bible-data"

export const exodusChapter4: ChapterData = {
  "Exodus-4": {
    book: "Exodus",
    chapter: 4,
    twoWordSummary: "Signs Given",
    themeSummary: "The LORD equips Moses with signs, appoints Aaron as his spokesman, and sends them to Egypt where the people believe.",
    sentenceDescription: "The LORD equips Moses with signs, appoints Aaron as his spokesman, and sends them to Egypt where the people believe.",
    themeWords: [
      { word: "signs", strongNumber: "H226", language: "Hebrew", lemma: "'owth", meaning: "a sign, token, or miracle given as evidence" },
      { word: "Moses", strongNumber: "H4872", language: "Hebrew", lemma: "Mosheh", meaning: "Moses; 'drawn out'" }
    ],
    verses: [
      { verse: 1, text: "And Moses answered and said, But, behold, they will not believe me, nor hearken unto my voice: for they will say, The LORD hath not appeared unto thee.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; 'drawn out'" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the proper name of the God of Israel" }] },
      { verse: 2, text: "And the LORD said unto him, What is that in thine hand? And he said, A rod.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the proper name of the God of Israel" }, { word: "rod", strongNumber: "H4294", lemma: "matteh", meaning: "a staff, rod" }] },
      { verse: 3, text: "And he said, Cast it on the ground. And he cast it on the ground, and it became a serpent; and Moses fled from before it.", highlightedWords: [{ word: "serpent", strongNumber: "H5175", lemma: "nachash", meaning: "a serpent, snake" }, { word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; 'drawn out'" }] },
      { verse: 4, text: "And the LORD said unto Moses, Put forth thine hand, and take it by the tail. And he put forth his hand, and caught it, and it became a rod in his hand:", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the proper name of the God of Israel" }, { word: "hand", strongNumber: "H3027", lemma: "yad", meaning: "hand, power" }] },
      { verse: 5, text: "That they may believe that the LORD God of their fathers, the God of Abraham, the God of Isaac, and the God of Jacob, hath appeared unto thee.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the proper name of the God of Israel" }, { word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; mighty one" }] },
      { verse: 6, text: "And the LORD said furthermore unto him, Put now thine hand into thy bosom. And he put his hand into his bosom: and when he took it out, behold, his hand was leprous as snow.", highlightedWords: [{ word: "hand", strongNumber: "H3027", lemma: "yad", meaning: "hand, power" }, { word: "bosom", strongNumber: "H2436", lemma: "cheq", meaning: "bosom, chest" }] },
      { verse: 7, text: "And he said, Put thine hand into thy bosom again. And he put his hand into his bosom again; and plucked it out of his bosom, and, behold, it was turned again as his other flesh.", highlightedWords: [{ word: "bosom", strongNumber: "H2436", lemma: "cheq", meaning: "bosom, chest" }, { word: "flesh", strongNumber: "H1320", lemma: "basar", meaning: "flesh, body" }] },
      { verse: 8, text: "And it shall come to pass, if they will not believe thee, neither hearken to the voice of the first sign, that they will believe the voice of the latter sign.", highlightedWords: [{ word: "sign", strongNumber: "H226", lemma: "'owth", meaning: "a sign, token, or miracle" }, { word: "voice", strongNumber: "H6963", lemma: "qol", meaning: "voice, sound" }] },
      { verse: 9, text: "And it shall come to pass, if they will not believe also these two signs, neither hearken unto thy voice, that thou shalt take of the water of the river, and pour it upon the dry land: and the water which thou takest out of the river shall become blood upon the dry land.", highlightedWords: [{ word: "water", strongNumber: "H4325", lemma: "mayim", meaning: "water(s)" }, { word: "blood", strongNumber: "H1818", lemma: "dam", meaning: "blood" }] },
      { verse: 10, text: "And Moses said unto the LORD, O my Lord, I am not eloquent, neither heretofore, nor since thou hast spoken unto thy servant: but I am slow of speech, and of a slow tongue.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; 'drawn out'" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the proper name of the God of Israel" }] },
      { verse: 11, text: "And the LORD said unto him, Who hath made man's mouth? or who maketh the dumb, or deaf, or the seeing, or the blind? have not I the LORD?", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the proper name of the God of Israel" }, { word: "mouth", strongNumber: "H6310", lemma: "peh", meaning: "mouth, speech" }] },
      { verse: 12, text: "Now therefore go, and I will be with thy mouth, and teach thee what thou shalt say.", highlightedWords: [{ word: "mouth", strongNumber: "H6310", lemma: "peh", meaning: "mouth, speech" }, { word: "teach", strongNumber: "H3384", lemma: "yarah", meaning: "to instruct, teach, direct" }] },
      { verse: 13, text: "And he said, O my Lord, send, I pray thee, by the hand of him whom thou wilt send.", highlightedWords: [{ word: "Lord", strongNumber: "H136", lemma: "Adonai", meaning: "Lord, Master" }, { word: "send", strongNumber: "H7971", lemma: "shalach", meaning: "to send, dispatch" }] },
      { verse: 14, text: "And the anger of the LORD was kindled against Moses, and he said, Is not Aaron the Levite thy brother? I know that he can speak well. And also, behold, he cometh forth to meet thee: and when he seeth thee, he will be glad in his heart.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the proper name of the God of Israel" }, { word: "Aaron", strongNumber: "H175", lemma: "Aharon", meaning: "Aaron; brother of Moses" }] },
      { verse: 15, text: "And thou shalt speak unto him, and put words in his mouth: and I will be with thy mouth, and with his mouth, and will teach you what ye shall do.", highlightedWords: [{ word: "speak", strongNumber: "H1696", lemma: "dabar", meaning: "to speak, declare" }, { word: "mouth", strongNumber: "H6310", lemma: "peh", meaning: "mouth, speech" }] },
      { verse: 16, text: "And he shall be thy spokesman unto the people: and he shall be, even he shall be to thee instead of a mouth, and thou shalt be to him instead of God.", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "'am", meaning: "people, nation" }, { word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; mighty one" }] },
      { verse: 17, text: "And thou shalt take this rod in thine hand, wherewith thou shalt do signs.", highlightedWords: [{ word: "rod", strongNumber: "H4294", lemma: "matteh", meaning: "a staff, rod" }, { word: "signs", strongNumber: "H226", lemma: "'owth", meaning: "signs, tokens, miracles" }] },
      { verse: 18, text: "And Moses went and returned to Jethro his father in law, and said unto him, Let me go, I pray thee, and return unto my brethren which are in Egypt, and see whether they be yet alive. And Jethro said to Moses, Go in peace.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; 'drawn out'" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 19, text: "And the LORD said unto Moses in Midian, Go, return into Egypt: for all the men are dead which sought thy life.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the proper name of the God of Israel" }, { word: "Midian", strongNumber: "H4080", lemma: "Midyan", meaning: "Midian; a region/people east of the Red Sea" }] },
      { verse: 20, text: "And Moses took his wife and his sons, and set them upon an ass, and he returned to the land of Egypt: and Moses took the rod of God in his hand.", highlightedWords: [{ word: "rod", strongNumber: "H4294", lemma: "matteh", meaning: "a staff, rod" }, { word: "ass", strongNumber: "H2543", lemma: "chamor", meaning: "a donkey" }] },
      { verse: 21, text: "And the LORD said unto Moses, When thou goest to return into Egypt, see that thou do all those wonders before Pharaoh, which I have put in thine hand: but I will harden his heart, that he shall not let the people go.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh; title of the Egyptian king" }, { word: "harden", strongNumber: "H2388", lemma: "chazaq", meaning: "to strengthen, make firm, harden" }] },
      { verse: 22, text: "And thou shalt say unto Pharaoh, Thus saith the LORD, Israel is my son, even my firstborn:", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; the people and nation" }, { word: "firstborn", strongNumber: "H1060", lemma: "bekor", meaning: "firstborn" }] },
      { verse: 23, text: "And I say unto thee, Let my son go, that he may serve me: and if thou refuse to let him go, behold, I will slay thy son, even thy firstborn.", highlightedWords: [{ word: "firstborn", strongNumber: "H1060", lemma: "bekor", meaning: "firstborn" }, { word: "slay", strongNumber: "H2026", lemma: "harag", meaning: "to kill, slay" }] },
      { verse: 24, text: "And it came to pass by the way in the inn, that the LORD met him, and sought to kill him.", highlightedWords: [{ word: "inn", strongNumber: "H4411", lemma: "malon", meaning: "a lodging place, inn" }, { word: "kill", strongNumber: "H4191", lemma: "muwth", meaning: "to die; to put to death" }] },
      { verse: 25, text: "Then Zipporah took a sharp stone, and cut off the foreskin of her son, and cast it at his feet, and said, Surely a bloody husband art thou to me.", highlightedWords: [{ word: "Zipporah", strongNumber: "H6855", lemma: "Tsipporah", meaning: "Zipporah; wife of Moses" }, { word: "foreskin", strongNumber: "H6190", lemma: "'orlah", meaning: "foreskin; uncircumcision" }] },
      { verse: 26, text: "So he let him go: then she said, A bloody husband thou art, because of the circumcision.", highlightedWords: [{ word: "circumcision", strongNumber: "H4139", lemma: "mulah", meaning: "circumcision" }, { word: "bloody", strongNumber: "H1818", lemma: "dam", meaning: "blood; bloody" }] },
      { verse: 27, text: "And the LORD said to Aaron, Go into the wilderness to meet Moses. And he went, and met him in the mount of God, and kissed him.", highlightedWords: [{ word: "Aaron", strongNumber: "H175", lemma: "Aharon", meaning: "Aaron; brother of Moses" }, { word: "wilderness", strongNumber: "H4057", lemma: "midbar", meaning: "wilderness, desert" }] },
      { verse: 28, text: "And Moses told Aaron all the words of the LORD who had sent him, and all the signs which he had commanded him.", highlightedWords: [{ word: "signs", strongNumber: "H226", lemma: "'owth", meaning: "signs, tokens, miracles" }, { word: "sent", strongNumber: "H7971", lemma: "shalach", meaning: "to send, dispatch" }] },
      { verse: 29, text: "And Moses and Aaron went and gathered together all the elders of the children of Israel:", highlightedWords: [{ word: "elders", strongNumber: "H2205", lemma: "zaqen", meaning: "elders; aged men; leaders" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; the people and nation" }] },
      { verse: 30, text: "And Aaron spake all the words which the LORD had spoken unto Moses, and did the signs in the sight of the people.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the proper name of the God of Israel" }, { word: "people", strongNumber: "H5971", lemma: "'am", meaning: "people, nation" }] },
      { verse: 31, text: "And the people believed: and when they heard that the LORD had visited the children of Israel, and that he had looked upon their affliction, then they bowed their heads and worshipped.", highlightedWords: [{ word: "believed", strongNumber: "H539", lemma: "'aman", meaning: "to believe, trust, be faithful" }, { word: "worshipped", strongNumber: "H7812", lemma: "shachah", meaning: "to bow down, worship" }] }
    ]
  }
}
