export const exodusChapter12 = [
  {
    book: 'Exodus',
    chapter: 12,
    verse: 1,
    text: 'And the LORD spake unto Moses and Aaron in the land of Egypt, saying,',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'LORD', strongNumber: 'H3068', lemma: 'Yehovah', meaning: 'the personal name of Israel\'s God' },
      { word: 'Egypt', strongNumber: 'H4714', lemma: 'Mitsrayim', meaning: 'Egypt; the land of the Nile' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 2,
    text: 'This month shall be unto you the beginning of months: it shall be the first month of the year to you.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'month', strongNumber: 'H2320', lemma: 'chodesh', meaning: 'new moon; month' },
      { word: 'year', strongNumber: 'H8141', lemma: 'shanah', meaning: 'year' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 3,
    text: 'Speak ye unto all the congregation of Israel, saying, In the tenth day of this month they shall take to them every man a lamb, according to the house of their fathers, a lamb for an house:',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'congregation', strongNumber: 'H5712', lemma: 'edah', meaning: 'assembly; congregation' },
      { word: 'Israel', strongNumber: 'H3478', lemma: 'Yisra\'el', meaning: 'Israel; God prevails' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 4,
    text: 'And if the household be too little for the lamb, let him and his neighbour next unto his house take it according to the number of the souls; every man according to his eating shall make your count for the lamb.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'house', strongNumber: 'H1004', lemma: 'bayith', meaning: 'house; household' },
      { word: 'souls', strongNumber: 'H5315', lemma: 'nephesh', meaning: 'soul; life; person' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 5,
    text: 'Your lamb shall be without blemish, a male of the first year: ye shall take it out from the sheep, or from the goats:',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'blemish', strongNumber: 'H3971', lemma: 'mum', meaning: 'defect; blemish' },
      { word: 'male', strongNumber: 'H2145', lemma: 'zakar', meaning: 'male' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 6,
    text: 'And ye shall keep it up until the fourteenth day of the same month: and the whole assembly of the congregation of Israel shall kill it in the evening.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'assembly', strongNumber: 'H6951', lemma: 'qahal', meaning: 'assembly; congregation' },
      { word: 'evening', strongNumber: 'H6153', lemma: 'ereb', meaning: 'evening; sunset' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 7,
    text: 'And they shall take of the blood, and strike it on the two side posts and on the upper door post of the houses, wherein they shall eat it.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'blood', strongNumber: 'H1818', lemma: 'dam', meaning: 'blood' },
      { word: 'houses', strongNumber: 'H1004', lemma: 'bayith', meaning: 'houses; households' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 8,
    text: 'And they shall eat the flesh in that night, roast with fire, and unleavened bread; and with bitter herbs they shall eat it.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'unleavened bread', strongNumber: 'H4682', lemma: 'matstsah', meaning: 'unleavened bread' },
      { word: 'bitter herbs', strongNumber: 'H4844', lemma: 'maror', meaning: 'bitterness; bitter herb' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 9,
    text: 'Eat not of it raw, nor sodden at all with water, but roast with fire; his head with his legs, and with the purtenance thereof.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'water', strongNumber: 'H4325', lemma: 'mayim', meaning: 'water' },
      { word: 'head', strongNumber: 'H7218', lemma: 'ro\'sh', meaning: 'head; top; chief' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 10,
    text: 'And ye shall let nothing of it remain until the morning; and that which remaineth of it until the morning ye shall burn with fire.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'morning', strongNumber: 'H1242', lemma: 'boqer', meaning: 'morning' },
      { word: 'fire', strongNumber: 'H784', lemma: 'esh', meaning: 'fire' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 11,
    text: 'And thus shall ye eat it; with your loins girded, your shoes on your feet, and your staff in your hand; and ye shall eat it in haste: it is the LORD\'S passover.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'LORD\'S', strongNumber: 'H3068', lemma: 'Yehovah', meaning: 'the personal name of Israel\'s God' },
      { word: 'passover', strongNumber: 'H6453', lemma: 'pesach', meaning: 'Passover sacrifice/meal' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 12,
    text: 'For I will pass through the land of Egypt this night, and will smite all the firstborn in the land of Egypt, both man and beast; and against all the gods of Egypt I will execute judgment: I am the LORD.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'firstborn', strongNumber: 'H1060', lemma: 'bekor', meaning: 'firstborn' },
      { word: 'gods', strongNumber: 'H430', lemma: 'elohim', meaning: 'gods; God' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 13,
    text: 'And the blood shall be to you for a token upon the houses where ye are: and when I see the blood, I will pass over you, and the plague shall not be upon you to destroy you, when I smite the land of Egypt.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'blood', strongNumber: 'H1818', lemma: 'dam', meaning: 'blood' },
      { word: 'plague', strongNumber: 'H5061', lemma: 'nega\'', meaning: 'stroke; plague' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 14,
    text: 'And this day shall be unto you for a memorial; and ye shall keep it a feast to the LORD throughout your generations; ye shall keep it a feast by an ordinance for ever.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'memorial', strongNumber: 'H2146', lemma: 'zikaron', meaning: 'memorial; remembrance' },
      { word: 'feast', strongNumber: 'H2282', lemma: 'chag', meaning: 'festival; feast' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 15,
    text: 'Seven days shall ye eat unleavened bread; even the first day ye shall put away leaven out of your houses: for whosoever eateth leavened bread from the first day until the seventh day, that soul shall be cut off from Israel.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'unleavened bread', strongNumber: 'H4682', lemma: 'matstsah', meaning: 'unleavened bread' },
      { word: 'Israel', strongNumber: 'H3478', lemma: 'Yisra\'el', meaning: 'Israel; God prevails' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 16,
    text: 'And in the first day there shall be an holy convocation, and in the seventh day there shall be an holy convocation to you; no manner of work shall be done in them, save that which every man must eat, that only may be done of you.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'holy', strongNumber: 'H6944', lemma: 'qodesh', meaning: 'holy; holiness' },
      { word: 'work', strongNumber: 'H4399', lemma: 'melakah', meaning: 'work; occupation' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 17,
    text: 'And ye shall observe the feast of unleavened bread; for in this selfsame day have I brought your armies out of the land of Egypt: therefore shall ye observe this day in your generations by an ordinance for ever.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'observe', strongNumber: 'H8104', lemma: 'shamar', meaning: 'to keep; observe' },
      { word: 'armies', strongNumber: 'H6635', lemma: 'tsaba\'', meaning: 'hosts; armies' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 18,
    text: 'In the first month, on the fourteenth day of the month at even, ye shall eat unleavened bread, until the one and twentieth day of the month at even.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'month', strongNumber: 'H2320', lemma: 'chodesh', meaning: 'new moon; month' },
      { word: 'even', strongNumber: 'H6153', lemma: 'ereb', meaning: 'evening; sunset' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 19,
    text: 'Seven days shall there be no leaven found in your houses: for whosoever eateth that which is leavened, even that soul shall be cut off from the congregation of Israel, whether he be a stranger, or born in the land.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'leaven', strongNumber: 'H7603', lemma: 'se\'or', meaning: 'leaven; sourdough' },
      { word: 'congregation', strongNumber: 'H5712', lemma: 'edah', meaning: 'assembly; congregation' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 20,
    text: 'Ye shall eat nothing leavened; in all your habitations shall ye eat unleavened bread.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'eat', strongNumber: 'H398', lemma: 'akal', meaning: 'to eat; consume' },
      { word: 'unleavened bread', strongNumber: 'H4682', lemma: 'matstsah', meaning: 'unleavened bread' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 21,
    text: 'Then Moses called for all the elders of Israel, and said unto them, Draw out and take you a lamb according to your families, and kill the passover.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'elders', strongNumber: 'H2205', lemma: 'zaqen', meaning: 'elder; old man; leader' },
      { word: 'passover', strongNumber: 'H6453', lemma: 'pesach', meaning: 'Passover sacrifice/meal' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 22,
    text: 'And ye shall take a bunch of hyssop, and dip it in the blood that is in the bason, and strike the lintel and the two side posts with the blood that is in the bason; and none of you shall go out at the door of his house until the morning.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'hyssop', strongNumber: 'H231', lemma: 'ezob', meaning: 'hyssop plant' },
      { word: 'lintel', strongNumber: 'H4947', lemma: 'mashqoph', meaning: 'lintel; door-beam' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 23,
    text: 'For the LORD will pass through to smite the Egyptians; and when he seeth the blood upon the lintel and on the two side posts, the LORD will pass over the door, and will not suffer the destroyer to come in unto your houses to smite you.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'LORD', strongNumber: 'H3068', lemma: 'Yehovah', meaning: 'the personal name of Israel\'s God' },
      { word: 'door', strongNumber: 'H6607', lemma: 'petach', meaning: 'doorway; entrance' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 24,
    text: 'And ye shall observe this thing for an ordinance to thee and to thy sons for ever.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'ordinance', strongNumber: 'H2708', lemma: 'chuqqah', meaning: 'statute; ordinance' },
      { word: 'sons', strongNumber: 'H1121', lemma: 'ben', meaning: 'son; child' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 25,
    text: 'And it shall come to pass, when ye be come to the land which the LORD will give you, according as he hath promised, that ye shall keep this service.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'LORD', strongNumber: 'H3068', lemma: 'Yehovah', meaning: 'the personal name of Israel\'s God' },
      { word: 'land', strongNumber: 'H776', lemma: 'erets', meaning: 'land; earth' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 26,
    text: 'And it shall come to pass, when your children shall say unto you, What mean ye by this service?',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'children', strongNumber: 'H1121', lemma: 'ben', meaning: 'sons; children' },
      { word: 'service', strongNumber: 'H5656', lemma: 'abodah', meaning: 'service; labor; ritual service' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 27,
    text: 'That ye shall say, It is the sacrifice of the LORD\'S passover, who passed over the houses of the children of Israel in Egypt, when he smote the Egyptians, and delivered our houses. And the people bowed the head and worshipped.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'sacrifice', strongNumber: 'H2077', lemma: 'zebach', meaning: 'sacrifice' },
      { word: 'worshipped', strongNumber: 'H7812', lemma: 'shachah', meaning: 'to bow down; worship' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 28,
    text: 'And the children of Israel went away, and did as the LORD had commanded Moses and Aaron, so did they.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'commanded', strongNumber: 'H6680', lemma: 'tsavah', meaning: 'to command; order' },
      { word: 'Israel', strongNumber: 'H3478', lemma: 'Yisra\'el', meaning: 'Israel; God prevails' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 29,
    text: 'And it came to pass, that at midnight the LORD smote all the firstborn in the land of Egypt, from the firstborn of Pharaoh that sat on his throne unto the firstborn of the captive that was in the dungeon; and all the firstborn of cattle.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'LORD', strongNumber: 'H3068', lemma: 'Yehovah', meaning: 'the personal name of Israel\'s God' },
      { word: 'firstborn', strongNumber: 'H1060', lemma: 'bekor', meaning: 'firstborn' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 30,
    text: 'And Pharaoh rose up in the night, he, and all his servants, and all the Egyptians; and there was a great cry in Egypt; for there was not a house where there was not one dead.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'Pharaoh', strongNumber: 'H6547', lemma: 'Par\'oh', meaning: 'Pharaoh, title of Egypt\'s king' },
      { word: 'dead', strongNumber: 'H4191', lemma: 'muwth', meaning: 'to die; dead' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 31,
    text: 'And he called for Moses and Aaron by night, and said, Rise up, and get you forth from among my people, both ye and the children of Israel; and go, serve the LORD, as ye have said.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'serve', strongNumber: 'H5647', lemma: 'abad', meaning: 'to serve; work; worship' },
      { word: 'LORD', strongNumber: 'H3068', lemma: 'Yehovah', meaning: 'the personal name of Israel\'s God' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 32,
    text: 'Also take your flocks and your herds, as ye have said, and be gone; and bless me also.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'flocks', strongNumber: 'H6629', lemma: 'tson', meaning: 'flock(s); sheep and goats' },
      { word: 'bless', strongNumber: 'H1288', lemma: 'barak', meaning: 'to bless' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 33,
    text: 'And the Egyptians were urgent upon the people, that they might send them out of the land in haste; for they said, We be all dead men.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'Egyptians', strongNumber: 'H4713', lemma: 'Mitsriy', meaning: 'Egyptian(s)' },
      { word: 'dead', strongNumber: 'H4191', lemma: 'muwth', meaning: 'to die; dead' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 34,
    text: 'And the people took their dough before it was leavened, their kneadingtroughs being bound up in their clothes upon their shoulders.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'dough', strongNumber: 'H1217', lemma: 'batsaq', meaning: 'dough' },
      { word: 'leavened', strongNumber: 'H2557', lemma: 'chamets', meaning: 'leavened; that which is leavened' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 35,
    text: 'And the children of Israel did according to the word of Moses; and they borrowed of the Egyptians jewels of silver, and jewels of gold, and raiment:',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'silver', strongNumber: 'H3701', lemma: 'keseph', meaning: 'silver; money' },
      { word: 'gold', strongNumber: 'H2091', lemma: 'zahab', meaning: 'gold' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 36,
    text: 'And the LORD gave the people favour in the sight of the Egyptians, so that they lent unto them such things as they required. And they spoiled the Egyptians.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'LORD', strongNumber: 'H3068', lemma: 'Yehovah', meaning: 'the personal name of Israel\'s God' },
      { word: 'favour', strongNumber: 'H2580', lemma: 'chen', meaning: 'grace; favour' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 37,
    text: 'And the children of Israel journeyed from Rameses to Succoth, about six hundred thousand on foot that were men, beside children.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'Rameses', strongNumber: 'H7486', lemma: 'Ra\'amses', meaning: 'Rameses, a city in Egypt' },
      { word: 'Succoth', strongNumber: 'H5523', lemma: 'Sukkoth', meaning: 'Succoth, a place of booths' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 38,
    text: 'And a mixed multitude went up also with them; and flocks, and herds, even very much cattle.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'flocks', strongNumber: 'H6629', lemma: 'tson', meaning: 'flock(s); sheep and goats' },
      { word: 'cattle', strongNumber: 'H4735', lemma: 'miqneh', meaning: 'livestock; cattle; possessions' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 39,
    text: 'And they baked unleavened cakes of the dough which they brought forth out of Egypt, for it was not leavened; because they were thrust out of Egypt, and could not tarry, neither had they prepared for themselves any victual.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'unleavened cakes', strongNumber: 'H4682', lemma: 'matstsah', meaning: 'unleavened bread/cakes' },
      { word: 'Egypt', strongNumber: 'H4714', lemma: 'Mitsrayim', meaning: 'Egypt; the land of the Nile' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 40,
    text: 'Now the sojourning of the children of Israel, who dwelt in Egypt, was four hundred and thirty years.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'sojourning', strongNumber: 'H4186', lemma: 'moshab', meaning: 'dwelling; sojourning' },
      { word: 'years', strongNumber: 'H8141', lemma: 'shanah', meaning: 'years' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 41,
    text: 'And it came to pass at the end of the four hundred and thirty years, even the selfsame day it came to pass, that all the hosts of the LORD went out from the land of Egypt.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'hosts', strongNumber: 'H6635', lemma: 'tsaba\'', meaning: 'armies; hosts' },
      { word: 'LORD', strongNumber: 'H3068', lemma: 'Yehovah', meaning: 'the personal name of Israel\'s God' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 42,
    text: 'It is a night to be much observed unto the LORD for bringing them out from the land of Egypt: this is that night of the LORD to be observed of all the children of Israel in their generations.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'night', strongNumber: 'H3915', lemma: 'layil', meaning: 'night' },
      { word: 'generations', strongNumber: 'H1755', lemma: 'dor', meaning: 'generation(s)' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 43,
    text: 'And the LORD said unto Moses and Aaron, This is the ordinance of the passover: There shall no stranger eat thereof:',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'ordinance', strongNumber: 'H2708', lemma: 'chuqqah', meaning: 'statute; ordinance' },
      { word: 'passover', strongNumber: 'H6453', lemma: 'pesach', meaning: 'Passover sacrifice/meal' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 44,
    text: 'But every man\'s servant that is bought for money, when thou hast circumcised him, then shall he eat thereof.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'servant', strongNumber: 'H5650', lemma: 'ebed', meaning: 'servant; slave' },
      { word: 'circumcised', strongNumber: 'H4135', lemma: 'mul', meaning: 'to circumcise' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 45,
    text: 'A foreigner and an hired servant shall not eat thereof.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'foreigner', strongNumber: 'H8453', lemma: 'toshav', meaning: 'resident foreigner; sojourner' },
      { word: 'eat', strongNumber: 'H398', lemma: 'akal', meaning: 'to eat; consume' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 46,
    text: 'In one house shall it be eaten: thou shalt not carry forth ought of the flesh abroad out of the house; neither shall ye break a bone thereof.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'house', strongNumber: 'H1004', lemma: 'bayith', meaning: 'house; household' },
      { word: 'bone', strongNumber: 'H6106', lemma: 'etsem', meaning: 'bone' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 47,
    text: 'All the congregation of Israel shall keep it.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'congregation', strongNumber: 'H5712', lemma: 'edah', meaning: 'assembly; congregation' },
      { word: 'Israel', strongNumber: 'H3478', lemma: 'Yisra\'el', meaning: 'Israel; God prevails' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 48,
    text: 'And when a stranger shall sojourn with thee, and will keep the passover to the LORD, let all his males be circumcised, and then let him come near and keep it; and he shall be as one that is born in the land: for no uncircumcised person shall eat thereof.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'stranger', strongNumber: 'H1616', lemma: 'ger', meaning: 'sojourner; stranger' },
      { word: 'circumcised', strongNumber: 'H4135', lemma: 'mul', meaning: 'to circumcise' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 49,
    text: 'One law shall be to him that is homeborn, and unto the stranger that sojourneth among you.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'law', strongNumber: 'H8451', lemma: 'torah', meaning: 'law; instruction' },
      { word: 'stranger', strongNumber: 'H1616', lemma: 'ger', meaning: 'sojourner; stranger' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 50,
    text: 'Thus did all the children of Israel; as the LORD commanded Moses and Aaron, so did they.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'commanded', strongNumber: 'H6680', lemma: 'tsavah', meaning: 'to command; order' },
      { word: 'Israel', strongNumber: 'H3478', lemma: 'Yisra\'el', meaning: 'Israel; God prevails' },
    ],
  },
  {
    book: 'Exodus',
    chapter: 12,
    verse: 51,
    text: 'And it came to pass the selfsame day, that the LORD did bring the children of Israel out of the land of Egypt by their armies.',
    themeTitle: 'Passover Instituted',
    highlightedWords: [
      { word: 'LORD', strongNumber: 'H3068', lemma: 'Yehovah', meaning: 'the personal name of Israel\'s God' },
      { word: 'armies', strongNumber: 'H6635', lemma: 'tsaba\'', meaning: 'hosts; armies' },
    ],
  },
];
