import { ChapterData } from "@/lib/bible-data"

export const exodusChapter18: ChapterData = {
  "Exodus-18": {
    book: "Exodus",
    chapter: 18,
    twoWordSummary: "Wise Delegation",
    themeSummary: "Jethro visits Moses, blesses the LORD for deliverance, and wisely counsels him to appoint capable rulers to judge the people.",
    sentenceDescription: "Jethro visits Moses, blesses the LORD for deliverance, and wisely counsels him to appoint capable rulers to judge the people.",
    themeWords: [
      { word: "Jethro", strongNumber: "H3503", language: "Hebrew", lemma: "Yithro", meaning: "Jethro; Moses' father-in-law; his excellence/abundance" },
      { word: "rulers", strongNumber: "H8269", language: "Hebrew", lemma: "sar", meaning: "chief, prince, ruler, official" }
    ],
    verses: [
      { verse: 1, text: "When Jethro, the priest of Midian, Moses' father in law, heard of all that God had done for Moses, and for Israel his people, and that the LORD had brought Israel out of Egypt;", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out (Israel's leader)" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the covenant name of God, Yahweh" }] },
      { verse: 2, text: "Then Jethro, Moses' father in law, took Zipporah, Moses' wife, after he had sent her back,", highlightedWords: [{ word: "Jethro", strongNumber: "H3503", lemma: "Yithro", meaning: "Jethro; Moses' father-in-law; his excellence/abundance" }, { word: "Zipporah", strongNumber: "H6855", lemma: "Tsipporah", meaning: "Zipporah; 'bird' (Moses' wife)" }] },
      { verse: 3, text: "And her two sons; of which the name of the one was Gershom; for he said, I have been an alien in a strange land:", highlightedWords: [{ word: "Gershom", strongNumber: "H1647", lemma: "Gershom", meaning: "Gershom; 'sojourner there'" }, { word: "land", strongNumber: "H776", lemma: "'erets", meaning: "land, earth, territory" }] },
      { verse: 4, text: "And the name of the other was Eliezer; for the God of my father, said he, was mine help, and delivered me from the sword of Pharaoh:", highlightedWords: [{ word: "Eliezer", strongNumber: "H461", lemma: "'Eli'ezer", meaning: "Eliezer; 'my God is help'" }, { word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God; mighty one" }] },
      { verse: 5, text: "And Jethro, Moses' father in law, came with his sons and his wife unto Moses into the wilderness, where he encamped at the mount of God:", highlightedWords: [{ word: "wilderness", strongNumber: "H4057", lemma: "midbar", meaning: "wilderness, desert, pasture" }, { word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God; mighty one" }] },
      { verse: 6, text: "And he said unto Moses, I thy father in law Jethro am come unto thee, and thy wife, and her two sons with her.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out (Israel's leader)" }, { word: "Jethro", strongNumber: "H3503", lemma: "Yithro", meaning: "Jethro; Moses' father-in-law; his excellence/abundance" }] },
      { verse: 7, text: "And Moses went out to meet his father in law, and did obeisance, and kissed him; and they asked each other of their welfare; and they came into the tent.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out (Israel's leader)" }, { word: "tent", strongNumber: "H168", lemma: "'ohel", meaning: "tent, dwelling" }] },
      { verse: 8, text: "And Moses told his father in law all that the LORD had done unto Pharaoh and to the Egyptians for Israel's sake, and all the travail that had come upon them by the way, and how the LORD delivered them.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the covenant name of God, Yahweh" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh; title of Egypt's king" }] },
      { verse: 9, text: "And Jethro rejoiced for all the goodness which the LORD had done to Israel, whom he had delivered out of the hand of the Egyptians.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the covenant name of God, Yahweh" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; God strives" }] },
      { verse: 10, text: "And Jethro said, Blessed be the LORD, who hath delivered you out of the hand of the Egyptians, and out of the hand of Pharaoh, who hath delivered the people from under the hand of the Egyptians.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the covenant name of God, Yahweh" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh; title of Egypt's king" }] },
      { verse: 11, text: "Now I know that the LORD is greater than all gods: for in the thing wherein they dealt proudly he was above them.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the covenant name of God, Yahweh" }, { word: "gods", strongNumber: "H430", lemma: "'elohim", meaning: "gods; mighty ones" }] },
      { verse: 12, text: "And Jethro, Moses' father in law, took a burnt offering and sacrifices for God: and Aaron came, and all the elders of Israel, to eat bread with Moses' father in law before God.", highlightedWords: [{ word: "Aaron", strongNumber: "H175", lemma: "'Aharon", meaning: "Aaron; brother of Moses, Israel's first high priest" }, { word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God; mighty one" }] },
      { verse: 13, text: "And it came to pass on the morrow, that Moses sat to judge the people: and the people stood by Moses from the morning unto the evening.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out (Israel's leader)" }, { word: "judge", strongNumber: "H8199", lemma: "shaphat", meaning: "to judge, govern, decide" }] },
      { verse: 14, text: "And when Moses' father in law saw all that he did to the people, he said, What is this thing that thou doest to the people? why sittest thou thyself alone, and all the people stand by thee from morning unto even?", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "'am", meaning: "people, nation" }, { word: "even", strongNumber: "H6153", lemma: "'ereb", meaning: "evening, sunset" }] },
      { verse: 15, text: "And Moses said unto his father in law, Because the people come unto me to enquire of God:", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out (Israel's leader)" }, { word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God; mighty one" }] },
      { verse: 16, text: "When they have a matter, they come unto me; and I judge between one and another, and I do make them know the statutes of God, and his laws.", highlightedWords: [{ word: "statutes", strongNumber: "H2706", lemma: "choq", meaning: "statute, prescribed decree" }, { word: "laws", strongNumber: "H8451", lemma: "torah", meaning: "law, instruction, teaching" }] },
      { verse: 17, text: "And Moses' father in law said unto him, The thing that thou doest is not good.", highlightedWords: [{ word: "said", strongNumber: "H559", lemma: "'amar", meaning: "to say, declare" }, { word: "good", strongNumber: "H2896", lemma: "tov", meaning: "good, pleasant, right" }] },
      { verse: 18, text: "Thou wilt surely wear away, both thou, and this people that is with thee: for this thing is too heavy for thee; thou art not able to perform it thyself alone.", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "'am", meaning: "people, nation" }, { word: "heavy", strongNumber: "H3515", lemma: "kaved", meaning: "heavy, weighty, burdensome" }] },
      { verse: 19, text: "Hearken now unto my voice, I will give thee counsel, and God shall be with thee: Be thou for the people to God-ward, that thou mayest bring the causes unto God:", highlightedWords: [{ word: "voice", strongNumber: "H6963", lemma: "qol", meaning: "voice, sound" }, { word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God; mighty one" }] },
      { verse: 20, text: "And thou shalt teach them ordinances and laws, and shalt shew them the way wherein they must walk, and the work that they must do.", highlightedWords: [{ word: "laws", strongNumber: "H8451", lemma: "torah", meaning: "law, instruction, teaching" }, { word: "way", strongNumber: "H1870", lemma: "derek", meaning: "way, road, manner of life" }] },
      { verse: 21, text: "Moreover thou shalt provide out of all the people able men, such as fear God, men of truth, hating covetousness; and place such over them, to be rulers of thousands, and rulers of hundreds, rulers of fifties, and rulers of tens:", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God; mighty one" }, { word: "rulers", strongNumber: "H8269", lemma: "sar", meaning: "chief, prince, ruler, official" }] },
      { verse: 22, text: "And let them judge the people at all seasons: and it shall be, that every great matter they shall bring unto thee, but every small matter they shall judge: so shall it be easier for thyself, and they shall bear the burden with thee.", highlightedWords: [{ word: "judge", strongNumber: "H8199", lemma: "shaphat", meaning: "to judge, govern, decide" }, { word: "burden", strongNumber: "H4853", lemma: "massa'", meaning: "burden, load, duty" }] },
      { verse: 23, text: "If thou shalt do this thing, and God command thee so, then thou shalt be able to endure, and all this people shall also go to their place in peace.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God; mighty one" }, { word: "peace", strongNumber: "H7965", lemma: "shalom", meaning: "peace, wholeness, welfare" }] },
      { verse: 24, text: "So Moses hearkened to the voice of his father in law, and did all that he had said.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out (Israel's leader)" }, { word: "voice", strongNumber: "H6963", lemma: "qol", meaning: "voice, sound" }] },
      { verse: 25, text: "And Moses chose able men out of all Israel, and made them heads over the people, rulers of thousands, rulers of hundreds, rulers of fifties, and rulers of tens.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; God strives" }, { word: "rulers", strongNumber: "H8269", lemma: "sar", meaning: "chief, prince, ruler, official" }] },
      { verse: 26, text: "And they judged the people at all seasons: the hard causes they brought unto Moses, but every small matter they judged themselves.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out (Israel's leader)" }, { word: "judged", strongNumber: "H8199", lemma: "shaphat", meaning: "to judge, govern, decide" }] },
      { verse: 27, text: "And Moses let his father in law depart; and he went his way into his own land.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out (Israel's leader)" }, { word: "land", strongNumber: "H776", lemma: "'erets", meaning: "land, earth, territory" }] }
    ]
  }
}
