import { ChapterData } from "@/lib/bible-data"

export const exodusChapter6: ChapterData = {
  "Exodus-6": {
    book: "Exodus",
    chapter: 6,
    twoWordSummary: "Covenant Assurance",
    themeSummary: "God reaffirms His covenant to Moses, promises deliverance with mighty power, and the lineage of Moses and Aaron is recorded.",
    sentenceDescription: "God reaffirms His covenant to Moses, promises deliverance with mighty power, and the lineage of Moses and Aaron is recorded.",
    themeWords: [
      { word: "LORD", strongNumber: "H3068", language: "Hebrew", lemma: "YHWH", meaning: "The covenant name of God; the LORD" },
      { word: "covenant", strongNumber: "H1285", language: "Hebrew", lemma: "berith", meaning: "A binding agreement or pledge" }
    ],
    verses: [
      { verse: 1, text: "Then the LORD said unto Moses, Now shalt thou see what I will do to Pharaoh: for with a strong hand shall he let them go, and with a strong hand shall he drive them out of his land.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "The covenant name of God; the LORD" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Parʿoh", meaning: "Title of the Egyptian king" }] },
      { verse: 2, text: "And God spake unto Moses, and said unto him, I am the LORD:", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; mighty one" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "The covenant name of God; the LORD" }] },
      { verse: 3, text: "And I appeared unto Abraham, unto Isaac, and unto Jacob, by the name of God Almighty, but by my name JEHOVAH was I not known to them.", highlightedWords: [{ word: "Almighty", strongNumber: "H7706", lemma: "Shaddai", meaning: "Almighty; all-powerful One" }, { word: "JEHOVAH", strongNumber: "H3068", lemma: "YHWH", meaning: "The personal name of Israel's God" }] },
      { verse: 4, text: "And I have also established my covenant with them, to give them the land of Canaan, the land of their pilgrimage, wherein they were strangers.", highlightedWords: [{ word: "covenant", strongNumber: "H1285", lemma: "berith", meaning: "A binding agreement or pledge" }, { word: "land", strongNumber: "H776", lemma: "ʾerets", meaning: "Land; earth; territory" }] },
      { verse: 5, text: "And I have also heard the groaning of the children of Israel, whom the Egyptians keep in bondage; and I have remembered my covenant.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisraʾel", meaning: "Israel; the people/nation descended from Jacob" }, { word: "covenant", strongNumber: "H1285", lemma: "berith", meaning: "A binding agreement or pledge" }] },
      { verse: 6, text: "Wherefore say unto the children of Israel, I am the LORD, and I will bring you out from under the burdens of the Egyptians, and I will rid you out of their bondage, and I will redeem you with a stretched out arm, and with great judgments:", highlightedWords: [{ word: "redeem", strongNumber: "H1350", lemma: "gaʾal", meaning: "To redeem; act as kinsman-redeemer" }, { word: "arm", strongNumber: "H2220", lemma: "zeroaʿ", meaning: "Arm; symbol of strength and power" }] },
      { verse: 7, text: "And I will take you to me for a people, and I will be to you a God: and ye shall know that I am the LORD your God, which bringeth you out from under the burdens of the Egyptians.", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "ʿam", meaning: "People; nation; populace" }, { word: "know", strongNumber: "H3045", lemma: "yadaʿ", meaning: "To know; recognize; acknowledge" }] },
      { verse: 8, text: "And I will bring you in unto the land, concerning the which I did swear to give it to Abraham, to Isaac, and to Jacob; and I will give it you for an heritage: I am the LORD.", highlightedWords: [{ word: "land", strongNumber: "H776", lemma: "ʾerets", meaning: "Land; earth; territory" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "The covenant name of God; the LORD" }] },
      { verse: 9, text: "And Moses spake so unto the children of Israel: but they hearkened not unto Moses for anguish of spirit, and for cruel bondage.", highlightedWords: [{ word: "hearkened", strongNumber: "H8085", lemma: "shamaʿ", meaning: "To hear; listen; obey" }, { word: "spirit", strongNumber: "H7307", lemma: "ruach", meaning: "Spirit; breath; wind; inner being" }] },
      { verse: 10, text: "And the LORD spake unto Moses, saying,", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "The covenant name of God; the LORD" }, { word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses; drawn out" }] },
      { verse: 11, text: "Go in, speak unto Pharaoh king of Egypt, that he let the children of Israel go out of his land.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Parʿoh", meaning: "Title of the Egyptian king" }, { word: "king", strongNumber: "H4428", lemma: "melek", meaning: "King; ruler" }] },
      { verse: 12, text: "And Moses spake before the LORD, saying, Behold, the children of Israel have not hearkened unto me; how then shall Pharaoh hear me, who am of uncircumcised lips?", highlightedWords: [{ word: "uncircumcised", strongNumber: "H6189", lemma: "ʿarel", meaning: "Uncircumcised; having a foreskin; figuratively unfit" }, { word: "hear", strongNumber: "H8085", lemma: "shamaʿ", meaning: "To hear; listen; heed" }] },
      { verse: 13, text: "And the LORD spake unto Moses and unto Aaron, and gave them a charge unto the children of Israel, and unto Pharaoh king of Egypt, to bring the children of Israel out of the land of Egypt.", highlightedWords: [{ word: "Aaron", strongNumber: "H175", lemma: "Aharon", meaning: "Aaron; brother of Moses" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Parʿoh", meaning: "Title of the Egyptian king" }] },
      { verse: 14, text: "These be the heads of their fathers' houses: The sons of Reuben the firstborn of Israel; Hanoch, and Pallu, Hezron, and Carmi: these be the families of Reuben.", highlightedWords: [{ word: "heads", strongNumber: "H7218", lemma: "roʾsh", meaning: "Head; chief; leader" }, { word: "families", strongNumber: "H4940", lemma: "mishpachah", meaning: "Family; clan; extended family" }] },
      { verse: 15, text: "And the sons of Simeon; Jemuel, and Jamin, and Ohad, and Jachin, and Zohar, and Shaul the son of a Canaanitish woman: these are the families of Simeon.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "Son; descendant; member" }, { word: "families", strongNumber: "H4940", lemma: "mishpachah", meaning: "Family; clan; extended family" }] },
      { verse: 16, text: "And these are the names of the sons of Levi according to their generations; Gershon, and Kohath, and Merari: and the years of the life of Levi were an hundred thirty and seven years.", highlightedWords: [{ word: "Levi", strongNumber: "H3878", lemma: "Levi", meaning: "Levi; joined; son of Jacob" }, { word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "Year; a cycle of time" }] },
      { verse: 17, text: "The sons of Gershon; Libni, and Shimi, according to their families.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "Son; descendant; member" }, { word: "families", strongNumber: "H4940", lemma: "mishpachah", meaning: "Family; clan; extended family" }] },
      { verse: 18, text: "And the sons of Kohath; Amram, and Izhar, and Hebron, and Uzziel: and the years of the life of Kohath were an hundred thirty and three years.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "Son; descendant; member" }, { word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "Year; a cycle of time" }] },
      { verse: 19, text: "And the sons of Merari; Mahali and Mushi: these are the families of Levi according to their generations.", highlightedWords: [{ word: "families", strongNumber: "H4940", lemma: "mishpachah", meaning: "Family; clan; extended family" }, { word: "Levi", strongNumber: "H3878", lemma: "Levi", meaning: "Levi; joined; son of Jacob" }] },
      { verse: 20, text: "And Amram took him Jochebed his father's sister to wife; and she bare him Aaron and Moses: and the years of the life of Amram were an hundred and thirty and seven years.", highlightedWords: [{ word: "took", strongNumber: "H3947", lemma: "laqach", meaning: "To take; grasp; receive" }, { word: "wife", strongNumber: "H802", lemma: "ishshah", meaning: "Woman; wife" }] },
      { verse: 21, text: "And the sons of Izhar; Korah, and Nepheg, and Zichri.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "Son; descendant; member" }, { word: "Korah", strongNumber: "H7141", lemma: "Qorach", meaning: "Korah; a Levite" }] },
      { verse: 22, text: "And the sons of Uzziel; Mishael, and Elzaphan, and Zithri.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "Son; descendant; member" }, { word: "Uzziel", strongNumber: "H5816", lemma: "ʿUzziel", meaning: "Uzziel; God is my strength" }] },
      { verse: 23, text: "And Aaron took him Elisheba, daughter of Amminadab, sister of Naashon, to wife; and she bare him Nadab, and Abihu, Eleazar, and Ithamar.", highlightedWords: [{ word: "Aaron", strongNumber: "H175", lemma: "Aharon", meaning: "Aaron; brother of Moses" }, { word: "wife", strongNumber: "H802", lemma: "ishshah", meaning: "Woman; wife" }] },
      { verse: 24, text: "And the sons of Korah; Assir, and Elkanah, and Abiasaph: these are the families of the Korhites.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "Son; descendant; member" }, { word: "families", strongNumber: "H4940", lemma: "mishpachah", meaning: "Family; clan; extended family" }] },
      { verse: 25, text: "And Eleazar Aaron's son took him one of the daughters of Putiel to wife; and she bare him Phinehas: these are the heads of the fathers of the Levites according to their families.", highlightedWords: [{ word: "Levites", strongNumber: "H3881", lemma: "Leviyyiy", meaning: "Levites; descendants of Levi" }, { word: "wife", strongNumber: "H802", lemma: "ishshah", meaning: "Woman; wife" }] },
      { verse: 26, text: "These are that Aaron and Moses, to whom the LORD said, Bring out the children of Israel from the land of Egypt according to their armies.", highlightedWords: [{ word: "armies", strongNumber: "H6635", lemma: "tsaba", meaning: "Host; army; organized company" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "The covenant name of God; the LORD" }] },
      { verse: 27, text: "These are they which spake to Pharaoh king of Egypt, to bring out the children of Israel from Egypt: these are that Moses and Aaron.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Parʿoh", meaning: "Title of the Egyptian king" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt; the land of the Nile" }] },
      { verse: 28, text: "And it came to pass on the day when the LORD spake unto Moses in the land of Egypt,", highlightedWords: [{ word: "day", strongNumber: "H3117", lemma: "yom", meaning: "Day; time; period" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt; the land of the Nile" }] },
      { verse: 29, text: "That the LORD spake unto Moses, saying, I am the LORD: speak thou unto Pharaoh king of Egypt all that I say unto thee.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "The covenant name of God; the LORD" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Parʿoh", meaning: "Title of the Egyptian king" }] },
      { verse: 30, text: "And Moses said before the LORD, Behold, I am of uncircumcised lips, and how shall Pharaoh hearken unto me?", highlightedWords: [{ word: "uncircumcised", strongNumber: "H6189", lemma: "ʿarel", meaning: "Uncircumcised; having a foreskin; figuratively unfit" }, { word: "hearken", strongNumber: "H8085", lemma: "shamaʿ", meaning: "To hear; listen; obey" }] }
    ]
  }
}
