import { ChapterData } from "@/lib/bible-data"

export const exodusChapter9: ChapterData = {
  "Exodus-9": {
    book: "Exodus",
    chapter: 9,
    twoWordSummary: "Devastating Plagues",
    themeSummary: "God intensifies judgment on Egypt through murrain, boils, and a devastating hailstorm, while Pharaoh's hardened heart resists repentance.",
    sentenceDescription: "God intensifies judgment on Egypt through murrain, boils, and a devastating hailstorm, while Pharaoh's hardened heart resists repentance.",
    themeWords: [
      { word: "hail", strongNumber: "H1259", language: "Hebrew", lemma: "barad", meaning: "hail" },
      { word: "pestilence", strongNumber: "H1698", language: "Hebrew", lemma: "deber", meaning: "pestilence, plague" }
    ],
    verses: [
      { verse: 1, text: "Then the LORD said unto Moses, Go in unto Pharaoh, and tell him, Thus saith the LORD God of the Hebrews, Let my people go, that they may serve me.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh, the Egyptian king" }] },
      { verse: 2, text: "For if thou refuse to let them go, and wilt hold them still,", highlightedWords: [{ word: "refuse", strongNumber: "H3985", lemma: "ma'en", meaning: "to refuse" }, { word: "go", strongNumber: "H7971", lemma: "shalach", meaning: "to send, send away" }] },
      { verse: 3, text: "Behold, the hand of the LORD is upon thy cattle which is in the field, upon the horses, upon the asses, upon the camels, upon the oxen, and upon the sheep: there shall be a very grievous murrain.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "murrain", strongNumber: "H1698", lemma: "deber", meaning: "pestilence, plague on livestock" }] },
      { verse: 4, text: "And the LORD shall sever between the cattle of Israel and the cattle of Egypt: and there shall nothing die of all that is the children's of Israel.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 5, text: "And the LORD appointed a set time, saying, To morrow the LORD shall do this thing in the land.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "land", strongNumber: "H0776", lemma: "'erets", meaning: "land, earth" }] },
      { verse: 6, text: "And the LORD did that thing on the morrow, and all the cattle of Egypt died: but of the cattle of the children of Israel died not one.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 7, text: "And Pharaoh sent, and, behold, there was not one of the cattle of the Israelites dead. And the heart of Pharaoh was hardened, and he did not let the people go.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh, the Egyptian king" }, { word: "heart", strongNumber: "H3820", lemma: "leb", meaning: "heart, inner person" }] },
      { verse: 8, text: "And the LORD said unto Moses and unto Aaron, Take to you handfuls of ashes of the furnace, and let Moses sprinkle it toward the heaven in the sight of Pharaoh.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }] },
      { verse: 9, text: "And it shall become small dust in all the land of Egypt, and shall be a boil breaking forth with blains upon man, and upon beast, throughout all the land of Egypt.", highlightedWords: [{ word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }, { word: "boil", strongNumber: "H7822", lemma: "shechin", meaning: "inflamed spot, boil" }] },
      { verse: 10, text: "And they took ashes of the furnace, and stood before Pharaoh; and Moses sprinkled it up toward heaven; and it became a boil breaking forth with blains upon man, and upon beast.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh, the Egyptian king" }, { word: "boil", strongNumber: "H7822", lemma: "shechin", meaning: "inflamed spot, boil" }] },
      { verse: 11, text: "And the magicians could not stand before Moses because of the boils; for the boil was upon the magicians, and upon all the Egyptians.", highlightedWords: [{ word: "magicians", strongNumber: "H2748", lemma: "chartom", meaning: "magician, enchanter" }, { word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses" }] },
      { verse: 12, text: "And the LORD hardened the heart of Pharaoh, and he hearkened not unto them; as the LORD had spoken unto Moses.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh, the Egyptian king" }] },
      { verse: 13, text: "And the LORD said unto Moses, Rise up early in the morning, and stand before Pharaoh, and say unto him, Thus saith the LORD God of the Hebrews, Let my people go, that they may serve me.", highlightedWords: [{ word: "Hebrews", strongNumber: "H5680", lemma: "'Ivri", meaning: "Hebrew" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }] },
      { verse: 14, text: "For I will at this time send all my plagues upon thine heart, and upon thy servants, and upon thy people; that thou mayest know that there is none like me in all the earth.", highlightedWords: [{ word: "earth", strongNumber: "H0776", lemma: "'erets", meaning: "earth, land" }, { word: "servants", strongNumber: "H5650", lemma: "'ebed", meaning: "servant" }] },
      { verse: 15, text: "For now I will stretch out my hand, that I may smite thee and thy people with pestilence; and thou shalt be cut off from the earth.", highlightedWords: [{ word: "hand", strongNumber: "H3027", lemma: "yad", meaning: "hand" }, { word: "pestilence", strongNumber: "H1698", lemma: "deber", meaning: "pestilence, plague" }] },
      { verse: 16, text: "And in very deed for this cause have I raised thee up, for to shew in thee my power; and that my name may be declared throughout all the earth.", highlightedWords: [{ word: "name", strongNumber: "H8034", lemma: "shem", meaning: "name, reputation" }, { word: "earth", strongNumber: "H0776", lemma: "'erets", meaning: "earth, land" }] },
      { verse: 17, text: "As yet exaltest thou thyself against my people, that thou wilt not let them go?", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "'am", meaning: "people, nation" }, { word: "go", strongNumber: "H7971", lemma: "shalach", meaning: "to send, send away" }] },
      { verse: 18, text: "Behold, to morrow about this time I will cause it to rain a very grievous hail, such as hath not been in Egypt since the foundation thereof even until now.", highlightedWords: [{ word: "hail", strongNumber: "H1259", lemma: "barad", meaning: "hail" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 19, text: "Send therefore now, and gather thy cattle, and all that thou hast in the field; for upon every man and beast which shall be found in the field, and shall not be brought home, the hail shall come down upon them, and they shall die.", highlightedWords: [{ word: "field", strongNumber: "H7704", lemma: "sadeh", meaning: "field, open country" }, { word: "hail", strongNumber: "H1259", lemma: "barad", meaning: "hail" }] },
      { verse: 20, text: "He that feared the word of the LORD among the servants of Pharaoh made his servants and his cattle flee into the houses:", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh, the Egyptian king" }] },
      { verse: 21, text: "And he that regarded not the word of the LORD left his servants and his cattle in the field.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "servants", strongNumber: "H5650", lemma: "'ebed", meaning: "servant" }] },
      { verse: 22, text: "And the LORD said unto Moses, Stretch forth thine hand toward heaven, that there may be hail in all the land of Egypt, upon man, and upon beast, and upon every herb of the field, throughout the land of Egypt.", highlightedWords: [{ word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }] },
      { verse: 23, text: "And Moses stretched forth his rod toward heaven: and the LORD sent thunder and hail, and the fire ran along upon the ground; and the LORD rained hail upon the land of Egypt.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "hail", strongNumber: "H1259", lemma: "barad", meaning: "hail" }] },
      { verse: 24, text: "So there was hail, and fire mingled with the hail, very grievous, such as there was none like it in all the land of Egypt since it became a nation.", highlightedWords: [{ word: "hail", strongNumber: "H1259", lemma: "barad", meaning: "hail" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 25, text: "And the hail smote throughout all the land of Egypt all that was in the field, both man and beast; and the hail smote every herb of the field, and brake every tree of the field.", highlightedWords: [{ word: "hail", strongNumber: "H1259", lemma: "barad", meaning: "hail" }, { word: "field", strongNumber: "H7704", lemma: "sadeh", meaning: "field, open country" }] },
      { verse: 26, text: "Only in the land of Goshen, where the children of Israel were, was there no hail.", highlightedWords: [{ word: "Goshen", strongNumber: "H1657", lemma: "Goshen", meaning: "region in Egypt where Israel lived" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel" }] },
      { verse: 27, text: "And Pharaoh sent, and called for Moses and Aaron, and said unto them, I have sinned this time: the LORD is righteous, and I and my people are wicked.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh, the Egyptian king" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }] },
      { verse: 28, text: "Intreat the LORD (for it is enough) that there be no more mighty thunderings and hail; and I will let you go, and ye shall stay no longer.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "hail", strongNumber: "H1259", lemma: "barad", meaning: "hail" }] },
      { verse: 29, text: "And Moses said unto him, As soon as I am gone out of the city, I will spread abroad my hands unto the LORD; and the thunder shall cease, neither shall there be any more hail; that thou mayest know how that the earth is the LORD's.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }] },
      { verse: 30, text: "But as for thee and thy servants, I know that ye will not yet fear the LORD God.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }, { word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God" }] },
      { verse: 31, text: "And the flax and the barley was smitten: for the barley was in the ear, and the flax was bolled.", highlightedWords: [{ word: "barley", strongNumber: "H8184", lemma: "se'orah", meaning: "barley" }, { word: "flax", strongNumber: "H6594", lemma: "pishtah", meaning: "flax" }] },
      { verse: 32, text: "But the wheat and the rie were not smitten: for they were not grown up.", highlightedWords: [{ word: "wheat", strongNumber: "H2406", lemma: "chittah", meaning: "wheat" }, { word: "rie", strongNumber: "H3698", lemma: "kussemeth", meaning: "spelt (rye)" }] },
      { verse: 33, text: "And Moses went out of the city from Pharaoh, and spread abroad his hands unto the LORD: and the thunders and hail ceased, and the rain was not poured upon the earth.", highlightedWords: [{ word: "Moses", strongNumber: "H4872", lemma: "Mosheh", meaning: "Moses" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }] },
      { verse: 34, text: "And when Pharaoh saw that the rain and the hail and the thunders were ceased, he sinned yet more, and hardened his heart, he and his servants.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh, the Egyptian king" }, { word: "heart", strongNumber: "H3820", lemma: "leb", meaning: "heart, inner person" }] },
      { verse: 35, text: "And the heart of Pharaoh was hardened, neither would he let the children of Israel go; as the LORD had spoken by Moses.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh, the Egyptian king" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the divine name, the LORD" }] }
    ]
  }
}
