import { ChapterData } from "@/lib/bible-data"

export const genesisChapter48: ChapterData = {
  "Genesis-48": {
    book: "Genesis",
    chapter: 48,
    twoWordSummary: "Crossed Blessing",
    themeSummary: "Israel (Jacob) adopts Joseph's sons and, crossing his hands, blesses Ephraim over Manasseh, assuring their future inheritance.",
    sentenceDescription: "Israel (Jacob) adopts Joseph's sons and, crossing his hands, blesses Ephraim over Manasseh, assuring their future inheritance.",
    themeWords: [
      { word: "bless", strongNumber: "H1288", language: "Hebrew", lemma: "barak", meaning: "to bless, kneel, invoke divine favor" },
      { word: "Ephraim", strongNumber: "H669", language: "Hebrew", lemma: "Ephrayim", meaning: "double fruitfulness" }
    ],
    verses: [
      { verse: 1, text: "And it came to pass after these things, that one told Joseph, Behold, thy father is sick: and he took with him his two sons, Manasseh and Ephraim.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "Manasseh", strongNumber: "H4519", lemma: "Menashsheh", meaning: "causing to forget" }] },
      { verse: 2, text: "And one told Jacob, and said, Behold, thy son Joseph cometh unto thee: and Israel strengthened himself, and sat upon the bed.", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqob", meaning: "supplanter; heel-catcher" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives; he struggles with God" }] },
      { verse: 3, text: "And Jacob said unto Joseph, God Almighty appeared unto me at Luz in the land of Canaan, and blessed me,", highlightedWords: [{ word: "Luz", strongNumber: "H3870", lemma: "Luz", meaning: "almond tree; a place name" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan; lowland" }] },
      { verse: 4, text: "And said unto me, Behold, I will make thee fruitful, and multiply thee, and I will make of thee a multitude of people; and will give this land to thy seed after thee for an everlasting possession.", highlightedWords: [{ word: "land", strongNumber: "H776", lemma: "erets", meaning: "land, earth, territory" }, { word: "seed", strongNumber: "H2233", lemma: "zera", meaning: "seed, offspring, descendants" }] },
      { verse: 5, text: "And now thy two sons, Ephraim and Manasseh, which were born unto thee in the land of Egypt before I came unto thee into Egypt, are mine; as Reuben and Simeon, they shall be mine.", highlightedWords: [{ word: "Ephraim", strongNumber: "H669", lemma: "Ephrayim", meaning: "double fruitfulness" }, { word: "Manasseh", strongNumber: "H4519", lemma: "Menashsheh", meaning: "causing to forget" }] },
      { verse: 6, text: "And thy issue, which thou begettest after them, shall be thine, and shall be called after the name of their brethren in their inheritance.", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brother, kinsman" }, { word: "inheritance", strongNumber: "H5159", lemma: "nachalah", meaning: "inheritance, possession, heritage" }] },
      { verse: 7, text: "And as for me, when I came from Padan, Rachel died by me in the land of Canaan in the way, when yet there was but a little way to come unto Ephrath: and I buried her there in the way of Ephrath; the same is Bethlehem.", highlightedWords: [{ word: "Rachel", strongNumber: "H7354", lemma: "Rahel", meaning: "ewe; a female sheep" }, { word: "Bethlehem", strongNumber: "H1035", lemma: "Beth Lechem", meaning: "house of bread" }] },
      { verse: 8, text: "And Israel beheld Joseph's sons, and said, Who are these?", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives; he struggles with God" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son, descendant" }] },
      { verse: 9, text: "And Joseph said unto his father, They are my sons, whom God hath given me in this place: and he said, Bring them, I pray thee, unto me, and I will bless them.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; mighty one" }, { word: "bless", strongNumber: "H1288", lemma: "barak", meaning: "to bless, invoke divine favor" }] },
      { verse: 10, text: "Now the eyes of Israel were dim for age, so that he could not see. And he brought them near unto him; and he kissed them, and embraced them.", highlightedWords: [{ word: "eyes", strongNumber: "H5869", lemma: "ayin", meaning: "eye" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives; he struggles with God" }] },
      { verse: 11, text: "And Israel said unto Joseph, I had not thought to see thy face: and, lo, God hath shewed me also thy seed.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; mighty one" }, { word: "seed", strongNumber: "H2233", lemma: "zera", meaning: "seed, offspring, descendants" }] },
      { verse: 12, text: "And Joseph brought them out from between his knees, and he bowed himself with his face to the earth.", highlightedWords: [{ word: "bowed", strongNumber: "H7812", lemma: "shachah", meaning: "to bow down, prostrate oneself" }, { word: "earth", strongNumber: "H776", lemma: "erets", meaning: "land, earth" }] },
      { verse: 13, text: "And Joseph took them both, Ephraim in his right hand toward Israel's left hand, and Manasseh in his left hand toward Israel's right hand, and brought them near unto him.", highlightedWords: [{ word: "Ephraim", strongNumber: "H669", lemma: "Ephrayim", meaning: "double fruitfulness" }, { word: "Manasseh", strongNumber: "H4519", lemma: "Menashsheh", meaning: "causing to forget" }] },
      { verse: 14, text: "And Israel stretched out his right hand, and laid it upon Ephraim's head, who was the younger, and his left hand upon Manasseh's head, guiding his hands wittingly; for Manasseh was the firstborn.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives; he struggles with God" }, { word: "firstborn", strongNumber: "H1060", lemma: "bekor", meaning: "firstborn" }] },
      { verse: 15, text: "And he blessed Joseph, and said, God, before whom my fathers Abraham and Isaac did walk, the God which fed me all my life long unto this day,", highlightedWords: [{ word: "Abraham", strongNumber: "H85", lemma: "Avraham", meaning: "father of a multitude" }, { word: "Isaac", strongNumber: "H3327", lemma: "Yitschaq", meaning: "he laughs" }] },
      { verse: 16, text: "The Angel which redeemed me from all evil, bless the lads; and let my name be named on them, and the name of my fathers Abraham and Isaac; and let them grow into a multitude in the midst of the earth.", highlightedWords: [{ word: "Angel", strongNumber: "H4397", lemma: "mal'ak", meaning: "messenger, angel" }, { word: "redeemed", strongNumber: "H1350", lemma: "gaal", meaning: "to redeem, act as kinsman-redeemer" }] },
      { verse: 17, text: "And when Joseph saw that his father laid his right hand upon the head of Ephraim, it displeased him: and he held up his father's hand, to remove it from Ephraim's head unto Manasseh's head.", highlightedWords: [{ word: "Ephraim", strongNumber: "H669", lemma: "Ephrayim", meaning: "double fruitfulness" }, { word: "Manasseh", strongNumber: "H4519", lemma: "Menashsheh", meaning: "causing to forget" }] },
      { verse: 18, text: "And Joseph said unto his father, Not so, my father: for this is the firstborn; put thy right hand upon his head.", highlightedWords: [{ word: "firstborn", strongNumber: "H1060", lemma: "bekor", meaning: "firstborn" }, { word: "hand", strongNumber: "H3027", lemma: "yad", meaning: "hand, power" }] },
      { verse: 19, text: "And his father refused, and said, I know it, my son, I know it: he also shall become a people, and he also shall be great: but truly his younger brother shall be greater than he, and his seed shall become a multitude of nations.", highlightedWords: [{ word: "seed", strongNumber: "H2233", lemma: "zera", meaning: "seed, offspring, descendants" }, { word: "nations", strongNumber: "H1471", lemma: "goy", meaning: "nation, people" }] },
      { verse: 20, text: "And he blessed them that day, saying, In thee shall Israel bless, saying, God make thee as Ephraim and as Manasseh: and he set Ephraim before Manasseh.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives; he struggles with God" }, { word: "bless", strongNumber: "H1288", lemma: "barak", meaning: "to bless, invoke divine favor" }] },
      { verse: 21, text: "And Israel said unto Joseph, Behold, I die: but God shall be with you, and bring you again unto the land of your fathers.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; mighty one" }, { word: "land", strongNumber: "H776", lemma: "erets", meaning: "land, earth, territory" }] },
      { verse: 22, text: "Moreover I have given to thee one portion above thy brethren, which I took out of the hand of the Amorite with my sword and with my bow.", highlightedWords: [{ word: "Amorite", strongNumber: "H567", lemma: "Emori", meaning: "Amorite; a Canaanite people" }, { word: "sword", strongNumber: "H2719", lemma: "chereb", meaning: "sword, dagger" }] }
    ]
  }
}
