import { ChapterData } from "@/lib/bible-data"

export const genesisChapter3: ChapterData = {
  "Genesis-3": {
    book: "Genesis",
    chapter: 3,
    twoWordSummary: "Humanity Falls",
    themeSummary: "The serpent deceives Eve, Adam and Eve eat from the forbidden tree, sin enters the world, God pronounces judgment, and humanity is expelled from Eden.",
    sentenceDescription: "The serpent's deception leads to humanity's disobedience, bringing sin, shame, and separation from God, yet within judgment lies the promise of future redemption through the seed of the woman.",
    themeWords: [
      { word: "serpent", strongNumber: "H5175", lemma: "nachash", meaning: "serpent; snake; deceiver" },
      { word: "enmity", strongNumber: "H342", lemma: "ebah", meaning: "hostility; hatred" }
    ],
    verses: [
      { verseNumber: 1, text: "Now the serpent was more subtil than any beast of the field which the LORD God had made. And he said unto the woman, Yea, hath God said, Ye shall not eat of every tree of the garden?", highlightedWords: [{ word: "serpent", strongNumber: "H5175", lemma: "nachash", meaning: "serpent; snake; deceiver" }, { word: "subtil", strongNumber: "H6175", lemma: "arum", meaning: "crafty; shrewd; cunning" }] },
      { verseNumber: 2, text: "And the woman said unto the serpent, We may eat of the fruit of the trees of the garden:", highlightedWords: [{ word: "fruit", strongNumber: "H6529", lemma: "peri", meaning: "fruit; produce of a tree" }, { word: "garden", strongNumber: "H1588", lemma: "gan", meaning: "garden; enclosed place" }] },
      { verseNumber: 3, text: "But of the fruit of the tree which is in the midst of the garden, God hath said, Ye shall not eat of it, neither shall ye touch it, lest ye die.", highlightedWords: [{ word: "touch", strongNumber: "H5060", lemma: "naga", meaning: "to touch; strike; reach" }, { word: "die", strongNumber: "H4191", lemma: "muth", meaning: "to die; suffer death" }] },
      { verseNumber: 4, text: "And the serpent said unto the woman, Ye shall not surely die:", highlightedWords: [{ word: "surely", strongNumber: "H4191", lemma: "muth", meaning: "emphatic certainty of death" }, { word: "serpent", strongNumber: "H5175", lemma: "nachash", meaning: "serpent; deceiver" }] },
      { verseNumber: 5, text: "For God doth know that in the day ye eat thereof, then your eyes shall be opened, and ye shall be as gods, knowing good and evil.", highlightedWords: [{ word: "opened", strongNumber: "H6491", lemma: "paqach", meaning: "to open; make aware" }, { word: "knowing", strongNumber: "H3045", lemma: "yada", meaning: "to know; understand" }] },
      { verseNumber: 6, text: "And when the woman saw that the tree was good for food, and that it was pleasant to the eyes, and a tree to be desired to make one wise, she took of the fruit thereof, and did eat, and gave also unto her husband with her; and he did eat.", highlightedWords: [{ word: "pleasant", strongNumber: "H8378", lemma: "taavah", meaning: "desire; longing" }, { word: "took", strongNumber: "H3947", lemma: "laqach", meaning: "to take; seize" }] },
      { verseNumber: 7, text: "And the eyes of them both were opened, and they knew that they were naked; and they sewed fig leaves together, and made themselves aprons.", highlightedWords: [{ word: "naked", strongNumber: "H5903", lemma: "erom", meaning: "naked; bare" }, { word: "sewed", strongNumber: "H8609", lemma: "taphar", meaning: "to sew; stitch together" }] },
      { verseNumber: 8, text: "And they heard the voice of the LORD God walking in the garden in the cool of the day: and Adam and his wife hid themselves from the presence of the LORD God amongst the trees of the garden.", highlightedWords: [{ word: "voice", strongNumber: "H6963", lemma: "qol", meaning: "voice; sound" }, { word: "hid", strongNumber: "H2244", lemma: "chaba", meaning: "to hide oneself" }] },
      { verseNumber: 9, text: "And the LORD God called unto Adam, and said unto him, Where art thou?", highlightedWords: [{ word: "called", strongNumber: "H7121", lemma: "qara", meaning: "to call; summon" }, { word: "Adam", strongNumber: "H120", lemma: "adam", meaning: "man; mankind" }] },
      { verseNumber: 10, text: "And he said, I heard thy voice in the garden, and I was afraid, because I was naked; and I hid myself.", highlightedWords: [{ word: "afraid", strongNumber: "H3372", lemma: "yare", meaning: "to fear; be afraid" }, { word: "naked", strongNumber: "H5903", lemma: "erom", meaning: "bare; uncovered" }] },
      { verseNumber: 11, text: "And he said, Who told thee that thou wast naked? Hast thou eaten of the tree, whereof I commanded thee that thou shouldest not eat?", highlightedWords: [{ word: "commanded", strongNumber: "H6680", lemma: "tsavah", meaning: "to command; charge" }, { word: "eaten", strongNumber: "H398", lemma: "akal", meaning: "to eat; consume" }] },
      { verseNumber: 12, text: "And the man said, The woman whom thou gavest to be with me, she gave me of the tree, and I did eat.", highlightedWords: [{ word: "gave", strongNumber: "H5414", lemma: "nathan", meaning: "to give; grant" }, { word: "woman", strongNumber: "H802", lemma: "ishshah", meaning: "woman; wife" }] },
      { verseNumber: 13, text: "And the LORD God said unto the woman, What is this that thou hast done? And the woman said, The serpent beguiled me, and I did eat.", highlightedWords: [{ word: "beguiled", strongNumber: "H5377", lemma: "nasha", meaning: "to deceive; lead astray" }, { word: "serpent", strongNumber: "H5175", lemma: "nachash", meaning: "serpent; deceiver" }] },
      { verseNumber: 14, text: "And the LORD God said unto the serpent, Because thou hast done this, thou art cursed above all cattle, and above every beast of the field; upon thy belly shalt thou go, and dust shalt thou eat all the days of thy life:", highlightedWords: [{ word: "cursed", strongNumber: "H779", lemma: "arar", meaning: "to curse; bind with misfortune" }, { word: "dust", strongNumber: "H6083", lemma: "aphar", meaning: "dust; dry earth" }] },
      { verseNumber: 15, text: "And I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel.", highlightedWords: [{ word: "enmity", strongNumber: "H342", lemma: "ebah", meaning: "hostility; hatred" }, { word: "seed", strongNumber: "H2233", lemma: "zera", meaning: "offspring; descendants" }] },
      { verseNumber: 16, text: "Unto the woman he said, I will greatly multiply thy sorrow and thy conception; in sorrow thou shalt bring forth children; and thy desire shall be to thy husband, and he shall rule over thee.", highlightedWords: [{ word: "sorrow", strongNumber: "H6093", lemma: "itsabon", meaning: "pain; sorrow" }, { word: "rule", strongNumber: "H4910", lemma: "mashal", meaning: "to rule; govern" }] },
      { verseNumber: 17, text: "And unto Adam he said, Because thou hast hearkened unto the voice of thy wife, and hast eaten of the tree, of which I commanded thee, saying, Thou shalt not eat of it: cursed is the ground for thy sake; in sorrow shalt thou eat of it all the days of thy life;", highlightedWords: [{ word: "cursed", strongNumber: "H779", lemma: "arar", meaning: "to curse; bring hardship" }, { word: "ground", strongNumber: "H127", lemma: "adamah", meaning: "ground; soil" }] },
      { verseNumber: 18, text: "Thorns also and thistles shall it bring forth to thee; and thou shalt eat the herb of the field;", highlightedWords: [{ word: "thorns", strongNumber: "H6975", lemma: "qots", meaning: "thorn; sharp plant" }, { word: "thistles", strongNumber: "H1863", lemma: "dardar", meaning: "thistle; prickly plant" }] },
      { verseNumber: 19, text: "In the sweat of thy face shalt thou eat bread, till thou return unto the ground; for out of it wast thou taken: for dust thou art, and unto dust shalt thou return.", highlightedWords: [{ word: "sweat", strongNumber: "H2188", lemma: "zeah", meaning: "sweat; perspiration" }, { word: "dust", strongNumber: "H6083", lemma: "aphar", meaning: "dust; earth particles" }] },
      { verseNumber: 20, text: "And Adam called his wife's name Eve; because she was the mother of all living.", highlightedWords: [{ word: "Eve", strongNumber: "H2332", lemma: "chavvah", meaning: "life; living one" }, { word: "mother", strongNumber: "H517", lemma: "em", meaning: "mother; female parent" }] },
      { verseNumber: 21, text: "Unto Adam also and to his wife did the LORD God make coats of skins, and clothed them.", highlightedWords: [{ word: "skins", strongNumber: "H5785", lemma: "or", meaning: "skin; hide of an animal" }, { word: "clothed", strongNumber: "H3847", lemma: "labash", meaning: "to clothe; dress" }] },
      { verseNumber: 22, text: "And the LORD God said, Behold, the man is become as one of us, to know good and evil: and now, lest he put forth his hand, and take also of the tree of life, and eat, and live for ever:", highlightedWords: [{ word: "know", strongNumber: "H3045", lemma: "yada", meaning: "to know; perceive" }, { word: "life", strongNumber: "H2416", lemma: "chay", meaning: "life; living existence" }] },
      { verseNumber: 23, text: "Therefore the LORD God sent him forth from the garden of Eden, to till the ground from whence he was taken.", highlightedWords: [{ word: "sent", strongNumber: "H7971", lemma: "shalach", meaning: "to send away; dispatch" }, { word: "Eden", strongNumber: "H5731", lemma: "eden", meaning: "delight; pleasure" }] },
      { verseNumber: 24, text: "So he drove out the man; and he placed at the east of the garden of Eden Cherubims, and a flaming sword which turned every way, to keep the way of the tree of life.", highlightedWords: [{ word: "drove", strongNumber: "H1644", lemma: "garash", meaning: "to drive out; expel" }, { word: "Cherubims", strongNumber: "H3742", lemma: "kerub", meaning: "cherub; angelic guardian" }] },
    ]
  }
}
