import { ChapterData } from "@/lib/bible-data"

export const genesisChapter50: ChapterData = {
  "Genesis-50": {
    book: "Genesis",
    chapter: 50,
    twoWordSummary: "Burial Forgiveness",
    themeSummary: "Joseph buries Jacob in Canaan, reassures and forgives his brothers, and dies in Egypt after prophesying Israel's future deliverance.",
    sentenceDescription: "Joseph buries Jacob in Canaan, reassures and forgives his brothers, and dies in Egypt after prophesying Israel's future deliverance.",
    themeWords: [
      { word: "Joseph", strongNumber: "H3130", language: "Hebrew", lemma: "Yosef", meaning: "he adds" },
      { word: "forgive", strongNumber: "H5375", language: "Hebrew", lemma: "nasa", meaning: "to lift, bear, forgive" }
    ],
    verses: [
      { verse: 1, text: "And Joseph fell upon his father's face, and wept upon him, and kissed him.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }, { word: "wept", strongNumber: "H1058", lemma: "bakah", meaning: "to weep, lament" }] },
      { verse: 2, text: "And Joseph commanded his servants the physicians to embalm his father: and the physicians embalmed Israel.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives; he who strives with God" }] },
      { verse: 3, text: "And forty days were fulfilled for him; for so are fulfilled the days of those which are embalmed: and the Egyptians mourned for him threescore and ten days.", highlightedWords: [{ word: "Egyptians", strongNumber: "H4713", lemma: "Mitsriy", meaning: "an Egyptian" }, { word: "days", strongNumber: "H3117", lemma: "yom", meaning: "day, time, period" }] },
      { verse: 4, text: "And when the days of his mourning were past, Joseph spake unto the house of Pharaoh, saying, If now I have found grace in your eyes, speak, I pray you, in the ears of Pharaoh, saying,", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh; great house" }] },
      { verse: 5, text: "My father made me swear, saying, Lo, I die: in my grave which I have digged for me in the land of Canaan, there shalt thou bury me. Now therefore let me go up, I pray thee, and bury my father, and I will come again.", highlightedWords: [{ word: "Canaan", strongNumber: "H3667", lemma: "Kĕna'an", meaning: "Canaan" }, { word: "bury", strongNumber: "H6912", lemma: "qabar", meaning: "to bury, inter" }] },
      { verse: 6, text: "And Pharaoh said, Go up, and bury thy father, according as he made thee swear.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh; great house" }, { word: "father", strongNumber: "H1", lemma: "'ab", meaning: "father, ancestor" }] },
      { verse: 7, text: "And Joseph went up to bury his father: and with him went up all the servants of Pharaoh, the elders of his house, and all the elders of the land of Egypt,", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 8, text: "And all the house of Joseph, and his brethren, and his father's house: only their little ones, and their flocks, and their herds, they left in the land of Goshen.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }, { word: "Goshen", strongNumber: "H1657", lemma: "Goshen", meaning: "Goshen (a region in Egypt)" }] },
      { verse: 9, text: "And there went up with him both chariots and horsemen: and it was a very great company.", highlightedWords: [{ word: "chariots", strongNumber: "H7393", lemma: "rekeb", meaning: "chariot, war-chariot" }, { word: "horsemen", strongNumber: "H6571", lemma: "parash", meaning: "horseman, cavalry" }] },
      { verse: 10, text: "And they came to the threshingfloor of Atad, which is beyond Jordan, and there they mourned with a great and very sore lamentation: and he made a mourning for his father seven days.", highlightedWords: [{ word: "threshingfloor", strongNumber: "H1637", lemma: "goren", meaning: "threshing-floor" }, { word: "Jordan", strongNumber: "H3383", lemma: "Yarden", meaning: "Jordan; the descender" }] },
      { verse: 11, text: "And when the inhabitants of the land, the Canaanites, saw the mourning in the floor of Atad, they said, This is a grievous mourning to the Egyptians: wherefore the name of it was called Abel-mizraim, which is beyond Jordan.", highlightedWords: [{ word: "Canaanites", strongNumber: "H3669", lemma: "Kĕna'aniy", meaning: "Canaanite" }, { word: "Egyptians", strongNumber: "H4713", lemma: "Mitsriy", meaning: "an Egyptian" }] },
      { verse: 12, text: "And his sons did unto him according as he commanded them:", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son, child" }, { word: "commanded", strongNumber: "H6680", lemma: "tsavah", meaning: "to command, charge" }] },
      { verse: 13, text: "For his sons carried him into the land of Canaan, and buried him in the cave of the field of Machpelah, which Abraham bought with the field for a possession of a buryingplace of Ephron the Hittite, before Mamre.", highlightedWords: [{ word: "Canaan", strongNumber: "H3667", lemma: "Kĕna'an", meaning: "Canaan" }, { word: "Abraham", strongNumber: "H85", lemma: "Avraham", meaning: "Abraham; father of a multitude" }] },
      { verse: 14, text: "And Joseph returned into Egypt, he and his brethren, and all that went up with him to bury his father, after he had buried his father.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 15, text: "And when Joseph's brethren saw that their father was dead, they said, Joseph will peradventure hate us, and will certainly requite us all the evil which we did unto him.", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "'ach", meaning: "brother, kinsman" }, { word: "hate", strongNumber: "H8130", lemma: "sane'", meaning: "to hate" }] },
      { verse: 16, text: "And they sent a messenger unto Joseph, saying, Thy father did command before he died, saying,", highlightedWords: [{ word: "messenger", strongNumber: "H4397", lemma: "mal'ak", meaning: "messenger, angel" }, { word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }] },
      { verse: 17, text: "So shall ye say unto Joseph, Forgive, I pray thee now, the trespass of thy brethren, and their sin; for they did unto thee evil: and now, we pray thee, forgive the trespass of the servants of the God of thy father. And Joseph wept when they spake unto him.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God" }, { word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }] },
      { verse: 18, text: "And his brethren also went and fell down before his face; and they said, Behold, we be thy servants.", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "'ach", meaning: "brother, kinsman" }, { word: "servants", strongNumber: "H5650", lemma: "'ebed", meaning: "servant, slave" }] },
      { verse: 19, text: "And Joseph said unto them, Fear not: for am I in the place of God?", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }, { word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God" }] },
      { verse: 20, text: "But as for you, ye thought evil against me; but God meant it unto good, to bring to pass, as it is this day, to save much people alive.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God" }, { word: "good", strongNumber: "H2896", lemma: "tov", meaning: "good, pleasant" }] },
      { verse: 21, text: "Now therefore fear ye not: I will nourish you, and your little ones. And he comforted them, and spake kindly unto them.", highlightedWords: [{ word: "fear", strongNumber: "H3372", lemma: "yare'", meaning: "to fear, be afraid" }, { word: "spake", strongNumber: "H1696", lemma: "dabar", meaning: "to speak" }] },
      { verse: 22, text: "And Joseph dwelt in Egypt, he, and his father's house: and Joseph lived an hundred and ten years.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds" }, { word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "year" }] },
      { verse: 23, text: "And Joseph saw Ephraim's children of the third generation: the children also of Machir the son of Manasseh were brought up upon Joseph's knees.", highlightedWords: [{ word: "children", strongNumber: "H1121", lemma: "ben", meaning: "son, child" }, { word: "Manasseh", strongNumber: "H4519", lemma: "Mĕnashsheh", meaning: "Manasseh; causing to forget" }] },
      { verse: 24, text: "And Joseph said unto his brethren, I die: and God will surely visit you, and bring you out of this land unto the land which he sware to Abraham, to Isaac, and to Jacob.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "'Elohim", meaning: "God" }, { word: "land", strongNumber: "H776", lemma: "'erets", meaning: "land, earth" }] },
      { verse: 25, text: "And Joseph took an oath of the children of Israel, saying, God will surely visit you, and ye shall carry up my bones from hence.", highlightedWords: [{ word: "oath", strongNumber: "H7621", lemma: "shĕbuw'ah", meaning: "oath, sworn pledge" }, { word: "bones", strongNumber: "H6106", lemma: "'etsem", meaning: "bone, substance" }] },
      { verse: 26, text: "So Joseph died, being an hundred and ten years old: and they embalmed him, and he was put in a coffin in Egypt.", highlightedWords: [{ word: "coffin", strongNumber: "H727", lemma: "'aron", meaning: "chest, ark, coffin" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] }
    ]
  }
}
