import { ChapterData } from "@/lib/bible-data"

export const genesisChapter39: ChapterData = {
  "Genesis-39": {
    book: "Genesis",
    chapter: 39,
    twoWordSummary: "Integrity Tested",
    themeSummary: "Joseph prospers under the LORD's presence, resists his master's wife, is falsely accused, and is shown favor even in prison.",
    sentenceDescription: "Joseph prospers under the LORD's presence, resists his master's wife, is falsely accused, and is shown favor even in prison.",
    themeWords: [
      { word: "LORD", strongNumber: "H3068", language: "Hebrew", lemma: "YHWH", meaning: "the covenant name of God" },
      { word: "Joseph", strongNumber: "H3130", language: "Hebrew", lemma: "Yosef", meaning: "He adds; son of Jacob" }
    ],
    verses: [
      { verse: 1, text: "And Joseph was brought down to Egypt; and Potiphar, an officer of Pharaoh, captain of the guard, an Egyptian, bought him of the hands of the Ishmeelites, which had brought him down thither.", highlightedWords: [{ word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt; land of the Nile" }, { word: "Potiphar", strongNumber: "H6318", lemma: "Potipḥar", meaning: "Egyptian official of Pharaoh" }] },
      { verse: 2, text: "And the LORD was with Joseph, and he was a prosperous man; and he was in the house of his master the Egyptian.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the covenant name of God" }, { word: "house", strongNumber: "H1004", lemma: "bayit", meaning: "house, household" }] },
      { verse: 3, text: "And his master saw that the LORD was with him, and that the LORD made all that he did to prosper in his hand.", highlightedWords: [{ word: "master", strongNumber: "H113", lemma: "'adon", meaning: "lord, master" }, { word: "prosper", strongNumber: "H6743", lemma: "tsalach", meaning: "to succeed, to prosper" }] },
      { verse: 4, text: "And Joseph found grace in his sight, and he served him: and he made him overseer over his house, and all that he had he put into his hand.", highlightedWords: [{ word: "grace", strongNumber: "H2580", lemma: "chen", meaning: "favor, grace" }, { word: "hand", strongNumber: "H3027", lemma: "yad", meaning: "hand, power" }] },
      { verse: 5, text: "And it came to pass from the time that he had made him overseer in his house, and over all that he had, that the LORD blessed the Egyptian's house for Joseph's sake; and the blessing of the LORD was upon all that he had in the house, and in the field.", highlightedWords: [{ word: "blessed", strongNumber: "H1288", lemma: "barak", meaning: "to bless" }, { word: "field", strongNumber: "H7704", lemma: "sadeh", meaning: "field, open country" }] },
      { verse: 6, text: "And he left all that he had in Joseph's hand; and he knew not ought he had, save the bread which he did eat. And Joseph was a goodly person, and well favoured.", highlightedWords: [{ word: "bread", strongNumber: "H3899", lemma: "lechem", meaning: "bread, food" }, { word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "He adds; son of Jacob" }] },
      { verse: 7, text: "And it came to pass after these things, that his master's wife cast her eyes upon Joseph; and she said, Lie with me.", highlightedWords: [{ word: "wife", strongNumber: "H802", lemma: "ishshah", meaning: "woman, wife" }, { word: "Lie", strongNumber: "H7901", lemma: "shakab", meaning: "to lie down (for rest or sexual relations)" }] },
      { verse: 8, text: "But he refused, and said unto his master's wife, Behold, my master wotteth not what is with me in the house, and he hath committed all that he hath to my hand;", highlightedWords: [{ word: "master", strongNumber: "H113", lemma: "'adon", meaning: "lord, master" }, { word: "hand", strongNumber: "H3027", lemma: "yad", meaning: "hand, power" }] },
      { verse: 9, text: "There is none greater in this house than I; neither hath he kept back any thing from me but thee, because thou art his wife: how then can I do this great wickedness, and sin against God?", highlightedWords: [{ word: "sin", strongNumber: "H2398", lemma: "chata'", meaning: "to miss, sin" }, { word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God, mighty one" }] },
      { verse: 10, text: "And it came to pass, as she spake to Joseph day by day, that he hearkened not unto her, to lie by her, or to be with her.", highlightedWords: [{ word: "hearkened", strongNumber: "H8085", lemma: "shama'", meaning: "to hear, listen, obey" }, { word: "day", strongNumber: "H3117", lemma: "yom", meaning: "day" }] },
      { verse: 11, text: "And it came to pass about this time, that Joseph went into the house to do his business; and there was none of the men of the house there within.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "He adds; son of Jacob" }, { word: "house", strongNumber: "H1004", lemma: "bayit", meaning: "house, household" }] },
      { verse: 12, text: "And she caught him by his garment, saying, Lie with me: and he left his garment in her hand, and fled, and got him out.", highlightedWords: [{ word: "garment", strongNumber: "H899", lemma: "beged", meaning: "garment, clothing" }, { word: "fled", strongNumber: "H5127", lemma: "nus", meaning: "to flee" }] },
      { verse: 13, text: "And it came to pass, when she saw that he had left his garment in her hand, and was fled forth,", highlightedWords: [{ word: "saw", strongNumber: "H7200", lemma: "ra'ah", meaning: "to see" }, { word: "garment", strongNumber: "H899", lemma: "beged", meaning: "garment, clothing" }] },
      { verse: 14, text: "That she called unto the men of her house, and spake unto them, saying, See, he hath brought in an Hebrew unto us to mock us; he came in unto me to lie with me, and I cried with a loud voice:", highlightedWords: [{ word: "Hebrew", strongNumber: "H5680", lemma: "Ivri", meaning: "a Hebrew" }, { word: "mock", strongNumber: "H6711", lemma: "tsachaq", meaning: "to laugh, mock, sport" }] },
      { verse: 15, text: "And it came to pass, when he heard that I lifted up my voice and cried, that he left his garment with me, and fled, and got him out.", highlightedWords: [{ word: "voice", strongNumber: "H6963", lemma: "qol", meaning: "voice, sound" }, { word: "fled", strongNumber: "H5127", lemma: "nus", meaning: "to flee" }] },
      { verse: 16, text: "And she laid up his garment by her, until his lord came home.", highlightedWords: [{ word: "garment", strongNumber: "H899", lemma: "beged", meaning: "garment, clothing" }, { word: "lord", strongNumber: "H113", lemma: "'adon", meaning: "lord, master" }] },
      { verse: 17, text: "And she spake unto him according to these words, saying, The Hebrew servant, which thou hast brought unto us, came in unto me to mock me:", highlightedWords: [{ word: "servant", strongNumber: "H5650", lemma: "'ebed", meaning: "servant, slave" }, { word: "Hebrew", strongNumber: "H5680", lemma: "Ivri", meaning: "a Hebrew" }] },
      { verse: 18, text: "And it came to pass, as I lifted up my voice and cried, that he left his garment with me, and fled out.", highlightedWords: [{ word: "cried", strongNumber: "H7121", lemma: "qara'", meaning: "to call, cry out" }, { word: "garment", strongNumber: "H899", lemma: "beged", meaning: "garment, clothing" }] },
      { verse: 19, text: "And it came to pass, when his master heard the words of his wife, which she spake unto him, saying, After this manner did thy servant to me; that his wrath was kindled.", highlightedWords: [{ word: "wrath", strongNumber: "H639", lemma: "'aph", meaning: "nose, anger, wrath" }, { word: "kindled", strongNumber: "H2734", lemma: "charah", meaning: "to burn, be kindled (with anger)" }] },
      { verse: 20, text: "And Joseph's master took him, and put him into the prison, a place where the king's prisoners were bound: and he was there in the prison.", highlightedWords: [{ word: "prison", strongNumber: "H5470", lemma: "sohar", meaning: "prison, round-house" }, { word: "bound", strongNumber: "H631", lemma: "'asar", meaning: "to bind, imprison" }] },
      { verse: 21, text: "But the LORD was with Joseph, and shewed him mercy, and gave him favour in the sight of the keeper of the prison.", highlightedWords: [{ word: "mercy", strongNumber: "H2617", lemma: "chesed", meaning: "kindness, loyal love, mercy" }, { word: "favour", strongNumber: "H2580", lemma: "chen", meaning: "favor, grace" }] },
      { verse: 22, text: "And the keeper of the prison committed to Joseph's hand all the prisoners that were in the prison; and whatsoever they did there, he was the doer of it.", highlightedWords: [{ word: "keeper", strongNumber: "H8269", lemma: "sar", meaning: "chief, ruler" }, { word: "prison", strongNumber: "H5470", lemma: "sohar", meaning: "prison, round-house" }] },
      { verse: 23, text: "The keeper of the prison looked not to any thing that was under his hand; because the LORD was with him, and that which he did, the LORD made it to prosper.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the covenant name of God" }, { word: "prosper", strongNumber: "H6743", lemma: "tsalach", meaning: "to succeed, to prosper" }] }
    ]
  }
}
