import { ChapterData } from "@/lib/bible-data"

export const genesisChapter32: ChapterData = {
  "Genesis-32": {
    book: "Genesis",
    chapter: 32,
    twoWordSummary: "Wrestling Transformation",
    themeSummary: "Jacob prepares to meet Esau with fear and prayer, sends gifts ahead, and wrestles through the night at Jabbok where he is blessed and renamed Israel.",
    sentenceDescription: "Jacob prepares to meet Esau with fear and prayer, sends gifts ahead, and wrestles through the night at Jabbok where he is blessed and renamed Israel.",
    themeWords: [
      { word: "Jacob", strongNumber: "H3290", language: "Hebrew", lemma: "יַעֲקֹב", meaning: "Jacob; heel-holder, supplanter" },
      { word: "Israel", strongNumber: "H3478", language: "Hebrew", lemma: "יִשְׂרָאֵל", meaning: "Israel; God strives, he struggles with God" }
    ],
    verses: [
      { verse: 1, text: "And Jacob went on his way, and the angels of God met him.", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "יַעֲקֹב", meaning: "Jacob; heel-holder, supplanter" }, { word: "angels", strongNumber: "H4397", lemma: "מַלְאָךְ", meaning: "messenger, angel" }] },
      { verse: 2, text: "And when Jacob saw them, he said, This is God's host: and he called the name of that place Mahanaim.", highlightedWords: [{ word: "host", strongNumber: "H4264", lemma: "מַחֲנֶה", meaning: "camp, army, host" }, { word: "Mahanaim", strongNumber: "H4266", lemma: "מַחֲנַיִם", meaning: "Mahanaim; two camps" }] },
      { verse: 3, text: "And Jacob sent messengers before him to Esau his brother unto the land of Seir, the country of Edom.", highlightedWords: [{ word: "messengers", strongNumber: "H4397", lemma: "מַלְאָךְ", meaning: "messenger, envoy" }, { word: "Esau", strongNumber: "H6215", lemma: "עֵשָׂו", meaning: "Esau; hairy" }] },
      { verse: 4, text: "And he commanded them, saying, Thus shall ye speak unto my lord Esau; Thy servant Jacob saith thus, I have sojourned with Laban, and stayed there until now:", highlightedWords: [{ word: "lord", strongNumber: "H113", lemma: "אֲדוֹן", meaning: "lord, master" }, { word: "Laban", strongNumber: "H3837", lemma: "לָבָן", meaning: "Laban; white" }] },
      { verse: 5, text: "And I have oxen, and asses, flocks, and menservants, and womenservants: and I have sent to tell my lord, that I may find grace in thy sight.", highlightedWords: [{ word: "oxen", strongNumber: "H7794", lemma: "שׁוֹר", meaning: "ox, bull" }, { word: "grace", strongNumber: "H2580", lemma: "חֵן", meaning: "grace, favor" }] },
      { verse: 6, text: "And the messengers returned to Jacob, saying, We came to thy brother Esau, and also he cometh to meet thee, and four hundred men with him.", highlightedWords: [{ word: "messengers", strongNumber: "H4397", lemma: "מַלְאָךְ", meaning: "messenger, envoy" }, { word: "Esau", strongNumber: "H6215", lemma: "עֵשָׂו", meaning: "Esau; hairy" }] },
      { verse: 7, text: "Then Jacob was greatly afraid and distressed: and he divided the people that was with him, and the flocks, and herds, and the camels, into two bands;", highlightedWords: [{ word: "afraid", strongNumber: "H3372", lemma: "יָרֵא", meaning: "to fear, be afraid" }, { word: "bands", strongNumber: "H4264", lemma: "מַחֲנֶה", meaning: "camp, band" }] },
      { verse: 8, text: "And said, If Esau come to the one company, and smite it, then the other company which is left shall escape.", highlightedWords: [{ word: "Esau", strongNumber: "H6215", lemma: "עֵשָׂו", meaning: "Esau; hairy" }, { word: "company", strongNumber: "H4264", lemma: "מַחֲנֶה", meaning: "camp, company" }] },
      { verse: 9, text: "And Jacob said, O God of my father Abraham, and God of my father Isaac, the LORD which saidst unto me, Return unto thy country, and to thy kindred, and I will deal well with thee:", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "יְהוָה", meaning: "the personal name of Israel's God, YHWH" }, { word: "Abraham", strongNumber: "H85", lemma: "אַבְרָהָם", meaning: "Abraham; father of a multitude" }] },
      { verse: 10, text: "I am not worthy of the least of all the mercies, and of all the truth, which thou hast shewed unto thy servant; for with my staff I passed over this Jordan; and now I am become two bands.", highlightedWords: [{ word: "mercies", strongNumber: "H2617", lemma: "חֶסֶד", meaning: "steadfast love, kindness, mercy" }, { word: "Jordan", strongNumber: "H3383", lemma: "יַרְדֵּן", meaning: "Jordan (the river)" }] },
      { verse: 11, text: "Deliver me, I pray thee, from the hand of my brother, from the hand of Esau: for I fear him, lest he will come and smite me, and the mother with the children.", highlightedWords: [{ word: "Deliver", strongNumber: "H5337", lemma: "נָצַל", meaning: "to deliver, rescue, snatch away" }, { word: "Esau", strongNumber: "H6215", lemma: "עֵשָׂו", meaning: "Esau; hairy" }] },
      { verse: 12, text: "And thou saidst, I will surely do thee good, and make thy seed as the sand of the sea, which cannot be numbered for multitude.", highlightedWords: [{ word: "seed", strongNumber: "H2233", lemma: "זֶרַע", meaning: "seed, offspring, descendants" }, { word: "sand", strongNumber: "H2344", lemma: "חוֹל", meaning: "sand" }] },
      { verse: 13, text: "And he lodged there that same night; and took of that which came to his hand a present for Esau his brother;", highlightedWords: [{ word: "present", strongNumber: "H4503", lemma: "מִנְחָה", meaning: "gift, offering, tribute" }, { word: "Esau", strongNumber: "H6215", lemma: "עֵשָׂו", meaning: "Esau; hairy" }] },
      { verse: 14, text: "Two hundred she goats, and twenty he goats, two hundred ewes, and twenty rams,", highlightedWords: [{ word: "she goats", strongNumber: "H5795", lemma: "עֵז", meaning: "she-goat" }, { word: "rams", strongNumber: "H352", lemma: "אַיִל", meaning: "ram" }] },
      { verse: 15, text: "Thirty milch camels with their colts, forty kine, and ten bulls, twenty she asses, and ten foals.", highlightedWords: [{ word: "camels", strongNumber: "H1581", lemma: "גָּמָל", meaning: "camel" }, { word: "kine", strongNumber: "H6510", lemma: "פָּרָה", meaning: "cow (kine)" }] },
      { verse: 16, text: "And he delivered them into the hand of his servants, every drove by themselves; and said unto his servants, Pass over before me, and put a space betwixt drove and drove.", highlightedWords: [{ word: "servants", strongNumber: "H5650", lemma: "עֶבֶד", meaning: "servant, slave" }, { word: "drove", strongNumber: "H5739", lemma: "עֵדֶר", meaning: "flock, herd, drove" }] },
      { verse: 17, text: "And he commanded the foremost, saying, When Esau my brother meeteth thee, and asketh thee, saying, Whose art thou? and whither goest thou? and whose are these before thee?", highlightedWords: [{ word: "Esau", strongNumber: "H6215", lemma: "עֵשָׂו", meaning: "Esau; hairy" }, { word: "brother", strongNumber: "H251", lemma: "אָח", meaning: "brother, kinsman" }] },
      { verse: 18, text: "Then thou shalt say, They be thy servant Jacob's; it is a present sent unto my lord Esau: and, behold, also he is behind us.", highlightedWords: [{ word: "servant", strongNumber: "H5650", lemma: "עֶבֶד", meaning: "servant, slave" }, { word: "present", strongNumber: "H4503", lemma: "מִנְחָה", meaning: "gift, offering, tribute" }] },
      { verse: 19, text: "And so commanded he the second, and the third, and all that followed the droves, saying, On this manner shall ye speak unto Esau, when ye find him;", highlightedWords: [{ word: "droves", strongNumber: "H5739", lemma: "עֵדֶר", meaning: "flocks, herds, droves" }, { word: "Esau", strongNumber: "H6215", lemma: "עֵשָׂו", meaning: "Esau; hairy" }] },
      { verse: 20, text: "And say ye moreover, Behold, thy servant Jacob is behind us. For he said, I will appease him with the present that goeth before me, and afterward I will see his face; peradventure he will accept of me.", highlightedWords: [{ word: "appease", strongNumber: "H3722", lemma: "כָּפַר", meaning: "to cover, atone, appease" }, { word: "present", strongNumber: "H4503", lemma: "מִנְחָה", meaning: "gift, offering, tribute" }] },
      { verse: 21, text: "So went the present over before him: and himself lodged that night in the company.", highlightedWords: [{ word: "present", strongNumber: "H4503", lemma: "מִנְחָה", meaning: "gift, offering, tribute" }, { word: "night", strongNumber: "H3915", lemma: "לַיְלָה", meaning: "night" }] },
      { verse: 22, text: "And he rose up that night, and took his two wives, and his two womenservants, and his eleven sons, and passed over the ford Jabbok.", highlightedWords: [{ word: "wives", strongNumber: "H802", lemma: "אִשָּׁה", meaning: "woman, wife" }, { word: "Jabbok", strongNumber: "H2999", lemma: "יַבֹּק", meaning: "Jabbok (a tributary of the Jordan)" }] },
      { verse: 23, text: "And he took them, and sent them over the brook, and sent over that he had.", highlightedWords: [{ word: "sent", strongNumber: "H5674", lemma: "עָבַר", meaning: "to pass over, cause to cross" }, { word: "brook", strongNumber: "H5158", lemma: "נַחַל", meaning: "brook, wadi, stream" }] },
      { verse: 24, text: "And Jacob was left alone; and there wrestled a man with him until the breaking of the day.", highlightedWords: [{ word: "wrestled", strongNumber: "H79", lemma: "אָבַק", meaning: "to wrestle" }, { word: "man", strongNumber: "H376", lemma: "אִישׁ", meaning: "man" }] },
      { verse: 25, text: "And when he saw that he prevailed not against him, he touched the hollow of his thigh; and the hollow of Jacob's thigh was out of joint, as he wrestled with him.", highlightedWords: [{ word: "hollow", strongNumber: "H3709", lemma: "כַּף", meaning: "palm, hollow (of hand or foot)" }, { word: "thigh", strongNumber: "H3409", lemma: "יָרֵךְ", meaning: "thigh, loins" }] },
      { verse: 26, text: "And he said, Let me go, for the day breaketh. And he said, I will not let thee go, except thou bless me.", highlightedWords: [{ word: "day", strongNumber: "H3117", lemma: "יוֹם", meaning: "day" }, { word: "bless", strongNumber: "H1288", lemma: "בָּרַךְ", meaning: "to bless" }] },
      { verse: 27, text: "And he said unto him, What is thy name? And he said, Jacob.", highlightedWords: [{ word: "name", strongNumber: "H8034", lemma: "שֵׁם", meaning: "name, reputation" }, { word: "Jacob", strongNumber: "H3290", lemma: "יַעֲקֹב", meaning: "Jacob; heel-holder, supplanter" }] },
      { verse: 28, text: "And he said, Thy name shall be called no more Jacob, but Israel: for as a prince hast thou power with God and with men, and hast prevailed.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "יִשְׂרָאֵל", meaning: "Israel; God strives, he struggles with God" }, { word: "God", strongNumber: "H430", lemma: "אֱלֹהִים", meaning: "God" }] },
      { verse: 29, text: "And Jacob asked him, and said, Tell me, I pray thee, thy name. And he said, Wherefore is it that thou dost ask after my name? And he blessed him there.", highlightedWords: [{ word: "name", strongNumber: "H8034", lemma: "שֵׁם", meaning: "name, reputation" }, { word: "blessed", strongNumber: "H1288", lemma: "בָּרַךְ", meaning: "to bless" }] },
      { verse: 30, text: "And Jacob called the name of the place Peniel: for I have seen God face to face, and my life is preserved.", highlightedWords: [{ word: "Peniel", strongNumber: "H6439", lemma: "פְּנוּאֵל", meaning: "Peniel/Penuel; face of God" }, { word: "God", strongNumber: "H430", lemma: "אֱלֹהִים", meaning: "God" }] },
      { verse: 31, text: "And as he passed over Penuel the sun rose upon him, and he halted upon his thigh.", highlightedWords: [{ word: "Penuel", strongNumber: "H6439", lemma: "פְּנוּאֵל", meaning: "Peniel/Penuel; face of God" }, { word: "halted", strongNumber: "H6760", lemma: "צָלַע", meaning: "to limp, be lame" }] },
      { verse: 32, text: "Therefore the children of Israel eat not of the sinew which shrank, which is upon the hollow of the thigh, unto this day: because he touched the hollow of Jacob's thigh in the sinew that shrank.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "יִשְׂרָאֵל", meaning: "Israel; God strives, he struggles with God" }, { word: "sinew", strongNumber: "H1517", lemma: "גִּיד", meaning: "sinew, tendon" }] }
    ]
  }
}
