import { ChapterData } from "@/lib/bible-data"

export const genesisChapter47: ChapterData = {
  "Genesis-47": {
    book: "Genesis",
    chapter: 47,
    twoWordSummary: "Famine Administration",
    themeSummary: "Joseph settles his family in Goshen, administers Egypt through severe famine by acquiring land and establishing a fifth-part tax, and Jacob (Israel) blesses Pharaoh and secures a promise to be buried with his fathers.",
    sentenceDescription: "Joseph settles his family in Goshen, administers Egypt through severe famine by acquiring land and establishing a fifth-part tax, and Jacob (Israel) blesses Pharaoh and secures a promise to be buried with his fathers.",
    themeWords: [
      { word: "Joseph", strongNumber: "H3130", language: "Hebrew", lemma: "Yosef", meaning: "he will add" },
      { word: "Pharaoh", strongNumber: "H6547", language: "Hebrew", lemma: "Paroh", meaning: "title of the Egyptian king; great house" }
    ],
    verses: [
      { verse: 1, text: "Then Joseph came and told Pharaoh, and said, My father and my brethren, and their flocks, and their herds, and all that they have, are come out of the land of Canaan; and, behold, they are in the land of Goshen.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "Goshen", strongNumber: "H1657", lemma: "Goshen", meaning: "a region in Egypt where Israel dwelt" }] },
      { verse: 2, text: "And he took some of his brethren, even five men, and presented them unto Pharaoh.", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "'ach", meaning: "brother; kinsman" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "title of the Egyptian king; great house" }] },
      { verse: 3, text: "And Pharaoh said unto his brethren, What is your occupation? And they said unto Pharaoh, Thy servants are shepherds, both we, and also our fathers.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "title of the Egyptian king; great house" }, { word: "servants", strongNumber: "H5650", lemma: "'eved", meaning: "servant; slave; bondman" }] },
      { verse: 4, text: "They said moreover unto Pharaoh, For to sojourn in the land are we come; for thy servants have no pasture for their flocks; for the famine is sore in the land of Canaan: now therefore, we pray thee, let thy servants dwell in the land of Goshen.", highlightedWords: [{ word: "famine", strongNumber: "H7458", lemma: "ra'av", meaning: "famine; hunger" }, { word: "Goshen", strongNumber: "H1657", lemma: "Goshen", meaning: "a region in Egypt where Israel dwelt" }] },
      { verse: 5, text: "And Pharaoh spake unto Joseph, saying, Thy father and thy brethren are come unto thee:", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "title of the Egyptian king; great house" }, { word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }] },
      { verse: 6, text: "The land of Egypt is before thee; in the best of the land make thy father and brethren to dwell; in the land of Goshen let them dwell: and if thou knowest any men of activity among them, then make them rulers over my cattle.", highlightedWords: [{ word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }, { word: "cattle", strongNumber: "H4735", lemma: "miqneh", meaning: "livestock; cattle; possessions" }] },
      { verse: 7, text: "And Joseph brought in Jacob his father, and set him before Pharaoh: and Jacob blessed Pharaoh.", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqov", meaning: "Jacob; supplanter" }, { word: "blessed", strongNumber: "H1288", lemma: "barak", meaning: "to bless; to praise" }] },
      { verse: 8, text: "And Pharaoh said unto Jacob, How old art thou?", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "title of the Egyptian king; great house" }, { word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqov", meaning: "Jacob; supplanter" }] },
      { verse: 9, text: "And Jacob said unto Pharaoh, The days of the years of my pilgrimage are an hundred and thirty years: few and evil have the days of the years of my life been, and have not attained unto the days of the years of the life of my fathers in the days of their pilgrimage.", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqov", meaning: "Jacob; supplanter" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "title of the Egyptian king; great house" }] },
      { verse: 10, text: "And Jacob blessed Pharaoh, and went out from before Pharaoh.", highlightedWords: [{ word: "blessed", strongNumber: "H1288", lemma: "barak", meaning: "to bless; to praise" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "title of the Egyptian king; great house" }] },
      { verse: 11, text: "And Joseph placed his father and his brethren, and gave them a possession in the land of Egypt, in the best of the land, in the land of Rameses, as Pharaoh had commanded.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 12, text: "And Joseph nourished his father, and his brethren, and all his father's household, with bread, according to their families.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "bread", strongNumber: "H3899", lemma: "lechem", meaning: "bread; food" }] },
      { verse: 13, text: "And there was no bread in all the land; for the famine was very sore, so that the land of Egypt and all the land of Canaan fainted by reason of the famine.", highlightedWords: [{ word: "bread", strongNumber: "H3899", lemma: "lechem", meaning: "bread; food" }, { word: "famine", strongNumber: "H7458", lemma: "ra'av", meaning: "famine; hunger" }] },
      { verse: 14, text: "And Joseph gathered up all the money that was found in the land of Egypt, and in the land of Canaan, for the corn which they bought: and Joseph brought the money into Pharaoh's house.", highlightedWords: [{ word: "money", strongNumber: "H3701", lemma: "keseph", meaning: "silver; money" }, { word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }] },
      { verse: 15, text: "And when money failed in the land of Egypt, and in the land of Canaan, all the Egyptians came unto Joseph, and said, Give us bread: for why should we die in thy presence? for the money faileth.", highlightedWords: [{ word: "money", strongNumber: "H3701", lemma: "keseph", meaning: "silver; money" }, { word: "bread", strongNumber: "H3899", lemma: "lechem", meaning: "bread; food" }] },
      { verse: 16, text: "And Joseph said, Give your cattle; and I will give you for your cattle, if money fail.", highlightedWords: [{ word: "cattle", strongNumber: "H4735", lemma: "miqneh", meaning: "livestock; cattle; possessions" }, { word: "money", strongNumber: "H3701", lemma: "keseph", meaning: "silver; money" }] },
      { verse: 17, text: "And they brought their cattle unto Joseph: and Joseph gave them bread in exchange for horses, and for the flocks, and for the cattle of the herds, and for the asses: and he fed them with bread for all their cattle for that year.", highlightedWords: [{ word: "cattle", strongNumber: "H4735", lemma: "miqneh", meaning: "livestock; cattle; possessions" }, { word: "bread", strongNumber: "H3899", lemma: "lechem", meaning: "bread; food" }] },
      { verse: 18, text: "When that year was ended, they came unto him the second year, and said unto him, We will not hide it from my lord, how that our money is spent; my lord also hath our herds of cattle; there is not ought left in the sight of my lord, but our bodies, and our lands:", highlightedWords: [{ word: "money", strongNumber: "H3701", lemma: "keseph", meaning: "silver; money" }, { word: "cattle", strongNumber: "H4735", lemma: "miqneh", meaning: "livestock; cattle; possessions" }] },
      { verse: 19, text: "Wherefore shall we die before thine eyes, both we and our land? buy us and our land for bread, and we and our land will be servants unto Pharaoh: and give us seed, that we may live, and not die, that the land be not desolate.", highlightedWords: [{ word: "seed", strongNumber: "H2233", lemma: "zera'", meaning: "seed; offspring" }, { word: "land", strongNumber: "H776", lemma: "'erets", meaning: "land; earth; territory" }] },
      { verse: 20, text: "And Joseph bought all the land of Egypt for Pharaoh; for the Egyptians sold every man his field, because the famine prevailed over them: so the land became Pharaoh's.", highlightedWords: [{ word: "land", strongNumber: "H776", lemma: "'erets", meaning: "land; earth; territory" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 21, text: "And as for the people, he removed them to cities from one end of the borders of Egypt even to the other end thereof.", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "'am", meaning: "people; nation" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 22, text: "Only the land of the priests bought he not; for the priests had a portion assigned them of Pharaoh, and did eat their portion which Pharaoh gave them: wherefore they sold not their lands.", highlightedWords: [{ word: "priests", strongNumber: "H3548", lemma: "kohen", meaning: "priest" }, { word: "land", strongNumber: "H776", lemma: "'erets", meaning: "land; earth; territory" }] },
      { verse: 23, text: "Then Joseph said unto the people, Behold, I have bought you this day and your land for Pharaoh: lo, here is seed for you, and ye shall sow the land.", highlightedWords: [{ word: "seed", strongNumber: "H2233", lemma: "zera'", meaning: "seed; offspring" }, { word: "land", strongNumber: "H776", lemma: "'erets", meaning: "land; earth; territory" }] },
      { verse: 24, text: "And it shall come to pass in the increase, that ye shall give the fifth part unto Pharaoh, and four parts shall be your own, for seed of the field, and for your food, and for them of your households, and for food for your little ones.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "title of the Egyptian king; great house" }, { word: "seed", strongNumber: "H2233", lemma: "zera'", meaning: "seed; offspring" }] },
      { verse: 25, text: "And they said, Thou hast saved our lives: let us find grace in the sight of my lord, and we will be Pharaoh's servants.", highlightedWords: [{ word: "grace", strongNumber: "H2580", lemma: "chen", meaning: "favor; grace" }, { word: "servants", strongNumber: "H5650", lemma: "'eved", meaning: "servant; slave; bondman" }] },
      { verse: 26, text: "And Joseph made it a law over the land of Egypt unto this day, that Pharaoh should have the fifth part; except the land of the priests only, which became not Pharaoh's.", highlightedWords: [{ word: "law", strongNumber: "H2706", lemma: "choq", meaning: "statute; decree; law" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "title of the Egyptian king; great house" }] },
      { verse: 27, text: "And Israel dwelt in the land of Egypt, in the country of Goshen; and they had possessions therein, and grew, and multiplied exceedingly.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; God strives" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 28, text: "And Jacob lived in the land of Egypt seventeen years: so the whole age of Jacob was an hundred forty and seven years.", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqov", meaning: "Jacob; supplanter" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 29, text: "And the time drew nigh that Israel must die: and he called his son Joseph, and said unto him, If now I have found grace in thy sight, put, I pray thee, thy hand under my thigh, and deal kindly and truly with me; bury me not, I pray thee, in Egypt:", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; God strives" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 30, text: "But I will lie with my fathers, and thou shalt carry me out of Egypt, and bury me in their buryingplace. And he said, I will do as thou hast said.", highlightedWords: [{ word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }, { word: "bury", strongNumber: "H6912", lemma: "qabar", meaning: "to bury; inter" }] },
      { verse: 31, text: "And he said, Swear unto me. And he sware unto him. And Israel bowed himself upon the bed's head.", highlightedWords: [{ word: "Swear", strongNumber: "H7650", lemma: "shava'", meaning: "to swear; take an oath" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; God strives" }] }
    ]
  }
}
