import { ChapterData } from "@/lib/bible-data"

export const genesisChapter11: ChapterData = {
  "Genesis-11": {
    book: "Genesis",
    chapter: 11,
    chapterTheme: {
      twoWordSummary: "Babel Confusion",
      themeWords: [
        { word: "confound", strongNumber: "H1101", lemma: "balal", meaning: "to mix, confuse, or bring disorder so communication becomes unintelligible" },
        { word: "language", strongNumber: "H8193", lemma: "saphah", meaning: "lip or speech referring to the language spoken by a people" }
      ]
    },
    sentenceTheme: "Humanity attempts to build a tower to reach heaven, but God confuses their language and scatters them across the earth.",
    verses: [
      { verse: 1, text: "And the whole earth was of one language, and of one speech.", highlightedWords: [{ word: "language", strongNumber: "H8193", lemma: "saphah", meaning: "spoken language or speech shared by a people" }, { word: "speech", strongNumber: "H1697", lemma: "dabar", meaning: "word, matter, or spoken communication" }] },
      { verse: 2, text: "And it came to pass, as they journeyed from the east, that they found a plain in the land of Shinar; and they dwelt there.", highlightedWords: [{ word: "journeyed", strongNumber: "H5265", lemma: "nasa", meaning: "to set out, travel, or migrate from one place to another" }, { word: "dwelt", strongNumber: "H3427", lemma: "yashab", meaning: "to sit, remain, or settle in a place" }] },
      { verse: 3, text: "And they said one to another, Go to, let us make brick, and burn them throughly. And they had brick for stone, and slime had they for morter.", highlightedWords: [{ word: "brick", strongNumber: "H3843", lemma: "lebenah", meaning: "a baked clay brick used for building structures" }, { word: "burn", strongNumber: "H8313", lemma: "saraph", meaning: "to burn or fire intensely" }] },
      { verse: 4, text: "And they said, Go to, let us build us a city and a tower, whose top may reach unto heaven; and let us make us a name, lest we be scattered abroad upon the face of the whole earth.", highlightedWords: [{ word: "tower", strongNumber: "H4026", lemma: "migdal", meaning: "a tall structure or tower used for prominence or defense" }, { word: "name", strongNumber: "H8034", lemma: "shem", meaning: "a name representing reputation, fame, or renown" }] },
      { verse: 5, text: "And the LORD came down to see the city and the tower, which the children of men builded.", highlightedWords: [{ word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the covenant name of God, the self-existent eternal One" }, { word: "children", strongNumber: "H1121", lemma: "ben", meaning: "sons or descendants representing humanity" }] },
      { verse: 6, text: "And the LORD said, Behold, the people is one, and they have all one language; and this they begin to do: and now nothing will be restrained from them, which they have imagined to do.", highlightedWords: [{ word: "people", strongNumber: "H5971", lemma: "am", meaning: "a people united as a community" }, { word: "imagined", strongNumber: "H2161", lemma: "zamam", meaning: "to devise, plan, or purpose within the mind" }] },
      { verse: 7, text: "Go to, let us go down, and there confound their language, that they may not understand one another's speech.", highlightedWords: [{ word: "confound", strongNumber: "H1101", lemma: "balal", meaning: "to mix, confuse, or bring disorder" }, { word: "understand", strongNumber: "H8085", lemma: "shama", meaning: "to hear intelligently or comprehend" }] },
      { verse: 8, text: "So the LORD scattered them abroad from thence upon the face of all the earth: and they left off to build the city.", highlightedWords: [{ word: "scattered", strongNumber: "H6327", lemma: "puwts", meaning: "to disperse widely or spread abroad" }, { word: "earth", strongNumber: "H776", lemma: "erets", meaning: "land or the inhabited world" }] },
      { verse: 9, text: "Therefore is the name of it called Babel; because the LORD did there confound the language of all the earth: and from thence did the LORD scatter them abroad upon the face of all the earth.", highlightedWords: [{ word: "Babel", strongNumber: "H894", lemma: "Babel", meaning: "Babylon; associated with confusion because languages were mixed there" }, { word: "language", strongNumber: "H8193", lemma: "saphah", meaning: "speech or language used by a people" }] },
      { verse: 10, text: "These are the generations of Shem: Shem was an hundred years old, and begat Arphaxad two years after the flood:", highlightedWords: [{ word: "generations", strongNumber: "H8435", lemma: "toledoth", meaning: "family records tracing lineage and descendants" }, { word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bring forth offspring or descendants" }] },
      { verse: 11, text: "And Shem lived after he begat Arphaxad five hundred years, and begat sons and daughters.", highlightedWords: [{ word: "lived", strongNumber: "H2421", lemma: "chayah", meaning: "to live, remain alive, or continue in life" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "male descendants within a family line" }] },
      { verse: 12, text: "And Arphaxad lived five and thirty years, and begat Salah:", highlightedWords: [{ word: "Arphaxad", strongNumber: "H775", lemma: "Arpakshad", meaning: "a descendant of Shem and ancestor in the Hebrew lineage" }, { word: "Salah", strongNumber: "H7974", lemma: "Shelach", meaning: "a patriarch in the genealogy leading to Abraham" }] },
      { verse: 13, text: "And Arphaxad lived after he begat Salah four hundred and three years, and begat sons and daughters.", highlightedWords: [{ word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "a cycle of time representing a full year" }, { word: "daughters", strongNumber: "H1323", lemma: "bath", meaning: "female offspring within a family lineage" }] },
      { verse: 14, text: "And Salah lived thirty years, and begat Eber:", highlightedWords: [{ word: "Salah", strongNumber: "H7974", lemma: "Shelach", meaning: "a patriarch in the ancestral line to Abraham" }, { word: "Eber", strongNumber: "H5677", lemma: "Eber", meaning: "ancestor associated with the Hebrews" }] },
      { verse: 15, text: "And Salah lived after he begat Eber four hundred and three years, and begat sons and daughters.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "male descendants continuing the lineage" }, { word: "daughters", strongNumber: "H1323", lemma: "bath", meaning: "female descendants within a family" }] },
      { verse: 16, text: "And Eber lived four and thirty years, and begat Peleg:", highlightedWords: [{ word: "Eber", strongNumber: "H5677", lemma: "Eber", meaning: "the forefather associated with the Hebrew people" }, { word: "Peleg", strongNumber: "H6389", lemma: "Peleg", meaning: "name meaning division, marking a time when the earth was divided" }] },
      { verse: 17, text: "And Eber lived after he begat Peleg four hundred and thirty years, and begat sons and daughters.", highlightedWords: [{ word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to father or produce descendants" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "male descendants continuing a family line" }] },
      { verse: 18, text: "And Peleg lived thirty years, and begat Reu:", highlightedWords: [{ word: "Peleg", strongNumber: "H6389", lemma: "Peleg", meaning: "a descendant whose name signifies division" }, { word: "Reu", strongNumber: "H7466", lemma: "Reu", meaning: "a patriarch in the genealogy leading to Abraham" }] },
      { verse: 19, text: "And Peleg lived after he begat Reu two hundred and nine years, and begat sons and daughters.", highlightedWords: [{ word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "a yearly cycle marking the passage of time" }, { word: "daughters", strongNumber: "H1323", lemma: "bath", meaning: "female offspring within a family" }] },
      { verse: 20, text: "And Reu lived two and thirty years, and begat Serug:", highlightedWords: [{ word: "Reu", strongNumber: "H7466", lemma: "Reu", meaning: "ancestor in the lineage leading to Abraham" }, { word: "Serug", strongNumber: "H8286", lemma: "Serug", meaning: "a patriarch in the ancestral line" }] },
      { verse: 21, text: "And Reu lived after he begat Serug two hundred and seven years, and begat sons and daughters.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "male descendants within a lineage" }, { word: "daughters", strongNumber: "H1323", lemma: "bath", meaning: "female descendants" }] },
      { verse: 22, text: "And Serug lived thirty years, and begat Nahor:", highlightedWords: [{ word: "Serug", strongNumber: "H8286", lemma: "Serug", meaning: "a patriarch within the genealogy" }, { word: "Nahor", strongNumber: "H5152", lemma: "Nachor", meaning: "ancestor within Abraham's family line" }] },
      { verse: 23, text: "And Serug lived after he begat Nahor two hundred years, and begat sons and daughters.", highlightedWords: [{ word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "a yearly cycle measuring time" }, { word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bring forth descendants" }] },
      { verse: 24, text: "And Nahor lived nine and twenty years, and begat Terah:", highlightedWords: [{ word: "Nahor", strongNumber: "H5152", lemma: "Nachor", meaning: "an ancestor within Abraham's genealogy" }, { word: "Terah", strongNumber: "H8646", lemma: "Terach", meaning: "father of Abram and patriarch of the family" }] },
      { verse: 25, text: "And Nahor lived after he begat Terah an hundred and nineteen years, and begat sons and daughters.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "male descendants within a lineage" }, { word: "daughters", strongNumber: "H1323", lemma: "bath", meaning: "female descendants" }] },
      { verse: 26, text: "And Terah lived seventy years, and begat Abram, Nahor, and Haran.", highlightedWords: [{ word: "Abram", strongNumber: "H87", lemma: "Abram", meaning: "exalted father; the original name of Abraham" }, { word: "Haran", strongNumber: "H2039", lemma: "Haran", meaning: "son of Terah and father of Lot" }] },
      { verse: 27, text: "Now these are the generations of Terah: Terah begat Abram, Nahor, and Haran; and Haran begat Lot.", highlightedWords: [{ word: "generations", strongNumber: "H8435", lemma: "toledoth", meaning: "records of family lineage and descendants" }, { word: "Lot", strongNumber: "H3876", lemma: "Lot", meaning: "the son of Haran and nephew of Abram" }] },
      { verse: 28, text: "And Haran died before his father Terah in the land of his nativity, in Ur of the Chaldees.", highlightedWords: [{ word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die or cease living" }, { word: "Ur", strongNumber: "H218", lemma: "Ur", meaning: "an ancient Mesopotamian city, birthplace of Abram" }] },
      { verse: 29, text: "And Abram and Nahor took them wives: the name of Abram's wife was Sarai; and the name of Nahor's wife, Milcah, the daughter of Haran, the father of Milcah, and the father of Iscah.", highlightedWords: [{ word: "wives", strongNumber: "H802", lemma: "ishshah", meaning: "a woman, wife, or female partner in marriage" }, { word: "Sarai", strongNumber: "H8297", lemma: "Saray", meaning: "princess; the original name of Sarah" }] },
      { verse: 30, text: "But Sarai was barren; she had no child.", highlightedWords: [{ word: "barren", strongNumber: "H6135", lemma: "aqar", meaning: "unable to bear children" }, { word: "child", strongNumber: "H2056", lemma: "yeled", meaning: "a child or offspring" }] },
      { verse: 31, text: "And Terah took Abram his son, and Lot the son of Haran his son's son, and Sarai his daughter in law, his son Abram's wife; and they went forth with them from Ur of the Chaldees, to go into the land of Canaan; and they came unto Haran, and dwelt there.", highlightedWords: [{ word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "the land later promised by God to Abram's descendants" }, { word: "dwelt", strongNumber: "H3427", lemma: "yashab", meaning: "to settle or live in a place" }] },
      { verse: 32, text: "And the days of Terah were two hundred and five years: and Terah died in Haran.", highlightedWords: [{ word: "days", strongNumber: "H3117", lemma: "yom", meaning: "days representing the span of life" }, { word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die or cease living" }] }
    ]
  }
}
