import { ChapterData } from "@/lib/bible-data"

export const genesisChapter42: ChapterData = {
  "Genesis-42": {
    book: "Genesis",
    chapter: 42,
    twoWordSummary: "Testing Brothers",
    themeSummary: "Joseph tests his brothers during their first journey to Egypt, imprisoning Simeon and demanding Benjamin's return.",
    sentenceDescription: "Joseph tests his brothers during their first journey to Egypt, imprisoning Simeon and demanding Benjamin's return.",
    themeWords: [
      { word: "Joseph", strongNumber: "H3130", language: "Hebrew", lemma: "Yoseph", meaning: "he will add; Joseph" },
      { word: "Egypt", strongNumber: "H4714", language: "Hebrew", lemma: "Mitsrayim", meaning: "Egypt" }
    ],
    verses: [
      { verse: 1, text: "Now when Jacob saw that there was corn in Egypt, Jacob said unto his sons, Why do ye look one upon another?", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqob", meaning: "heel-catcher; supplanter; Jacob" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 2, text: "And he said, Behold, I have heard that there is corn in Egypt: get you down thither, and buy for us from thence; that we may live, and not die.", highlightedWords: [{ word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }, { word: "die", strongNumber: "H4191", lemma: "muth", meaning: "to die" }] },
      { verse: 3, text: "And Joseph's ten brethren went down to buy corn in Egypt.", highlightedWords: [{ word: "Joseph's", strongNumber: "H3130", lemma: "Yoseph", meaning: "he will add; Joseph" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 4, text: "But Benjamin, Joseph's brother, Jacob sent not with his brethren; for he said, Lest peradventure mischief befall him.", highlightedWords: [{ word: "Benjamin", strongNumber: "H1144", lemma: "Binyamin", meaning: "son of the right hand; Benjamin" }, { word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqob", meaning: "heel-catcher; supplanter; Jacob" }] },
      { verse: 5, text: "And the sons of Israel came to buy corn among those that came: for the famine was in the land of Canaan.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives; Israel" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan; lowland" }] },
      { verse: 6, text: "And Joseph was the governor over the land, and he it was that sold to all the people of the land: and Joseph's brethren came, and bowed down themselves before him with their faces to the earth.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yoseph", meaning: "he will add; Joseph" }, { word: "land", strongNumber: "H776", lemma: "erets", meaning: "land, earth" }] },
      { verse: 7, text: "And Joseph saw his brethren, and he knew them, but made himself strange unto them, and spake roughly unto them; and he said unto them, Whence come ye? And they said, From the land of Canaan to buy food.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yoseph", meaning: "he will add; Joseph" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan; lowland" }] },
      { verse: 8, text: "And Joseph knew his brethren, but they knew not him.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yoseph", meaning: "he will add; Joseph" }, { word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brother, kinsman" }] },
      { verse: 9, text: "And Joseph remembered the dreams which he dreamed of them, and said unto them, Ye are spies; to see the nakedness of the land ye are come.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yoseph", meaning: "he will add; Joseph" }, { word: "land", strongNumber: "H776", lemma: "erets", meaning: "land, earth" }] },
      { verse: 10, text: "And they said unto him, Nay, my lord, but to buy food are thy servants come.", highlightedWords: [{ word: "lord", strongNumber: "H113", lemma: "adon/adonai", meaning: "lord, master" }, { word: "servants", strongNumber: "H5650", lemma: "ebed", meaning: "servant, slave" }] },
      { verse: 11, text: "We are all one man's sons; we are true men, thy servants are no spies.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son" }, { word: "servants", strongNumber: "H5650", lemma: "ebed", meaning: "servant, slave" }] },
      { verse: 12, text: "And he said unto them, Nay, but to see the nakedness of the land ye are come.", highlightedWords: [{ word: "nakedness", strongNumber: "H6172", lemma: "ervah", meaning: "nakedness, bareness" }, { word: "land", strongNumber: "H776", lemma: "erets", meaning: "land, earth" }] },
      { verse: 13, text: "And they said, Thy servants are twelve brethren, the sons of one man in the land of Canaan; and, behold, the youngest is this day with our father, and one is not.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan; lowland" }] },
      { verse: 14, text: "And Joseph said unto them, That is it that I spake unto you, saying, Ye are spies:", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yoseph", meaning: "he will add; Joseph" }, { word: "said", strongNumber: "H559", lemma: "amar", meaning: "to say" }] },
      { verse: 15, text: "Hereby ye shall be proved: By the life of Pharaoh ye shall not go forth hence, except your youngest brother come hither.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh" }, { word: "brother", strongNumber: "H251", lemma: "ach", meaning: "brother, kinsman" }] },
      { verse: 16, text: "Send one of you, and let him fetch your brother, and ye shall be kept in prison, that your words may be proved, whether there be any truth in you: or else by the life of Pharaoh surely ye are spies.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh" }, { word: "prison", strongNumber: "H4929", lemma: "mishmar", meaning: "guard, custody, prison" }] },
      { verse: 17, text: "And he put them all together into ward three days.", highlightedWords: [{ word: "ward", strongNumber: "H4929", lemma: "mishmar", meaning: "guard, custody, prison" }, { word: "three", strongNumber: "H7969", lemma: "shalosh", meaning: "three" }] },
      { verse: 18, text: "And Joseph said unto them the third day, This do, and live; for I fear God:", highlightedWords: [{ word: "third", strongNumber: "H7992", lemma: "shelishi", meaning: "third" }, { word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God" }] },
      { verse: 19, text: "If ye be true men, let one of your brethren be bound in the house of your prison: go ye, carry corn for the famine of your houses:", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brother, kinsman" }, { word: "prison", strongNumber: "H4929", lemma: "mishmar", meaning: "guard, custody, prison" }] },
      { verse: 20, text: "But bring your youngest brother unto me; so shall your words be verified, and ye shall not die. And they did so.", highlightedWords: [{ word: "brother", strongNumber: "H251", lemma: "ach", meaning: "brother, kinsman" }, { word: "die", strongNumber: "H4191", lemma: "muth", meaning: "to die" }] },
      { verse: 21, text: "And they said one to another, We are verily guilty concerning our brother, in that we saw the anguish of his soul, when he besought us, and we would not hear; therefore is this distress come upon us.", highlightedWords: [{ word: "brother", strongNumber: "H251", lemma: "ach", meaning: "brother, kinsman" }, { word: "soul", strongNumber: "H5315", lemma: "nephesh", meaning: "soul, life, person" }] },
      { verse: 22, text: "And Reuben answered them, saying, Spake I not unto you, saying, Do not sin against the child; and ye would not hear? therefore, behold, also his blood is required.", highlightedWords: [{ word: "Reuben", strongNumber: "H7205", lemma: "Re'uven", meaning: "behold, a son; Reuben" }, { word: "blood", strongNumber: "H1818", lemma: "dam", meaning: "blood" }] },
      { verse: 23, text: "And they knew not that Joseph understood them; for he spake unto them by an interpreter.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yoseph", meaning: "he will add; Joseph" }, { word: "understood", strongNumber: "H995", lemma: "bin", meaning: "to understand, perceive" }] },
      { verse: 24, text: "And he turned himself about from them, and wept; and returned to them again, and communed with them, and took from them Simeon, and bound him before their eyes.", highlightedWords: [{ word: "Simeon", strongNumber: "H8095", lemma: "Shim'on", meaning: "heard; Simeon" }, { word: "wept", strongNumber: "H1058", lemma: "bakah", meaning: "to weep" }] },
      { verse: 25, text: "Then Joseph commanded to fill their sacks with corn, and to restore every man's money into his sack, and to give them provision for the way: and thus did he unto them.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yoseph", meaning: "he will add; Joseph" }, { word: "money", strongNumber: "H3701", lemma: "keseph", meaning: "silver, money" }] },
      { verse: 26, text: "And they laded their asses with the corn, and departed thence.", highlightedWords: [{ word: "asses", strongNumber: "H2543", lemma: "chamor", meaning: "donkey" }, { word: "departed", strongNumber: "H3212", lemma: "yalak", meaning: "to go, walk, depart" }] },
      { verse: 27, text: "And as one of them opened his sack to give his ass provender in the inn, he espied his money; for, behold, it was in his sack's mouth.", highlightedWords: [{ word: "ass", strongNumber: "H2543", lemma: "chamor", meaning: "donkey" }, { word: "inn", strongNumber: "H4411", lemma: "malon", meaning: "lodging place, inn" }] },
      { verse: 28, text: "And he said unto his brethren, My money is restored; and, lo, it is even in my sack: and their heart failed them, and they were afraid, saying one to another, What is this that God hath done unto us?", highlightedWords: [{ word: "heart", strongNumber: "H3820", lemma: "lev", meaning: "heart, inner man" }, { word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God" }] },
      { verse: 29, text: "And they came unto Jacob their father unto the land of Canaan, and told him all that befell unto them; saying,", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqob", meaning: "heel-catcher; supplanter; Jacob" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan; lowland" }] },
      { verse: 30, text: "The man, who is the lord of the land, spake roughly to us, and took us for spies of the country.", highlightedWords: [{ word: "lord", strongNumber: "H113", lemma: "adon/adonai", meaning: "lord, master" }, { word: "land", strongNumber: "H776", lemma: "erets", meaning: "land, earth" }] },
      { verse: 31, text: "And we said unto him, We are true men; we are no spies:", highlightedWords: [{ word: "said", strongNumber: "H559", lemma: "amar", meaning: "to say" }, { word: "unto", strongNumber: "H413", lemma: "el", meaning: "to, toward" }] },
      { verse: 32, text: "We be twelve brethren, sons of our father; one is not, and the youngest is this day with our father in the land of Canaan.", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brother, kinsman" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan; lowland" }] },
      { verse: 33, text: "And the man, the lord of the country, said unto us, Hereby shall I know that ye are true men; leave one of your brethren here with me, and take food for the famine of your households, and be gone:", highlightedWords: [{ word: "lord", strongNumber: "H113", lemma: "adon/adonai", meaning: "lord, master" }, { word: "country", strongNumber: "H776", lemma: "erets", meaning: "land, country" }] },
      { verse: 34, text: "And bring your youngest brother unto me: then shall I know that ye are no spies, but that ye are true men: so will I deliver you your brother, and ye shall traffick in the land.", highlightedWords: [{ word: "brother", strongNumber: "H251", lemma: "ach", meaning: "brother, kinsman" }, { word: "land", strongNumber: "H776", lemma: "erets", meaning: "land, earth" }] },
      { verse: 35, text: "And it came to pass as they emptied their sacks, that, behold, every man's bundle of money was in his sack: and when both they and their father saw the bundles of money, they were afraid.", highlightedWords: [{ word: "money", strongNumber: "H3701", lemma: "keseph", meaning: "silver, money" }, { word: "father", strongNumber: "H1", lemma: "ab", meaning: "father" }] },
      { verse: 36, text: "And Jacob their father said unto them, Me have ye bereaved of my children: Joseph is not, and Simeon is not, and ye will take Benjamin away: all these things are against me.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yoseph", meaning: "he will add; Joseph" }, { word: "Benjamin", strongNumber: "H1144", lemma: "Binyamin", meaning: "son of the right hand; Benjamin" }] },
      { verse: 37, text: "And Reuben spake unto his father, saying, Slay my two sons, if I bring him not to thee: deliver him into my hand, and I will bring him to thee again.", highlightedWords: [{ word: "Reuben", strongNumber: "H7205", lemma: "Re'uven", meaning: "behold, a son; Reuben" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son" }] },
      { verse: 38, text: "And he said, My son shall not go down with you; for his brother is dead, and he is left alone: if mischief befall him by the way in the which ye go, then shall ye bring down my gray hairs with sorrow to the grave.", highlightedWords: [{ word: "gray hairs", strongNumber: "H7872", lemma: "seybah", meaning: "hoary head, gray hair" }, { word: "grave", strongNumber: "H6913", lemma: "qever", meaning: "grave, sepulcher" }] }
    ]
  }
}
