import { ChapterData } from "@/lib/bible-data"

export const genesisChapter37: ChapterData = {
  "Genesis-37": {
    book: "Genesis",
    chapter: 37,
    twoWordSummary: "Joseph Sold",
    themeSummary: "Joseph, favored by Jacob, dreams of preeminence, inciting his brothers' envy, who sell him into slavery while deceiving their father.",
    sentenceDescription: "Joseph, favored by Jacob, dreams of preeminence, inciting his brothers' envy, who sell him into slavery while deceiving their father.",
    themeWords: [
      { word: "Joseph", strongNumber: "H3130", language: "Hebrew", lemma: "Yosef", meaning: "he adds; Joseph" },
      { word: "Dream", strongNumber: "H2472", language: "Hebrew", lemma: "chalom", meaning: "a dream; vision during sleep" }
    ],
    verses: [
      { verse: 1, text: "And Jacob dwelt in the land wherein his father was a stranger, in the land of Canaan.", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqov", meaning: "Jacob; supplanter" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan; lowland; merchant" }] },
      { verse: 2, text: "These are the generations of Jacob. Joseph, being seventeen years old, was feeding the flock with his brethren; and the lad was with the sons of Bilhah, and with the sons of Zilpah, his father's wives: and Joseph brought unto his father their evil report.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "Joseph; he adds" }, { word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brothers; kinsmen" }] },
      { verse: 3, text: "Now Israel loved Joseph more than all his children, because he was the son of his old age: and he made him a coat of many colours.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; God strives/contends" }, { word: "coat", strongNumber: "H3801", lemma: "kethoneth", meaning: "tunic; coat" }] },
      { verse: 4, text: "And when his brethren saw that their father loved him more than all his brethren, they hated him, and could not speak peaceably unto him.", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brothers; kinsmen" }, { word: "hated", strongNumber: "H8130", lemma: "sane'", meaning: "to hate; be an enemy to" }] },
      { verse: 5, text: "And Joseph dreamed a dream, and he told it his brethren: and they hated him yet the more.", highlightedWords: [{ word: "dreamed", strongNumber: "H2492", lemma: "chalam", meaning: "to dream" }, { word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brothers; kinsmen" }] },
      { verse: 6, text: "And he said unto them, Hear, I pray you, this dream which I have dreamed:", highlightedWords: [{ word: "Hear", strongNumber: "H8085", lemma: "shama'", meaning: "to hear; listen; obey" }, { word: "dream", strongNumber: "H2472", lemma: "chalom", meaning: "a dream; vision during sleep" }] },
      { verse: 7, text: "For, behold, we were binding sheaves in the field, and, lo, my sheaf arose, and also stood upright; and, behold, your sheaves stood round about, and made obeisance to my sheaf.", highlightedWords: [{ word: "sheaf", strongNumber: "H485", lemma: "alumah", meaning: "a sheaf (bundle of grain)" }, { word: "obeisance", strongNumber: "H7812", lemma: "shachah", meaning: "to bow down; prostrate oneself" }] },
      { verse: 8, text: "And his brethren said to him, Shalt thou indeed reign over us? or shalt thou indeed have dominion over us? And they hated him yet the more for his dreams, and for his words.", highlightedWords: [{ word: "reign", strongNumber: "H4427", lemma: "malak", meaning: "to reign; be king" }, { word: "dominion", strongNumber: "H4910", lemma: "mashal", meaning: "to rule; have dominion" }] },
      { verse: 9, text: "And he dreamed yet another dream, and told it his brethren, and said, Behold, I have dreamed a dream more; and, behold, the sun and the moon and the eleven stars made obeisance to me.", highlightedWords: [{ word: "sun", strongNumber: "H8121", lemma: "shemesh", meaning: "the sun" }, { word: "stars", strongNumber: "H3556", lemma: "kokab", meaning: "stars" }] },
      { verse: 10, text: "And he told it to his father, and to his brethren: and his father rebuked him, and said unto him, What is this dream that thou hast dreamed? Shall I and thy mother and thy brethren indeed come to bow down ourselves to thee to the earth?", highlightedWords: [{ word: "father", strongNumber: "H1", lemma: "av", meaning: "father" }, { word: "rebuked", strongNumber: "H1605", lemma: "ga'ar", meaning: "to rebuke; reprove" }] },
      { verse: 11, text: "And his brethren envied him; but his father observed the saying.", highlightedWords: [{ word: "envied", strongNumber: "H7065", lemma: "qana'", meaning: "to be jealous; envy" }, { word: "observed", strongNumber: "H8104", lemma: "shamar", meaning: "to keep; guard; observe" }] },
      { verse: 12, text: "And his brethren went to feed their father's flock in Shechem.", highlightedWords: [{ word: "flock", strongNumber: "H6629", lemma: "tson", meaning: "flock; small livestock" }, { word: "Shechem", strongNumber: "H7927", lemma: "Shekhem", meaning: "Shechem (a city in Ephraim)" }] },
      { verse: 13, text: "And Israel said unto Joseph, Do not thy brethren feed the flock in Shechem? come, and I will send thee unto them. And he said to him, Here am I.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "Israel; God strives/contends" }, { word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "Joseph; he adds" }] },
      { verse: 14, text: "And he said to him, Go, I pray thee, see whether it be well with thy brethren, and well with the flocks; and bring me word again. So he sent him out of the vale of Hebron, and he came to Shechem.", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brothers; kinsmen" }, { word: "Hebron", strongNumber: "H2275", lemma: "Chebron", meaning: "Hebron" }] },
      { verse: 15, text: "And a certain man found him, and, behold, he was wandering in the field: and the man asked him, saying, What seekest thou?", highlightedWords: [{ word: "found", strongNumber: "H4672", lemma: "matsa'", meaning: "to find; come upon" }, { word: "seekest", strongNumber: "H1245", lemma: "baqash", meaning: "to seek; search for" }] },
      { verse: 16, text: "And he said, I seek my brethren: tell me, I pray thee, where they feed their flocks.", highlightedWords: [{ word: "seek", strongNumber: "H1245", lemma: "baqash", meaning: "to seek; search for" }, { word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brothers; kinsmen" }] },
      { verse: 17, text: "And the man said, They are departed hence; for I heard them say, Let us go to Dothan. And Joseph went after his brethren, and found them in Dothan.", highlightedWords: [{ word: "Dothan", strongNumber: "H1886", lemma: "Dothan", meaning: "Dothan (a place in Manasseh)" }, { word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "Joseph; he adds" }] },
      { verse: 18, text: "And when they saw him afar off, even before he came near unto them, they conspired against him to slay him.", highlightedWords: [{ word: "conspired", strongNumber: "H5230", lemma: "nakal", meaning: "to act craftily; conspire" }, { word: "slay", strongNumber: "H2026", lemma: "harag", meaning: "to kill; slay" }] },
      { verse: 19, text: "And they said one to another, Behold, this dreamer cometh.", highlightedWords: [{ word: "Behold", strongNumber: "H2009", lemma: "hinneh", meaning: "behold; look; see" }, { word: "cometh", strongNumber: "H935", lemma: "bo'", meaning: "to come; enter" }] },
      { verse: 20, text: "Come now therefore, and let us slay him, and cast him into some pit, and we will say, Some evil beast hath devoured him: and we shall see what will become of his dreams.", highlightedWords: [{ word: "pit", strongNumber: "H953", lemma: "bor", meaning: "pit; cistern; well" }, { word: "beast", strongNumber: "H2416", lemma: "chayyah", meaning: "living thing; animal; beast" }] },
      { verse: 21, text: "And Reuben heard it, and he delivered him out of their hands; and said, Let us not kill him.", highlightedWords: [{ word: "Reuben", strongNumber: "H7205", lemma: "Re'uven", meaning: "Reuben (Jacob's firstborn)" }, { word: "kill", strongNumber: "H5221", lemma: "nakah", meaning: "to strike; smite; kill" }] },
      { verse: 22, text: "And Reuben said unto them, Shed no blood, but cast him into this pit that is in the wilderness, and lay no hand upon him; that he might rid him out of their hands, to deliver him to his father again.", highlightedWords: [{ word: "blood", strongNumber: "H1818", lemma: "dam", meaning: "blood" }, { word: "wilderness", strongNumber: "H4057", lemma: "midbar", meaning: "wilderness; desert" }] },
      { verse: 23, text: "And it came to pass, when Joseph was come unto his brethren, that they stripped Joseph out of his coat, his coat of many colours that was on him;", highlightedWords: [{ word: "stripped", strongNumber: "H6584", lemma: "pashat", meaning: "to strip off; undress" }, { word: "coat", strongNumber: "H3801", lemma: "kethoneth", meaning: "tunic; coat" }] },
      { verse: 24, text: "And they took him, and cast him into a pit: and the pit was empty, there was no water in it.", highlightedWords: [{ word: "pit", strongNumber: "H953", lemma: "bor", meaning: "pit; cistern; well" }, { word: "water", strongNumber: "H4325", lemma: "mayim", meaning: "water; waters" }] },
      { verse: 25, text: "And they sat down to eat bread: and they lifted up their eyes and looked, and, behold, a company of Ishmeelites came from Gilead with their camels bearing spicery and balm and myrrh, going to carry it down to Egypt.", highlightedWords: [{ word: "Ishmeelites", strongNumber: "H3459", lemma: "Yishme'eli", meaning: "Ishmaelite; descendant of Ishmael" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 26, text: "And Judah said unto his brethren, What profit is it if we slay our brother, and conceal his blood?", highlightedWords: [{ word: "Judah", strongNumber: "H3063", lemma: "Yehudah", meaning: "Judah; praised" }, { word: "profit", strongNumber: "H1215", lemma: "betsa'", meaning: "unjust gain; profit" }] },
      { verse: 27, text: "Come, and let us sell him to the Ishmeelites, and let not our hand be upon him; for he is our brother and our flesh. And his brethren were content.", highlightedWords: [{ word: "sell", strongNumber: "H4376", lemma: "makar", meaning: "to sell" }, { word: "Ishmeelites", strongNumber: "H3459", lemma: "Yishme'eli", meaning: "Ishmaelite; descendant of Ishmael" }] },
      { verse: 28, text: "Then there passed by Midianites merchantmen; and they drew and lifted up Joseph out of the pit, and sold Joseph to the Ishmeelites for twenty pieces of silver: and they brought Joseph into Egypt.", highlightedWords: [{ word: "Midianites", strongNumber: "H4084", lemma: "Midyani", meaning: "Midianite; descendant of Midian" }, { word: "silver", strongNumber: "H3701", lemma: "keseph", meaning: "silver; money" }] },
      { verse: 29, text: "And Reuben returned unto the pit; and, behold, Joseph was not in the pit; and he rent his clothes.", highlightedWords: [{ word: "rent", strongNumber: "H7167", lemma: "qara'", meaning: "to tear; rend" }, { word: "clothes", strongNumber: "H899", lemma: "beged", meaning: "garment; clothing" }] },
      { verse: 30, text: "And he returned unto his brethren, and said, The child is not; and I, whither shall I go?", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brothers; kinsmen" }, { word: "child", strongNumber: "H3206", lemma: "yeled", meaning: "child; boy" }] },
      { verse: 31, text: "And they took Joseph's coat, and killed a kid of the goats, and dipped the coat in the blood;", highlightedWords: [{ word: "kid", strongNumber: "H5795", lemma: "gedi", meaning: "a kid (young goat)" }, { word: "blood", strongNumber: "H1818", lemma: "dam", meaning: "blood" }] },
      { verse: 32, text: "And they sent the coat of many colours, and they brought it to their father; and said, This have we found: know now whether it be thy son's coat or no.", highlightedWords: [{ word: "know", strongNumber: "H5234", lemma: "nakar", meaning: "to recognize; acknowledge" }, { word: "coat", strongNumber: "H3801", lemma: "kethoneth", meaning: "tunic; coat" }] },
      { verse: 33, text: "And he knew it, and said, It is my son's coat; an evil beast hath devoured him; Joseph is without doubt rent in pieces.", highlightedWords: [{ word: "beast", strongNumber: "H2416", lemma: "chayyah", meaning: "living thing; animal; beast" }, { word: "rent", strongNumber: "H2963", lemma: "taraph", meaning: "to tear; rend in pieces" }] },
      { verse: 34, text: "And Jacob rent his clothes, and put sackcloth upon his loins, and mourned for his son many days.", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqov", meaning: "Jacob; supplanter" }, { word: "sackcloth", strongNumber: "H8242", lemma: "saq", meaning: "sackcloth" }] },
      { verse: 35, text: "And all his sons and all his daughters rose up to comfort him; but he refused to be comforted; and he said, For I will go down into the grave unto my son mourning. Thus his father wept for him.", highlightedWords: [{ word: "grave", strongNumber: "H7585", lemma: "she'ol", meaning: "Sheol; the grave; the realm of the dead" }, { word: "wept", strongNumber: "H1058", lemma: "bakah", meaning: "to weep; lament" }] },
      { verse: 36, text: "And the Midianites sold him into Egypt unto Potiphar, an officer of Pharaoh's, and captain of the guard.", highlightedWords: [{ word: "Potiphar", strongNumber: "H6318", lemma: "Potiphar", meaning: "Potiphar, an Egyptian officer" }, { word: "captain", strongNumber: "H8269", lemma: "sar", meaning: "chief; prince; captain" }] }
    ]
  }
}
