import { ChapterData } from "@/lib/bible-data"

export const genesisChapter5: ChapterData = {
  "Genesis-5": {
    book: "Genesis",
    chapter: 5,
    twoWordSummary: "Adam's Lineage",
    themeSummary: "The genealogy from Adam to Noah records the generations of early humanity, highlighting long lifespans and the continued spread of mankind after the creation.",
    sentenceDescription: "The genealogical account documents the descendants of Adam through Seth, spanning from creation to Noah, with Enoch's faithful walk with God and his translation to heaven.",
    themeWords: [
      { word: "generations", strongNumber: "H8435", lemma: "toledoth", meaning: "genealogies; historical records" },
      { word: "lineage", strongNumber: "H3205", lemma: "yalad", meaning: "to bring forth; establish descent" }
    ],
    verses: [
      { verse: 1, text: "This is the book of the generations of Adam. In the day that God created man, in the likeness of God made he him;", highlightedWords: [{ word: "generations", strongNumber: "H8435", lemma: "toledoth", meaning: "genealogies; historical records" }, { word: "likeness", strongNumber: "H1823", lemma: "demuth", meaning: "likeness; resemblance" }] },
      { verse: 2, text: "Male and female created he them; and blessed them, and called their name Adam, in the day when they were created.", highlightedWords: [{ word: "blessed", strongNumber: "H1288", lemma: "barak", meaning: "to bless; endow with favor" }, { word: "Adam", strongNumber: "H120", lemma: "adam", meaning: "man; mankind" }] },
      { verse: 3, text: "And Adam lived an hundred and thirty years, and begat a son in his own likeness, after his image; and called his name Seth:", highlightedWords: [{ word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bear; bring forth children" }, { word: "Seth", strongNumber: "H8352", lemma: "Shet", meaning: "appointed; placed" }] },
      { verse: 4, text: "And the days of Adam after he had begotten Seth were eight hundred years: and he begat sons and daughters:", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }, { word: "daughters", strongNumber: "H1323", lemma: "bath", meaning: "daughter; female child" }] },
      { verse: 5, text: "And all the days that Adam lived were nine hundred and thirty years: and he died.", highlightedWords: [{ word: "lived", strongNumber: "H2421", lemma: "chayah", meaning: "to live; remain alive" }, { word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die; death" }] },
      { verse: 6, text: "And Seth lived an hundred and five years, and begat Enos:", highlightedWords: [{ word: "lived", strongNumber: "H2421", lemma: "chayah", meaning: "to live; be alive" }, { word: "Enos", strongNumber: "H583", lemma: "Enosh", meaning: "man; mortal man" }] },
      { verse: 7, text: "And Seth lived after he begat Enos eight hundred and seven years, and begat sons and daughters:", highlightedWords: [{ word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bear children" }, { word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "year; cycle of time" }] },
      { verse: 8, text: "And all the days of Seth were nine hundred and twelve years: and he died.", highlightedWords: [{ word: "days", strongNumber: "H3117", lemma: "yom", meaning: "day; lifetime period" }, { word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die; death" }] },
      { verse: 9, text: "And Enos lived ninety years, and begat Cainan:", highlightedWords: [{ word: "lived", strongNumber: "H2421", lemma: "chayah", meaning: "to live; be alive" }, { word: "Cainan", strongNumber: "H7018", lemma: "Qenan", meaning: "possession; acquisition" }] },
      { verse: 10, text: "And Enos lived after he begat Cainan eight hundred and fifteen years, and begat sons and daughters:", highlightedWords: [{ word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bear children" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "sons; descendants" }] },
      { verse: 11, text: "And all the days of Enos were nine hundred and five years: and he died.", highlightedWords: [{ word: "days", strongNumber: "H3117", lemma: "yom", meaning: "days; lifetime" }, { word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die" }] },
      { verse: 12, text: "And Cainan lived seventy years, and begat Mahalaleel:", highlightedWords: [{ word: "lived", strongNumber: "H2421", lemma: "chayah", meaning: "to live" }, { word: "Mahalaleel", strongNumber: "H4111", lemma: "Mahalalel", meaning: "praise of God" }] },
      { verse: 13, text: "And Cainan lived after he begat Mahalaleel eight hundred and forty years, and begat sons and daughters:", highlightedWords: [{ word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bear children" }, { word: "daughters", strongNumber: "H1323", lemma: "bath", meaning: "daughters" }] },
      { verse: 14, text: "And all the days of Cainan were nine hundred and ten years: and he died.", highlightedWords: [{ word: "days", strongNumber: "H3117", lemma: "yom", meaning: "days; lifetime" }, { word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die" }] },
      { verse: 15, text: "And Mahalaleel lived sixty and five years, and begat Jared:", highlightedWords: [{ word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bear children" }, { word: "Jared", strongNumber: "H3382", lemma: "Yered", meaning: "descent; coming down" }] },
      { verse: 16, text: "And Mahalaleel lived after he begat Jared eight hundred and thirty years, and begat sons and daughters:", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "sons; descendants" }, { word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "years; time cycle" }] },
      { verse: 17, text: "And all the days of Mahalaleel were eight hundred ninety and five years: and he died.", highlightedWords: [{ word: "days", strongNumber: "H3117", lemma: "yom", meaning: "days; lifetime" }, { word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die" }] },
      { verse: 18, text: "And Jared lived an hundred sixty and two years, and he begat Enoch:", highlightedWords: [{ word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bear children" }, { word: "Enoch", strongNumber: "H2585", lemma: "Chanok", meaning: "dedicated; initiated" }] },
      { verse: 19, text: "And Jared lived after he begat Enoch eight hundred years, and begat sons and daughters:", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "sons; descendants" }, { word: "daughters", strongNumber: "H1323", lemma: "bath", meaning: "daughters" }] },
      { verse: 20, text: "And all the days of Jared were nine hundred sixty and two years: and he died.", highlightedWords: [{ word: "days", strongNumber: "H3117", lemma: "yom", meaning: "days; lifetime" }, { word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die" }] },
      { verse: 21, text: "And Enoch lived sixty and five years, and begat Methuselah:", highlightedWords: [{ word: "Enoch", strongNumber: "H2585", lemma: "Chanok", meaning: "dedicated one" }, { word: "Methuselah", strongNumber: "H4968", lemma: "Methushelach", meaning: "man of the dart; when he dies it shall come" }] },
      { verse: 22, text: "And Enoch walked with God after he begat Methuselah three hundred years, and begat sons and daughters:", highlightedWords: [{ word: "walked", strongNumber: "H1980", lemma: "halak", meaning: "to walk; live; conduct life" }, { word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; divine being" }] },
      { verse: 23, text: "And all the days of Enoch were three hundred sixty and five years:", highlightedWords: [{ word: "days", strongNumber: "H3117", lemma: "yom", meaning: "days; lifetime" }, { word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "years; time cycle" }] },
      { verse: 24, text: "And Enoch walked with God: and he was not; for God took him.", highlightedWords: [{ word: "walked", strongNumber: "H1980", lemma: "halak", meaning: "to walk; live faithfully" }, { word: "took", strongNumber: "H3947", lemma: "laqach", meaning: "to take; receive; carry away" }] },
      { verse: 25, text: "And Methuselah lived an hundred eighty and seven years, and begat Lamech:", highlightedWords: [{ word: "lived", strongNumber: "H2421", lemma: "chayah", meaning: "to live; remain alive" }, { word: "Lamech", strongNumber: "H3929", lemma: "Lemek", meaning: "powerful; strong youth" }] },
      { verse: 26, text: "And Methuselah lived after he begat Lamech seven hundred eighty and two years, and begat sons and daughters:", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "sons; descendants" }, { word: "years", strongNumber: "H8141", lemma: "shanah", meaning: "years; time cycle" }] },
      { verse: 27, text: "And all the days of Methuselah were nine hundred sixty and nine years: and he died.", highlightedWords: [{ word: "days", strongNumber: "H3117", lemma: "yom", meaning: "days; lifetime" }, { word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die" }] },
      { verse: 28, text: "And Lamech lived an hundred eighty and two years, and begat a son:", highlightedWords: [{ word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bear children" }, { word: "son", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 29, text: "And he called his name Noah, saying, This same shall comfort us concerning our work and toil of our hands, because of the ground which the LORD hath cursed.", highlightedWords: [{ word: "Noah", strongNumber: "H5146", lemma: "Noach", meaning: "rest; comfort" }, { word: "comfort", strongNumber: "H5162", lemma: "nacham", meaning: "to comfort; bring relief" }] },
      { verse: 30, text: "And Lamech lived after he begat Noah five hundred ninety and five years, and begat sons and daughters:", highlightedWords: [{ word: "Noah", strongNumber: "H5146", lemma: "Noach", meaning: "rest; comfort" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "sons; descendants" }] },
      { verse: 31, text: "And all the days of Lamech were seven hundred seventy and seven years: and he died.", highlightedWords: [{ word: "days", strongNumber: "H3117", lemma: "yom", meaning: "days; lifetime" }, { word: "died", strongNumber: "H4191", lemma: "muth", meaning: "to die" }] },
      { verse: 32, text: "And Noah was five hundred years old: and Noah begat Shem, Ham, and Japheth.", highlightedWords: [{ word: "Noah", strongNumber: "H5146", lemma: "Noach", meaning: "rest; comfort" }, { word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bear children" }] },
    ]
  }
}
