import { ChapterData } from "@/lib/bible-data"

export const genesisChapter46: ChapterData = {
  "Genesis-46": {
    book: "Genesis",
    chapter: 46,
    twoWordSummary: "Family Migration",
    themeSummary: "Jacob (Israel) journeys to Egypt at God's direction, the family register of those who went down is recorded, and Joseph prepares for their dwelling in Goshen.",
    sentenceDescription: "Jacob journeys to Egypt with God's assurance, bringing his entire household. The chapter records the genealogy of all seventy souls who descended into Egypt, and details Joseph's arrangement for the family to settle in Goshen.",
    themeWords: [
      { word: "Egypt", strongNumber: "H4714", language: "Hebrew", lemma: "Mitsrayim", meaning: "Egypt" },
      { word: "Goshen", strongNumber: "H1657", language: "Hebrew", lemma: "Goshen", meaning: "region in Egypt where Israel settled" }
    ],
    verses: [
      { verse: 1, text: "And Israel took his journey with all that he had, and came to Beer-sheba, and offered sacrifices unto the God of his father Isaac.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives" }, { word: "Beer-sheba", strongNumber: "H884", lemma: "Be'er Sheba'", meaning: "well of the oath" }] },
      { verse: 2, text: "And God spake unto Israel in the visions of the night, and said, Jacob, Jacob. And he said, Here am I.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives" }] },
      { verse: 3, text: "And he said, I am God, the God of thy father: fear not to go down into Egypt; for I will there make of thee a great nation:", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 4, text: "I will go down with thee into Egypt; and I will also surely bring thee up again: and Joseph shall put his hand upon thine eyes.", highlightedWords: [{ word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }, { word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }] },
      { verse: 5, text: "And Jacob rose up from Beer-sheba: and the sons of Israel carried Jacob their father, and their little ones, and their wives, in the wagons which Pharaoh had sent to carry him.", highlightedWords: [{ word: "Jacob", strongNumber: "H3290", lemma: "Ya'aqob", meaning: "supplanter" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh; great house" }] },
      { verse: 6, text: "And they took their cattle, and their goods, which they had gotten in the land of Canaan, and came into Egypt, Jacob, and all his seed with him:", highlightedWords: [{ word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 7, text: "His sons, and his sons' sons with him, his daughters, and his sons' daughters, and all his seed brought he with him into Egypt.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }, { word: "daughters", strongNumber: "H1323", lemma: "bath", meaning: "daughter" }] },
      { verse: 8, text: "And these are the names of the children of Israel, which came into Egypt, Jacob and his sons: Reuben, Jacob's firstborn.", highlightedWords: [{ word: "names", strongNumber: "H8034", lemma: "shem", meaning: "name" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives" }] },
      { verse: 9, text: "And the sons of Reuben; Hanoch, and Phallu, and Hezron, and Carmi.", highlightedWords: [{ word: "Reuben", strongNumber: "H7205", lemma: "Re'uven", meaning: "behold, a son" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 10, text: "And the sons of Simeon; Jemuel, and Jamin, and Ohad, and Jachin, and Zohar, and Shaul the son of a Canaanitish woman.", highlightedWords: [{ word: "Simeon", strongNumber: "H8095", lemma: "Shim'on", meaning: "heard" }, { word: "Canaanitish", strongNumber: "H3669", lemma: "Kena'anith", meaning: "Canaanite (woman)" }] },
      { verse: 11, text: "And the sons of Levi; Gershon, Kohath, and Merari.", highlightedWords: [{ word: "Levi", strongNumber: "H3878", lemma: "Lewi", meaning: "joined" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 12, text: "And the sons of Judah; Er, and Onan, and Shelah, and Pharez, and Zarah: but Er and Onan died in the land of Canaan. And the sons of Pharez were Hezron and Hamul.", highlightedWords: [{ word: "Judah", strongNumber: "H3063", lemma: "Yehudah", meaning: "praise" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan" }] },
      { verse: 13, text: "And the sons of Issachar; Tola, and Phuvah, and Job, and Shimron.", highlightedWords: [{ word: "Issachar", strongNumber: "H3485", lemma: "Yissaskar", meaning: "there is recompense" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 14, text: "And the sons of Zebulun; Sered, and Elon, and Jahleel.", highlightedWords: [{ word: "Zebulun", strongNumber: "H2074", lemma: "Zebulun", meaning: "dwelling; exalted" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 15, text: "These be the sons of Leah, which she bare unto Jacob in Padan-aram, with his daughter Dinah: all the souls of his sons and his daughters were thirty and three.", highlightedWords: [{ word: "Leah", strongNumber: "H3812", lemma: "Le'ah", meaning: "weary" }, { word: "souls", strongNumber: "H5315", lemma: "nephesh", meaning: "soul; life" }] },
      { verse: 16, text: "And the sons of Gad; Ziphion, and Haggi, Shuni, and Ezbon, Eri, and Arodi, and Areli.", highlightedWords: [{ word: "Gad", strongNumber: "H1410", lemma: "Gad", meaning: "troop; fortune" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 17, text: "And the sons of Asher; Jimnah, and Ishuah, and Isui, and Beriah, and Serah their sister: and the sons of Beriah; Heber, and Malchiel.", highlightedWords: [{ word: "Asher", strongNumber: "H836", lemma: "Asher", meaning: "happy; blessed" }, { word: "sister", strongNumber: "H269", lemma: "achoth", meaning: "sister" }] },
      { verse: 18, text: "These are the sons of Zilpah, whom Laban gave to Leah his daughter, and these she bare unto Jacob, even sixteen souls.", highlightedWords: [{ word: "Zilpah", strongNumber: "H2153", lemma: "Zilpah", meaning: "Zilpah" }, { word: "souls", strongNumber: "H5315", lemma: "nephesh", meaning: "soul; life" }] },
      { verse: 19, text: "The sons of Rachel Jacob's wife; Joseph, and Benjamin.", highlightedWords: [{ word: "Rachel", strongNumber: "H7354", lemma: "Rachel", meaning: "ewe" }, { word: "Benjamin", strongNumber: "H1144", lemma: "Binyamin", meaning: "son of the right hand" }] },
      { verse: 20, text: "And unto Joseph in the land of Egypt were born Manasseh and Ephraim, which Asenath the daughter of Poti-pherah priest of On bare unto him.", highlightedWords: [{ word: "Manasseh", strongNumber: "H4519", lemma: "Mĕnashsheh", meaning: "causing to forget" }, { word: "Ephraim", strongNumber: "H669", lemma: "Ephrayim", meaning: "fruitful" }] },
      { verse: 21, text: "And the sons of Benjamin were Belah, and Becher, and Ashbel, Gera, and Naaman, Ehi, and Rosh, Muppim, and Huppim, and Ard.", highlightedWords: [{ word: "Benjamin", strongNumber: "H1144", lemma: "Binyamin", meaning: "son of the right hand" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 22, text: "These are the sons of Rachel, which were born to Jacob: all the souls were fourteen.", highlightedWords: [{ word: "Rachel", strongNumber: "H7354", lemma: "Rachel", meaning: "ewe" }, { word: "souls", strongNumber: "H5315", lemma: "nephesh", meaning: "soul; life" }] },
      { verse: 23, text: "And the sons of Dan; Hushim.", highlightedWords: [{ word: "Dan", strongNumber: "H1835", lemma: "Dan", meaning: "judge" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 24, text: "And the sons of Naphtali; Jahzeel, and Guni, and Jezer, and Shillem.", highlightedWords: [{ word: "Naphtali", strongNumber: "H5321", lemma: "Naphtali", meaning: "my wrestling" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "son; descendant" }] },
      { verse: 25, text: "These are the sons of Bilhah, which Laban gave unto Rachel his daughter, and she bare these unto Jacob: all the souls were seven.", highlightedWords: [{ word: "Bilhah", strongNumber: "H1090", lemma: "Bilhah", meaning: "Bilhah" }, { word: "souls", strongNumber: "H5315", lemma: "nephesh", meaning: "soul; life" }] },
      { verse: 26, text: "All the souls that came with Jacob into Egypt, which came out of his loins, besides Jacob's sons' wives, all the souls were threescore and six;", highlightedWords: [{ word: "souls", strongNumber: "H5315", lemma: "nephesh", meaning: "soul; life" }, { word: "loins", strongNumber: "H4975", lemma: "mothen", meaning: "loins" }] },
      { verse: 27, text: "And the sons of Joseph, which were born him in Egypt, were two souls: all the souls of the house of Jacob, which came into Egypt, were threescore and ten.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "house", strongNumber: "H1004", lemma: "bayith", meaning: "house" }] },
      { verse: 28, text: "And he sent Judah before him unto Joseph, to direct his face unto Goshen; and they came into the land of Goshen.", highlightedWords: [{ word: "Judah", strongNumber: "H3063", lemma: "Yehudah", meaning: "praise" }, { word: "Goshen", strongNumber: "H1657", lemma: "Goshen", meaning: "region in Egypt where Israel settled" }] },
      { verse: 29, text: "And Joseph made ready his chariot, and went up to meet Israel his father, to Goshen, and presented himself unto him; and he fell on his neck, and wept on his neck a good while.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives" }] },
      { verse: 30, text: "And Israel said unto Joseph, Now let me die, since I have seen thy face, because thou art yet alive.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisra'el", meaning: "God strives" }, { word: "alive", strongNumber: "H2416", lemma: "chay", meaning: "living; alive" }] },
      { verse: 31, text: "And Joseph said unto his brethren, and unto his father's house, I will go up, and shew Pharaoh, and say unto him, My brethren, and my father's house, which were in the land of Canaan, are come unto me;", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brothers; kinsmen" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh; great house" }] },
      { verse: 32, text: "And the men are shepherds, for their trade hath been to feed cattle; and they have brought their flocks, and their herds, and all that they have.", highlightedWords: [{ word: "shepherds", strongNumber: "H7462", lemma: "ro'eh", meaning: "shepherd; herdsman" }, { word: "flocks", strongNumber: "H6629", lemma: "tson", meaning: "small livestock; flock" }] },
      { verse: 33, text: "And it shall come to pass, when Pharaoh shall call you, and shall say, What is your occupation?", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Par'oh", meaning: "Pharaoh; great house" }, { word: "call", strongNumber: "H7121", lemma: "qara'", meaning: "to call; summon" }] },
      { verse: 34, text: "That ye shall say, Thy servants' trade hath been about cattle from our youth even until now, both we, and also our fathers: that ye may dwell in the land of Goshen; for every shepherd is an abomination unto the Egyptians.", highlightedWords: [{ word: "Goshen", strongNumber: "H1657", lemma: "Goshen", meaning: "region in Egypt where Israel settled" }, { word: "abomination", strongNumber: "H8441", lemma: "to'evah", meaning: "abomination; detestable thing" }] }
    ]
  }
}
