import { ChapterData } from "@/lib/bible-data"

export const genesisChapter6: ChapterData = {
  "Genesis-6": {
    book: "Genesis",
    chapter: 6,
    twoWordSummary: "Corrupt Earth",
    themeSummary: "The narrative describes escalating human wickedness and corruption filling the earth, God's grief over creation, His judgment to destroy mankind through a flood, yet His mercy toward Noah and command to build the ark.",
    sentenceDescription: "Human corruption and violence provoke God's judgment, yet He extends grace to righteous Noah, commanding him to build an ark for salvation while all other flesh faces destruction.",
    themeWords: [
      { word: "Corrupt", strongNumber: "H7843", lemma: "shachath", meaning: "to ruin, corrupt, destroy morally" },
      { word: "Earth", strongNumber: "H776", lemma: "erets", meaning: "earth, land, ground, world" }
    ],
    verses: [
      { verse: 1, text: "And it came to pass, when men began to multiply on the face of the earth, and daughters were born unto them,", highlightedWords: [{ word: "multiply", strongNumber: "H7235", lemma: "rabah", meaning: "to increase greatly, multiply" }, { word: "earth", strongNumber: "H127", lemma: "adamah", meaning: "ground, soil, earth" }] },
      { verse: 2, text: "That the sons of God saw the daughters of men that they were fair; and they took them wives of all which they chose.", highlightedWords: [{ word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "sons; descendants" }, { word: "wives", strongNumber: "H802", lemma: "ishshah", meaning: "woman; wife" }] },
      { verse: 3, text: "And the LORD said, My spirit shall not always strive with man, for that he also is flesh: yet his days shall be an hundred and twenty years.", highlightedWords: [{ word: "spirit", strongNumber: "H7307", lemma: "ruach", meaning: "spirit; breath; life-force" }, { word: "strive", strongNumber: "H1777", lemma: "din", meaning: "to judge; contend; plead a cause" }] },
      { verse: 4, text: "There were giants in the earth in those days; and also after that, when the sons of God came in unto the daughters of men, and they bare children to them the same became mighty men which were of old men of renown.", highlightedWords: [{ word: "giants", strongNumber: "H5303", lemma: "nephilim", meaning: "fallen ones; giants" }, { word: "mighty", strongNumber: "H1368", lemma: "gibbor", meaning: "mighty man; warrior; champion" }] },
      { verse: 5, text: "And GOD saw that the wickedness of man was great in the earth and that every imagination of the thoughts of his heart was only evil continually.", highlightedWords: [{ word: "wickedness", strongNumber: "H7451", lemma: "ra", meaning: "evil; wickedness" }, { word: "imagination", strongNumber: "H3336", lemma: "yetser", meaning: "formation; intention; imagination" }] },
      { verse: 6, text: "And it repented the LORD that he had made man on the earth and it grieved him at his heart.", highlightedWords: [{ word: "repented", strongNumber: "H5162", lemma: "nacham", meaning: "to be sorry; regret; relent" }, { word: "grieved", strongNumber: "H6087", lemma: "atsab", meaning: "to grieve; pain; distress" }] },
      { verse: 7, text: "And the LORD said I will destroy man whom I have created from the face of the earth both man and beast and the creeping thing and the fowls of the air for it repenteth me that I have made them.", highlightedWords: [{ word: "destroy", strongNumber: "H4229", lemma: "machah", meaning: "to blot out; wipe away" }, { word: "created", strongNumber: "H1254", lemma: "bara", meaning: "to create; shape by divine act" }] },
      { verse: 8, text: "But Noah found grace in the eyes of the LORD.", highlightedWords: [{ word: "grace", strongNumber: "H2580", lemma: "chen", meaning: "favor; grace; kindness" }, { word: "Noah", strongNumber: "H5146", lemma: "Noach", meaning: "rest; comfort" }] },
      { verse: 9, text: "These are the generations of Noah Noah was a just man and perfect in his generations and Noah walked with God.", highlightedWords: [{ word: "just", strongNumber: "H6662", lemma: "tsaddiq", meaning: "righteous; just person" }, { word: "walked", strongNumber: "H1980", lemma: "halak", meaning: "to walk; live; conduct life" }] },
      { verse: 10, text: "And Noah begat three sons Shem Ham and Japheth.", highlightedWords: [{ word: "begat", strongNumber: "H3205", lemma: "yalad", meaning: "to bear children" }, { word: "sons", strongNumber: "H1121", lemma: "ben", meaning: "sons; descendants" }] },
      { verse: 11, text: "The earth also was corrupt before God and the earth was filled with violence.", highlightedWords: [{ word: "corrupt", strongNumber: "H7843", lemma: "shachath", meaning: "to corrupt; ruin morally" }, { word: "violence", strongNumber: "H2555", lemma: "chamas", meaning: "violence; injustice; cruelty" }] },
      { verse: 12, text: "And God looked upon the earth and behold it was corrupt for all flesh had corrupted his way upon the earth.", highlightedWords: [{ word: "flesh", strongNumber: "H1320", lemma: "basar", meaning: "flesh; living beings" }, { word: "way", strongNumber: "H1870", lemma: "derek", meaning: "way; path; conduct" }] },
      { verse: 13, text: "And God said unto Noah The end of all flesh is come before me for the earth is filled with violence through them and behold I will destroy them with the earth.", highlightedWords: [{ word: "end", strongNumber: "H7093", lemma: "qets", meaning: "end; termination" }, { word: "destroy", strongNumber: "H7843", lemma: "shachath", meaning: "to destroy; ruin" }] },
      { verse: 14, text: "Make thee an ark of gopher wood rooms shalt thou make in the ark and shalt pitch it within and without with pitch.", highlightedWords: [{ word: "ark", strongNumber: "H8392", lemma: "tebah", meaning: "ark; chest; vessel" }, { word: "pitch", strongNumber: "H3724", lemma: "kopher", meaning: "pitch; covering substance" }] },
      { verse: 15, text: "And this is the fashion which thou shalt make it of The length of the ark shall be three hundred cubits the breadth of it fifty cubits and the height of it thirty cubits.", highlightedWords: [{ word: "cubits", strongNumber: "H520", lemma: "ammah", meaning: "cubit; ancient length measurement" }, { word: "length", strongNumber: "H753", lemma: "orek", meaning: "length; extension" }] },
      { verse: 16, text: "A window shalt thou make to the ark and in a cubit shalt thou finish it above and the door of the ark shalt thou set in the side thereof with lower second and third stories shalt thou make it.", highlightedWords: [{ word: "window", strongNumber: "H6672", lemma: "tsohar", meaning: "roof opening; window" }, { word: "door", strongNumber: "H6607", lemma: "pethach", meaning: "doorway; entrance" }] },
      { verse: 17, text: "And behold I even I do bring a flood of waters upon the earth to destroy all flesh wherein is the breath of life from under heaven and every thing that is in the earth shall die.", highlightedWords: [{ word: "flood", strongNumber: "H3999", lemma: "mabbul", meaning: "deluge; flood" }, { word: "breath", strongNumber: "H7307", lemma: "ruach", meaning: "breath; spirit of life" }] },
      { verse: 18, text: "But with thee will I establish my covenant and thou shalt come into the ark thou and thy sons and thy wife and thy sons wives with thee.", highlightedWords: [{ word: "covenant", strongNumber: "H1285", lemma: "berith", meaning: "covenant; binding agreement" }, { word: "ark", strongNumber: "H8392", lemma: "tebah", meaning: "ark; vessel of preservation" }] },
      { verse: 19, text: "And of every living thing of all flesh two of every sort shalt thou bring into the ark to keep them alive with thee they shall be male and female.", highlightedWords: [{ word: "living", strongNumber: "H2416", lemma: "chay", meaning: "living; alive" }, { word: "sort", strongNumber: "H4327", lemma: "min", meaning: "kind; species" }] },
      { verse: 20, text: "Of fowls after their kind and of cattle after their kind of every creeping thing of the earth after his kind two of every sort shall come unto thee to keep them alive.", highlightedWords: [{ word: "fowls", strongNumber: "H5775", lemma: "oph", meaning: "bird; flying creature" }, { word: "cattle", strongNumber: "H929", lemma: "behemah", meaning: "beast; livestock animal" }] },
      { verse: 21, text: "And take thou unto thee of all food that is eaten and thou shalt gather it to thee and it shall be for food for thee and for them.", highlightedWords: [{ word: "food", strongNumber: "H400", lemma: "oklah", meaning: "food; nourishment" }, { word: "gather", strongNumber: "H622", lemma: "asaph", meaning: "to gather; collect" }] },
      { verse: 22, text: "Thus did Noah according to all that God commanded him so did he.", highlightedWords: [{ word: "commanded", strongNumber: "H6680", lemma: "tsavah", meaning: "to command; give instruction" }, { word: "Noah", strongNumber: "H5146", lemma: "Noach", meaning: "rest; comfort" }] },
    ]
  }
}
