import { ChapterData } from "@/lib/bible-data"

export const genesisChapter45: ChapterData = {
  "Genesis-45": {
    book: "Genesis",
    chapter: 45,
    twoWordSummary: "Joseph Revealed",
    themeSummary: "Joseph reveals himself to his brothers, explains God's providence in sending him ahead to preserve life, and invites Jacob's household to settle in Egypt.",
    sentenceDescription: "Joseph reveals himself to his brothers, explains God's providence in sending him ahead to preserve life, and invites Jacob's household to settle in Egypt.",
    themeWords: [
      { word: "Joseph", strongNumber: "H3130", language: "Hebrew", lemma: "Yosef", meaning: "he will add" },
      { word: "God", strongNumber: "H430", language: "Hebrew", lemma: "Elohim", meaning: "God; the mighty one" }
    ],
    verses: [
      { verse: 1, text: "Then Joseph could not refrain himself before all them that stood by him; and he cried, Cause every man to go out from me. And there stood no man with him, while Joseph made himself known unto his brethren.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brother; kinsman" }] },
      { verse: 2, text: "And he wept aloud: and the Egyptians and the house of Pharaoh heard.", highlightedWords: [{ word: "wept", strongNumber: "H1058", lemma: "bakah", meaning: "to weep; lament" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "Pharaoh; Egyptian king" }] },
      { verse: 3, text: "And Joseph said unto his brethren, I am Joseph; doth my father yet live? And his brethren could not answer him; for they were troubled at his presence.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "father", strongNumber: "H1", lemma: "ab", meaning: "father; ancestor" }] },
      { verse: 4, text: "And Joseph said unto his brethren, Come near to me, I pray you. And they came near. And he said, I am Joseph your brother, whom ye sold into Egypt.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 5, text: "Now therefore be not grieved, nor angry with yourselves, that ye sold me hither: for God did send me before you to preserve life.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; the mighty one" }, { word: "send", strongNumber: "H7971", lemma: "shalach", meaning: "to send; dispatch" }] },
      { verse: 6, text: "For these two years hath the famine been in the land: and yet there are five years, in the which there shall neither be earing nor harvest.", highlightedWords: [{ word: "famine", strongNumber: "H7458", lemma: "ra'av", meaning: "famine; hunger" }, { word: "land", strongNumber: "H776", lemma: "erets", meaning: "land; earth" }] },
      { verse: 7, text: "And God sent me before you to preserve you a posterity in the earth, and to save your lives by a great deliverance.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; the mighty one" }, { word: "earth", strongNumber: "H776", lemma: "erets", meaning: "land; earth" }] },
      { verse: 8, text: "So now it was not you that sent me hither, but God: and he hath made me a father to Pharaoh, and lord of all his house, and a ruler throughout all the land of Egypt.", highlightedWords: [{ word: "God", strongNumber: "H430", lemma: "Elohim", meaning: "God; the mighty one" }, { word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "Pharaoh; Egyptian king" }] },
      { verse: 9, text: "Haste ye, and go up to my father, and say unto him, Thus saith thy son Joseph, God hath made me lord of all Egypt: come down unto me, tarry not:", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 10, text: "And thou shalt dwell in the land of Goshen, and thou shalt be near unto me, thou, and thy children, and thy children's children, and thy flocks, and thy herds, and all that thou hast:", highlightedWords: [{ word: "Goshen", strongNumber: "H1657", lemma: "Goshen", meaning: "region in Egypt given to Israel" }, { word: "children", strongNumber: "H1121", lemma: "ben", meaning: "son; child; descendant" }] },
      { verse: 11, text: "And there will I nourish thee; for yet there are five years of famine; lest thou, and thy household, and all that thou hast, come to poverty.", highlightedWords: [{ word: "famine", strongNumber: "H7458", lemma: "ra'av", meaning: "famine; hunger" }, { word: "household", strongNumber: "H1004", lemma: "bayith", meaning: "house; household; family" }] },
      { verse: 12, text: "And, behold, your eyes see, and the eyes of my brother Benjamin, that it is my mouth that speaketh unto you.", highlightedWords: [{ word: "eyes", strongNumber: "H5869", lemma: "ayin", meaning: "eye; sight" }, { word: "mouth", strongNumber: "H6310", lemma: "peh", meaning: "mouth; speech" }] },
      { verse: 13, text: "And ye shall tell my father of all my glory in Egypt, and of all that ye have seen; and ye shall haste and bring down my father hither.", highlightedWords: [{ word: "glory", strongNumber: "H3519", lemma: "kabod", meaning: "glory; honor; weight" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 14, text: "And he fell upon his brother Benjamin's neck, and wept; and Benjamin wept upon his neck.", highlightedWords: [{ word: "Benjamin", strongNumber: "H1144", lemma: "Binyamin", meaning: "son of the right hand" }, { word: "wept", strongNumber: "H1058", lemma: "bakah", meaning: "to weep; lament" }] },
      { verse: 15, text: "Moreover he kissed all his brethren, and wept upon them: and after that his brethren talked with him.", highlightedWords: [{ word: "kissed", strongNumber: "H5401", lemma: "nashaq", meaning: "to kiss" }, { word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brother; kinsman" }] },
      { verse: 16, text: "And the fame thereof was heard in Pharaoh's house, saying, Joseph's brethren are come: and it pleased Pharaoh well, and his servants.", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "Pharaoh; Egyptian king" }, { word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brother; kinsman" }] },
      { verse: 17, text: "And Pharaoh said unto Joseph, Say unto thy brethren, This do ye; lade your beasts, and go, get you unto the land of Canaan;", highlightedWords: [{ word: "Pharaoh", strongNumber: "H6547", lemma: "Paroh", meaning: "Pharaoh; Egyptian king" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan; the land of Canaan" }] },
      { verse: 18, text: "And take your father and your households, and come unto me: and I will give you the good of the land of Egypt, and ye shall eat the fat of the land.", highlightedWords: [{ word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }, { word: "land", strongNumber: "H776", lemma: "erets", meaning: "land; earth" }] },
      { verse: 19, text: "Now thou art commanded, this do ye; take you wagons out of the land of Egypt for your little ones, and for your wives, and bring your father, and come.", highlightedWords: [{ word: "wagons", strongNumber: "H5699", lemma: "agalah", meaning: "cart; wagon" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 20, text: "Also regard not your stuff; for the good of all the land of Egypt is yours.", highlightedWords: [{ word: "stuff", strongNumber: "H3627", lemma: "keli", meaning: "articles; utensils; goods" }, { word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }] },
      { verse: 21, text: "And the children of Israel did so: and Joseph gave them wagons, according to the commandment of Pharaoh, and gave them provision for the way.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisrael", meaning: "God strives; Israel" }, { word: "wagons", strongNumber: "H5699", lemma: "agalah", meaning: "cart; wagon" }] },
      { verse: 22, text: "To all of them he gave each man changes of raiment; but to Benjamin he gave three hundred pieces of silver, and five changes of raiment.", highlightedWords: [{ word: "Benjamin", strongNumber: "H1144", lemma: "Binyamin", meaning: "son of the right hand" }, { word: "silver", strongNumber: "H3701", lemma: "kesef", meaning: "silver; money" }] },
      { verse: 23, text: "And to his father he sent after this manner; ten asses laden with the good things of Egypt, and ten she asses laden with corn and bread and meat for his father by the way.", highlightedWords: [{ word: "asses", strongNumber: "H2543", lemma: "chamor", meaning: "donkey; male ass" }, { word: "bread", strongNumber: "H3899", lemma: "lechem", meaning: "bread; food" }] },
      { verse: 24, text: "So he sent his brethren away, and they departed: and he said unto them, See that ye fall not out by the way.", highlightedWords: [{ word: "brethren", strongNumber: "H251", lemma: "ach", meaning: "brother; kinsman" }, { word: "way", strongNumber: "H1870", lemma: "derek", meaning: "way; road; path" }] },
      { verse: 25, text: "And they went up out of Egypt, and came into the land of Canaan unto Jacob their father,", highlightedWords: [{ word: "Egypt", strongNumber: "H4714", lemma: "Mitsrayim", meaning: "Egypt" }, { word: "Canaan", strongNumber: "H3667", lemma: "Kena'an", meaning: "Canaan; the land of Canaan" }] },
      { verse: 26, text: "And told him, saying, Joseph is yet alive, and he is governor over all the land of Egypt. And Jacob's heart fainted, for he believed them not.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he will add" }, { word: "heart", strongNumber: "H3820", lemma: "leb", meaning: "heart; inner person" }] },
      { verse: 27, text: "And they told him all the words of Joseph, which he had said unto them: and when he saw the wagons which Joseph had sent to carry him, the spirit of Jacob their father revived:", highlightedWords: [{ word: "wagons", strongNumber: "H5699", lemma: "agalah", meaning: "cart; wagon" }, { word: "spirit", strongNumber: "H7307", lemma: "ruach", meaning: "spirit; breath; wind" }] },
      { verse: 28, text: "And Israel said, It is enough; Joseph my son is yet alive: I will go and see him before I die.", highlightedWords: [{ word: "Israel", strongNumber: "H3478", lemma: "Yisrael", meaning: "God strives; Israel" }, { word: "die", strongNumber: "H4191", lemma: "muth", meaning: "to die; perish" }] }
    ]
  }
}
