export const genesisChapter1 = {
  "Genesis-1": {
    book: "Genesis",
    chapter: 1,
    twoWordSummary: "Divine Creation",
    themeSummary: "God speaks the universe into existence, establishing light, sky, land, seas, plants, celestial bodies, animals, and finally humanity in His image with dominion over the earth.",
    sentenceDescription: "God creates all things through spoken word, culminating in humanity made in His divine image with authority over creation.",
    themeWords: [
      { word: "beginning", strongNumber: "H7225", language: "Hebrew", lemma: "re'shith", meaning: "first; starting point; origin" },
      { word: "created", strongNumber: "H1254", language: "Hebrew", lemma: "bara", meaning: "to create by divine act; bring into existence" }
    ],
    verses: [
      { book: "Genesis", chapter: 1, verse: 1, text: "In the beginning God created the heaven and the earth.", highlightedWords: [{ word: "beginning", strongNumber: "H7225", language: "Hebrew", lemma: "re'shith", meaning: "first; starting point; origin" }, { word: "created", strongNumber: "H1254", language: "Hebrew", lemma: "bara", meaning: "to create by divine act; bring into existence" }] },
      { book: "Genesis", chapter: 1, verse: 2, text: "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.", highlightedWords: [{ word: "void", strongNumber: "H922", language: "Hebrew", lemma: "bohu", meaning: "emptiness; desolation" }, { word: "moved", strongNumber: "H7363", language: "Hebrew", lemma: "rachaph", meaning: "to hover; brood gently over" }] },
      { book: "Genesis", chapter: 1, verse: 3, text: "And God said, Let there be light: and there was light.", highlightedWords: [{ word: "said", strongNumber: "H559", language: "Hebrew", lemma: "amar", meaning: "to speak; declare; command" }, { word: "light", strongNumber: "H216", language: "Hebrew", lemma: "or", meaning: "illumination; brightness; divine light" }] },
      { book: "Genesis", chapter: 1, verse: 4, text: "And God saw the light, that it was good: and God divided the light from the darkness.", highlightedWords: [{ word: "good", strongNumber: "H2896", language: "Hebrew", lemma: "tob", meaning: "pleasant; beneficial; morally good" }, { word: "divided", strongNumber: "H914", language: "Hebrew", lemma: "badal", meaning: "to separate; distinguish" }] },
      { book: "Genesis", chapter: 1, verse: 5, text: "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.", highlightedWords: [{ word: "called", strongNumber: "H7121", language: "Hebrew", lemma: "qara", meaning: "to name; proclaim" }, { word: "day", strongNumber: "H3117", language: "Hebrew", lemma: "yom", meaning: "day; period of light" }] },
      { book: "Genesis", chapter: 1, verse: 6, text: "And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.", highlightedWords: [{ word: "firmament", strongNumber: "H7549", language: "Hebrew", lemma: "raqia", meaning: "expanse; stretched sky" }, { word: "divide", strongNumber: "H914", language: "Hebrew", lemma: "badal", meaning: "to separate; distinguish" }] },
      { book: "Genesis", chapter: 1, verse: 7, text: "And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.", highlightedWords: [{ word: "made", strongNumber: "H6213", language: "Hebrew", lemma: "asah", meaning: "to fashion; accomplish; produce" }, { word: "firmament", strongNumber: "H7549", language: "Hebrew", lemma: "raqia", meaning: "expanse; visible heavens" }] },
      { book: "Genesis", chapter: 1, verse: 8, text: "And God called the firmament Heaven. And the evening and the morning were the second day.", highlightedWords: [{ word: "Heaven", strongNumber: "H8064", language: "Hebrew", lemma: "shamayim", meaning: "the sky; heavens above" }, { word: "called", strongNumber: "H7121", language: "Hebrew", lemma: "qara", meaning: "to name; proclaim identity" }] },
      { book: "Genesis", chapter: 1, verse: 9, text: "And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so.", highlightedWords: [{ word: "gathered", strongNumber: "H6960", language: "Hebrew", lemma: "qavah", meaning: "to collect together; assemble" }, { word: "appear", strongNumber: "H7200", language: "Hebrew", lemma: "raah", meaning: "to be seen; become visible" }] },
      { book: "Genesis", chapter: 1, verse: 10, text: "And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.", highlightedWords: [{ word: "Earth", strongNumber: "H776", language: "Hebrew", lemma: "erets", meaning: "land; earth; ground" }, { word: "Seas", strongNumber: "H3220", language: "Hebrew", lemma: "yam", meaning: "sea; large body of water" }] },
      { book: "Genesis", chapter: 1, verse: 11, text: "And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so.", highlightedWords: [{ word: "bring", strongNumber: "H1876", language: "Hebrew", lemma: "dasha", meaning: "to sprout; cause to grow" }, { word: "seed", strongNumber: "H2233", language: "Hebrew", lemma: "zera", meaning: "seed; offspring; source of life" }] },
      { book: "Genesis", chapter: 1, verse: 12, text: "And the earth brought forth grass, and herb yielding seed after his kind, and the tree yielding fruit, whose seed was in itself, after his kind: and God saw that it was good.", highlightedWords: [{ word: "fruit", strongNumber: "H6529", language: "Hebrew", lemma: "peri", meaning: "fruit; produce; yield" }, { word: "kind", strongNumber: "H4327", language: "Hebrew", lemma: "min", meaning: "species; category; type" }] },
      { book: "Genesis", chapter: 1, verse: 13, text: "And the evening and the morning were the third day.", highlightedWords: [{ word: "evening", strongNumber: "H6153", language: "Hebrew", lemma: "ereb", meaning: "sunset; evening time" }, { word: "morning", strongNumber: "H1242", language: "Hebrew", lemma: "boqer", meaning: "daybreak; morning light" }] },
      { book: "Genesis", chapter: 1, verse: 14, text: "And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:", highlightedWords: [{ word: "lights", strongNumber: "H3974", language: "Hebrew", lemma: "maor", meaning: "luminary; source of light" }, { word: "seasons", strongNumber: "H4150", language: "Hebrew", lemma: "moed", meaning: "appointed times; sacred seasons" }] },
      { book: "Genesis", chapter: 1, verse: 15, text: "And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so.", highlightedWords: [{ word: "give", strongNumber: "H5414", language: "Hebrew", lemma: "nathan", meaning: "to give; bestow; place" }, { word: "earth", strongNumber: "H776", language: "Hebrew", lemma: "erets", meaning: "land; the world below" }] },
      { book: "Genesis", chapter: 1, verse: 16, text: "And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also.", highlightedWords: [{ word: "rule", strongNumber: "H4475", language: "Hebrew", lemma: "memshalah", meaning: "dominion; governing authority" }, { word: "stars", strongNumber: "H3556", language: "Hebrew", lemma: "kokab", meaning: "star; celestial body" }] },
      { book: "Genesis", chapter: 1, verse: 17, text: "And God set them in the firmament of the heaven to give light upon the earth,", highlightedWords: [{ word: "set", strongNumber: "H5414", language: "Hebrew", lemma: "nathan", meaning: "to place; appoint" }, { word: "firmament", strongNumber: "H7549", language: "Hebrew", lemma: "raqia", meaning: "expanse; heavens" }] },
      { book: "Genesis", chapter: 1, verse: 18, text: "And to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good.", highlightedWords: [{ word: "divide", strongNumber: "H914", language: "Hebrew", lemma: "badal", meaning: "to separate; distinguish" }, { word: "darkness", strongNumber: "H2822", language: "Hebrew", lemma: "choshek", meaning: "darkness; obscurity" }] },
      { book: "Genesis", chapter: 1, verse: 19, text: "And the evening and the morning were the fourth day.", highlightedWords: [{ word: "evening", strongNumber: "H6153", language: "Hebrew", lemma: "ereb", meaning: "sunset" }, { word: "morning", strongNumber: "H1242", language: "Hebrew", lemma: "boqer", meaning: "dawn; daybreak" }] },
      { book: "Genesis", chapter: 1, verse: 20, text: "And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth in the open firmament of heaven.", highlightedWords: [{ word: "bring", strongNumber: "H8317", language: "Hebrew", lemma: "sharats", meaning: "to swarm; teem abundantly" }, { word: "life", strongNumber: "H5315", language: "Hebrew", lemma: "nephesh", meaning: "living soul; life force" }] },
      { book: "Genesis", chapter: 1, verse: 21, text: "And God created great whales, and every living creature that moveth, which the waters brought forth abundantly, after their kind...", highlightedWords: [{ word: "created", strongNumber: "H1254", language: "Hebrew", lemma: "bara", meaning: "to create by divine power" }, { word: "creature", strongNumber: "H5315", language: "Hebrew", lemma: "nephesh", meaning: "living being; soul" }] },
      { book: "Genesis", chapter: 1, verse: 22, text: "And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let fowl multiply in the earth.", highlightedWords: [{ word: "blessed", strongNumber: "H1288", language: "Hebrew", lemma: "barak", meaning: "to bless; endow with favor" }, { word: "multiply", strongNumber: "H7235", language: "Hebrew", lemma: "rabah", meaning: "to increase; become many" }] },
      { book: "Genesis", chapter: 1, verse: 23, text: "And the evening and the morning were the fifth day.", highlightedWords: [{ word: "evening", strongNumber: "H6153", language: "Hebrew", lemma: "ereb", meaning: "sunset" }, { word: "morning", strongNumber: "H1242", language: "Hebrew", lemma: "boqer", meaning: "daybreak" }] },
      { book: "Genesis", chapter: 1, verse: 24, text: "And God said, Let the earth bring forth the living creature after his kind, cattle, and creeping thing, and beast of the earth after his kind: and it was so.", highlightedWords: [{ word: "living", strongNumber: "H2416", language: "Hebrew", lemma: "chay", meaning: "living; alive" }, { word: "beast", strongNumber: "H929", language: "Hebrew", lemma: "behemah", meaning: "animal; beast; livestock" }] },
      { book: "Genesis", chapter: 1, verse: 25, text: "And God made the beast of the earth after his kind...", highlightedWords: [{ word: "made", strongNumber: "H6213", language: "Hebrew", lemma: "asah", meaning: "to make; fashion; accomplish" }, { word: "creepeth", strongNumber: "H7430", language: "Hebrew", lemma: "remes", meaning: "creeping creature; small moving life" }] },
      { book: "Genesis", chapter: 1, verse: 26, text: "And God said, Let us make man in our image, after our likeness...", highlightedWords: [{ word: "image", strongNumber: "H6754", language: "Hebrew", lemma: "tselem", meaning: "image; representation; likeness" }, { word: "dominion", strongNumber: "H7287", language: "Hebrew", lemma: "radah", meaning: "to rule; exercise authority" }] },
      { book: "Genesis", chapter: 1, verse: 27, text: "So God created man in his own image, in the image of God created he him; male and female created he them.", highlightedWords: [{ word: "created", strongNumber: "H1254", language: "Hebrew", lemma: "bara", meaning: "to create by divine power" }, { word: "male", strongNumber: "H2145", language: "Hebrew", lemma: "zakar", meaning: "male; masculine being" }] },
      { book: "Genesis", chapter: 1, verse: 28, text: "And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it...", highlightedWords: [{ word: "replenish", strongNumber: "H4390", language: "Hebrew", lemma: "male", meaning: "to fill; make full" }, { word: "subdue", strongNumber: "H3533", language: "Hebrew", lemma: "kabash", meaning: "to bring into subjection; govern" }] },
      { book: "Genesis", chapter: 1, verse: 29, text: "And God said, Behold, I have given you every herb bearing seed...", highlightedWords: [{ word: "given", strongNumber: "H5414", language: "Hebrew", lemma: "nathan", meaning: "to give; grant; bestow" }, { word: "herb", strongNumber: "H6212", language: "Hebrew", lemma: "eseb", meaning: "plant; green herb" }] },
      { book: "Genesis", chapter: 1, verse: 30, text: "And to every beast of the earth... wherein there is life, I have given every green herb for meat: and it was so.", highlightedWords: [{ word: "life", strongNumber: "H5315", language: "Hebrew", lemma: "nephesh", meaning: "living soul; life principle" }, { word: "meat", strongNumber: "H402", language: "Hebrew", lemma: "oklah", meaning: "food; nourishment" }] },
      { book: "Genesis", chapter: 1, verse: 31, text: "And God saw every thing that he had made, and, behold, it was very good. And the evening and the morning were the sixth day.", highlightedWords: [{ word: "made", strongNumber: "H6213", language: "Hebrew", lemma: "asah", meaning: "to accomplish; produce" }, { word: "good", strongNumber: "H2896", language: "Hebrew", lemma: "tob", meaning: "excellent; beneficial; good" }] }
    ]
  }
}
