import { ChapterData } from "@/lib/bible-data"

export const genesisChapter2: ChapterData = {
  "Genesis-2": {
    book: "Genesis",
    chapter: 2,
    twoWordSummary: "Garden Covenant",
    themeSummary: "God completes creation, rests on the seventh day, forms Adam from the dust, places him in the Garden of Eden, and creates Eve establishing the first marriage.",
    sentenceDescription: "God completes creation, rests on the seventh day, forms Adam from the dust, places him in the Garden of Eden, and creates Eve establishing the first marriage.",
    themeWords: [
      { word: "rested", strongNumber: "H7673", lemma: "shabath", meaning: "to cease; rest; stop working" },
      { word: "garden", strongNumber: "H1588", lemma: "gan", meaning: "garden; enclosed place" }
    ],
    verses: [
      { verseNumber: 1, text: "Thus the heavens and the earth were finished, and all the host of them.", highlightedWords: [{ word: "finished", strongNumber: "H3615", lemma: "kalah", meaning: "to complete; bring to an end" }, { word: "host", strongNumber: "H6635", lemma: "tsaba", meaning: "army; multitude; vast company" }] },
      { verseNumber: 2, text: "And on the seventh day God ended his work which he had made; and he rested on the seventh day from all his work which he had made.", highlightedWords: [{ word: "seventh", strongNumber: "H7637", lemma: "shebiiy", meaning: "seventh; sacred completion" }, { word: "rested", strongNumber: "H7673", lemma: "shabath", meaning: "to cease; rest; stop working" }] },
      { verseNumber: 3, text: "And God blessed the seventh day, and sanctified it: because that in it he had rested from all his work which God created and made.", highlightedWords: [{ word: "blessed", strongNumber: "H1288", lemma: "barak", meaning: "to bless; endow with favor" }, { word: "sanctified", strongNumber: "H6942", lemma: "qadash", meaning: "to set apart; make holy" }] },
      { verseNumber: 4, text: "These are the generations of the heavens and of the earth when they were created, in the day that the LORD God made the earth and the heavens.", highlightedWords: [{ word: "generations", strongNumber: "H8435", lemma: "toledoth", meaning: "account; history; origins" }, { word: "LORD", strongNumber: "H3068", lemma: "YHWH", meaning: "the covenant name of God" }] },
      { verseNumber: 5, text: "And every plant of the field before it was in the earth, and every herb of the field before it grew: for the LORD God had not caused it to rain upon the earth, and there was not a man to till the ground.", highlightedWords: [{ word: "rain", strongNumber: "H4305", lemma: "matar", meaning: "rain; rainfall" }, { word: "till", strongNumber: "H5647", lemma: "abad", meaning: "to serve; work; cultivate" }] },
      { verseNumber: 6, text: "But there went up a mist from the earth, and watered the whole face of the ground.", highlightedWords: [{ word: "mist", strongNumber: "H108", lemma: "ed", meaning: "mist; vapor rising from earth" }, { word: "watered", strongNumber: "H8248", lemma: "shaqah", meaning: "to give drink; water" }] },
      { verseNumber: 7, text: "And the LORD God formed man of the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.", highlightedWords: [{ word: "formed", strongNumber: "H3335", lemma: "yatsar", meaning: "to form; shape like a potter" }, { word: "breathed", strongNumber: "H5301", lemma: "naphach", meaning: "to breathe; blow life" }] },
      { verseNumber: 8, text: "And the LORD God planted a garden eastward in Eden; and there he put the man whom he had formed.", highlightedWords: [{ word: "garden", strongNumber: "H1588", lemma: "gan", meaning: "garden; enclosed place" }, { word: "Eden", strongNumber: "H5731", lemma: "eden", meaning: "delight; pleasure" }] },
      { verseNumber: 9, text: "And out of the ground made the LORD God to grow every tree that is pleasant to the sight, and good for food; the tree of life also in the midst of the garden, and the tree of knowledge of good and evil.", highlightedWords: [{ word: "tree", strongNumber: "H6086", lemma: "ets", meaning: "tree; wood" }, { word: "life", strongNumber: "H2416", lemma: "chay", meaning: "life; living" }] },
      { verseNumber: 10, text: "And a river went out of Eden to water the garden; and from thence it was parted, and became into four heads.", highlightedWords: [{ word: "river", strongNumber: "H5104", lemma: "nahar", meaning: "river; flowing stream" }, { word: "heads", strongNumber: "H7218", lemma: "rosh", meaning: "head; beginning; source" }] },
      { verseNumber: 11, text: "The name of the first is Pison: that is it which compasseth the whole land of Havilah, where there is gold;", highlightedWords: [{ word: "gold", strongNumber: "H2091", lemma: "zahab", meaning: "gold; precious metal" }, { word: "land", strongNumber: "H776", lemma: "erets", meaning: "earth; land" }] },
      { verseNumber: 12, text: "And the gold of that land is good: there is bdellium and the onyx stone.", highlightedWords: [{ word: "bdellium", strongNumber: "H916", lemma: "bedolach", meaning: "aromatic resin or precious substance" }, { word: "onyx", strongNumber: "H7718", lemma: "shoham", meaning: "onyx stone; precious gem" }] },
      { verseNumber: 13, text: "And the name of the second river is Gihon: the same is it that compasseth the whole land of Ethiopia.", highlightedWords: [{ word: "Gihon", strongNumber: "H1521", lemma: "gichon", meaning: "Gihon river" }, { word: "Ethiopia", strongNumber: "H3568", lemma: "kush", meaning: "Cush; region south of Egypt" }] },
      { verseNumber: 14, text: "And the name of the third river is Hiddekel: that is it which goeth toward the east of Assyria. And the fourth river is Euphrates.", highlightedWords: [{ word: "Hiddekel", strongNumber: "H2313", lemma: "chiddeqel", meaning: "Tigris river" }, { word: "Euphrates", strongNumber: "H6578", lemma: "perath", meaning: "Euphrates river" }] },
      { verseNumber: 15, text: "And the LORD God took the man, and put him into the garden of Eden to dress it and to keep it.", highlightedWords: [{ word: "dress", strongNumber: "H5647", lemma: "abad", meaning: "to serve; cultivate" }, { word: "keep", strongNumber: "H8104", lemma: "shamar", meaning: "to guard; keep; watch over" }] },
      { verseNumber: 16, text: "And the LORD God commanded the man, saying, Of every tree of the garden thou mayest freely eat:", highlightedWords: [{ word: "commanded", strongNumber: "H6680", lemma: "tsavah", meaning: "to command; give charge" }, { word: "eat", strongNumber: "H398", lemma: "akal", meaning: "to eat; consume food" }] },
      { verseNumber: 17, text: "But of the tree of the knowledge of good and evil, thou shalt not eat of it: for in the day thou eatest thereof thou shalt surely die.", highlightedWords: [{ word: "knowledge", strongNumber: "H1847", lemma: "daath", meaning: "knowledge; awareness" }, { word: "die", strongNumber: "H4191", lemma: "muth", meaning: "to die; death sentence" }] },
      { verseNumber: 18, text: "And the LORD God said, It is not good that the man should be alone; I will make him an help meet for him.", highlightedWords: [{ word: "alone", strongNumber: "H905", lemma: "bad", meaning: "alone; separated" }, { word: "help", strongNumber: "H5828", lemma: "ezer", meaning: "help; strong support" }] },
      { verseNumber: 19, text: "And out of the ground the LORD God formed every beast of the field, and every fowl of the air; and brought them unto Adam to see what he would call them: and whatsoever Adam called every living creature, that was the name thereof.", highlightedWords: [{ word: "beast", strongNumber: "H2416", lemma: "chay", meaning: "living animal" }, { word: "name", strongNumber: "H8034", lemma: "shem", meaning: "name; identity" }] },
      { verseNumber: 20, text: "And Adam gave names to all cattle, and to the fowl of the air, and to every beast of the field; but for Adam there was not found an help meet for him.", highlightedWords: [{ word: "Adam", strongNumber: "H120", lemma: "adam", meaning: "man; mankind" }, { word: "names", strongNumber: "H8034", lemma: "shem", meaning: "name; designation" }] },
      { verseNumber: 21, text: "And the LORD God caused a deep sleep to fall upon Adam, and he slept: and he took one of his ribs, and closed up the flesh instead thereof;", highlightedWords: [{ word: "sleep", strongNumber: "H8639", lemma: "tardemah", meaning: "deep sleep; trance" }, { word: "rib", strongNumber: "H6763", lemma: "tsela", meaning: "side; rib" }] },
      { verseNumber: 22, text: "And the rib, which the LORD God had taken from man, made he a woman, and brought her unto the man.", highlightedWords: [{ word: "woman", strongNumber: "H802", lemma: "ishshah", meaning: "woman; wife" }, { word: "brought", strongNumber: "H935", lemma: "bo", meaning: "to bring; lead in" }] },
      { verseNumber: 23, text: "And Adam said, This is now bone of my bones, and flesh of my flesh: she shall be called Woman, because she was taken out of Man.", highlightedWords: [{ word: "bone", strongNumber: "H6106", lemma: "etsem", meaning: "bone; essence" }, { word: "called", strongNumber: "H7121", lemma: "qara", meaning: "to call; name" }] },
      { verseNumber: 24, text: "Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh.", highlightedWords: [{ word: "cleave", strongNumber: "H1692", lemma: "dabaq", meaning: "to cling; join closely" }, { word: "flesh", strongNumber: "H1320", lemma: "basar", meaning: "flesh; body; humanity" }] },
      { verseNumber: 25, text: "And they were both naked, the man and his wife, and were not ashamed.", highlightedWords: [{ word: "naked", strongNumber: "H6174", lemma: "arom", meaning: "naked; uncovered" }, { word: "ashamed", strongNumber: "H954", lemma: "bosh", meaning: "to be ashamed; embarrassed" }] },
    ]
  }
}
