import { ChapterData } from "@/lib/bible-data"

export const genesisChapter1: ChapterData = {
  "Genesis-1": {
    book: "Genesis",
    chapter: 1,
    twoWordSummary: "Divine Creation",
    themeSummary: "God creates the heavens and the earth in six ordered days, bringing light, life, and humanity into existence by His word and declaring His creation very good.",
    sentenceDescription: "God creates all things through spoken word, culminating in humanity made in His divine image with authority over creation.",
    themeWords: [
      { word: "beginning", strongNumber: "H7225", lemma: "reshith", meaning: "first; beginning; chief" },
      { word: "created", strongNumber: "H1254", lemma: "bara", meaning: "to create; shape by divine power" }
    ],
    verses: [
      { verseNumber: 1, text: "In the beginning God created the heaven and the earth.", highlightedWords: [{ word: "beginning", strongNumber: "H7225", lemma: "reshith", meaning: "first; beginning; chief" }, { word: "created", strongNumber: "H1254", lemma: "bara", meaning: "to create; shape by divine power" }] },
      { verseNumber: 2, text: "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters.", highlightedWords: [{ word: "Spirit", strongNumber: "H7307", lemma: "ruach", meaning: "spirit; breath; wind" }, { word: "moved", strongNumber: "H7363", lemma: "rachaph", meaning: "to hover; flutter gently" }] },
      { verseNumber: 3, text: "And God said, Let there be light: and there was light.", highlightedWords: [{ word: "said", strongNumber: "H559", lemma: "amar", meaning: "to say; speak; declare" }, { word: "light", strongNumber: "H216", lemma: "or", meaning: "light; illumination" }] },
      { verseNumber: 4, text: "And God saw the light, that it was good: and God divided the light from the darkness.", highlightedWords: [{ word: "good", strongNumber: "H2896", lemma: "tov", meaning: "good; pleasant; beneficial" }, { word: "divided", strongNumber: "H914", lemma: "badal", meaning: "to separate; distinguish" }] },
      { verseNumber: 5, text: "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day.", highlightedWords: [{ word: "called", strongNumber: "H7121", lemma: "qara", meaning: "to call; name; proclaim" }, { word: "day", strongNumber: "H3117", lemma: "yom", meaning: "day; time period" }] },
      { verseNumber: 6, text: "And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters.", highlightedWords: [{ word: "firmament", strongNumber: "H7549", lemma: "raqia", meaning: "expanse; stretched sky" }, { word: "divide", strongNumber: "H914", lemma: "badal", meaning: "to separate; distinguish" }] },
      { verseNumber: 7, text: "And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so.", highlightedWords: [{ word: "made", strongNumber: "H6213", lemma: "asah", meaning: "to make; do; accomplish" }, { word: "waters", strongNumber: "H4325", lemma: "mayim", meaning: "waters; bodies of water" }] },
      { verseNumber: 8, text: "And God called the firmament Heaven. And the evening and the morning were the second day.", highlightedWords: [{ word: "Heaven", strongNumber: "H8064", lemma: "shamayim", meaning: "heavens; sky" }, { word: "evening", strongNumber: "H6153", lemma: "ereb", meaning: "evening; sunset time" }] },
      { verseNumber: 9, text: "And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so.", highlightedWords: [{ word: "gathered", strongNumber: "H6960", lemma: "qavah", meaning: "to collect together" }, { word: "land", strongNumber: "H3004", lemma: "yabbashah", meaning: "dry land" }] },
      { verseNumber: 10, text: "And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good.", highlightedWords: [{ word: "Earth", strongNumber: "H776", lemma: "erets", meaning: "earth; land" }, { word: "Seas", strongNumber: "H3220", lemma: "yam", meaning: "sea; large body of water" }] },
      { verseNumber: 11, text: "And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so.", highlightedWords: [{ word: "grass", strongNumber: "H1877", lemma: "deshe", meaning: "grass; green vegetation" }, { word: "seed", strongNumber: "H2233", lemma: "zera", meaning: "seed; offspring" }] },
      { verseNumber: 12, text: "And the earth brought forth grass, and herb yielding seed after his kind, and the tree yielding fruit, whose seed was in itself, after his kind: and God saw that it was good.", highlightedWords: [{ word: "fruit", strongNumber: "H6529", lemma: "peri", meaning: "fruit; produce" }, { word: "kind", strongNumber: "H4327", lemma: "min", meaning: "kind; species" }] },
      { verseNumber: 13, text: "And the evening and the morning were the third day.", highlightedWords: [{ word: "evening", strongNumber: "H6153", lemma: "ereb", meaning: "evening; sunset time" }, { word: "morning", strongNumber: "H1242", lemma: "boqer", meaning: "morning; dawn" }] },
      { verseNumber: 14, text: "And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:", highlightedWords: [{ word: "lights", strongNumber: "H3974", lemma: "maor", meaning: "luminary; light source" }, { word: "seasons", strongNumber: "H4150", lemma: "moed", meaning: "appointed time; season" }] },
      { verseNumber: 15, text: "And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so.", highlightedWords: [{ word: "give", strongNumber: "H5414", lemma: "nathan", meaning: "to give; place" }, { word: "earth", strongNumber: "H776", lemma: "erets", meaning: "earth; land" }] },
      { verseNumber: 16, text: "And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also.", highlightedWords: [{ word: "rule", strongNumber: "H4474", lemma: "memshalah", meaning: "dominion; rule" }, { word: "stars", strongNumber: "H3556", lemma: "kokab", meaning: "star; celestial body" }] },
      { verseNumber: 17, text: "And God set them in the firmament of the heaven to give light upon the earth,", highlightedWords: [{ word: "set", strongNumber: "H5414", lemma: "nathan", meaning: "to place; appoint" }, { word: "firmament", strongNumber: "H7549", lemma: "raqia", meaning: "expanse; sky" }] },
      { verseNumber: 18, text: "And to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good.", highlightedWords: [{ word: "rule", strongNumber: "H4910", lemma: "mashal", meaning: "to govern; rule" }, { word: "darkness", strongNumber: "H2822", lemma: "choshek", meaning: "darkness; obscurity" }] },
      { verseNumber: 19, text: "And the evening and the morning were the fourth day.", highlightedWords: [{ word: "fourth", strongNumber: "H7243", lemma: "rebii", meaning: "fourth" }, { word: "day", strongNumber: "H3117", lemma: "yom", meaning: "day; time period" }] },
      { verseNumber: 20, text: "And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth in the open firmament of heaven.", highlightedWords: [{ word: "creature", strongNumber: "H5315", lemma: "nephesh", meaning: "living creature; soul" }, { word: "fly", strongNumber: "H5774", lemma: "uph", meaning: "to fly; fly about" }] },
      { verseNumber: 21, text: "And God created great whales, and every living creature that moveth, which the waters brought forth abundantly, after their kind, and every winged fowl after his kind: and God saw that it was good.", highlightedWords: [{ word: "whales", strongNumber: "H8577", lemma: "tannin", meaning: "great sea creatures" }, { word: "created", strongNumber: "H1254", lemma: "bara", meaning: "to create; bring into existence" }] },
      { verseNumber: 22, text: "And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let fowl multiply in the earth.", highlightedWords: [{ word: "blessed", strongNumber: "H1288", lemma: "barak", meaning: "to bless; endow with favor" }, { word: "multiply", strongNumber: "H7235", lemma: "rabah", meaning: "to multiply; increase" }] },
      { verseNumber: 23, text: "And the evening and the morning were the fifth day.", highlightedWords: [{ word: "fifth", strongNumber: "H2549", lemma: "chamishi", meaning: "fifth" }, { word: "morning", strongNumber: "H1242", lemma: "boqer", meaning: "morning; dawn" }] },
      { verseNumber: 24, text: "And God said, Let the earth bring forth the living creature after his kind, cattle, and creeping thing, and beast of the earth after his kind: and it was so.", highlightedWords: [{ word: "beast", strongNumber: "H2416", lemma: "chay", meaning: "living animal; beast" }, { word: "kind", strongNumber: "H4327", lemma: "min", meaning: "kind; species" }] },
      { verseNumber: 25, text: "And God made the beast of the earth after his kind, and cattle after their kind, and every thing that creepeth upon the earth after his kind: and God saw that it was good.", highlightedWords: [{ word: "beast", strongNumber: "H2416", lemma: "chay", meaning: "living animal" }, { word: "good", strongNumber: "H2896", lemma: "tov", meaning: "good; beneficial" }] },
      { verseNumber: 26, text: "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that creepeth upon the earth.", highlightedWords: [{ word: "image", strongNumber: "H6754", lemma: "tselem", meaning: "image; representation" }, { word: "dominion", strongNumber: "H7287", lemma: "radah", meaning: "to rule; have dominion" }] },
      { verseNumber: 27, text: "So God created man in his own image, in the image of God created he him; male and female created he them.", highlightedWords: [{ word: "man", strongNumber: "H120", lemma: "adam", meaning: "man; mankind" }, { word: "female", strongNumber: "H5347", lemma: "neqebah", meaning: "female" }] },
      { verseNumber: 28, text: "And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it: and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth.", highlightedWords: [{ word: "blessed", strongNumber: "H1288", lemma: "barak", meaning: "to bless; endow with favor" }, { word: "subdue", strongNumber: "H3533", lemma: "kabash", meaning: "to subdue; bring into bondage" }] },
      { verseNumber: 29, text: "And God said, Behold, I have given you every herb bearing seed, which is upon the face of all the earth, and every tree, in the which is the fruit of a tree yielding seed; to you it shall be for meat.", highlightedWords: [{ word: "given", strongNumber: "H5414", lemma: "nathan", meaning: "to give; grant" }, { word: "meat", strongNumber: "H402", lemma: "oklah", meaning: "food; nourishment" }] },
      { verseNumber: 30, text: "And to every beast of the earth, and to every fowl of the air, and to every thing that creepeth upon the earth, wherein there is life, I have given every green herb for meat: and it was so.", highlightedWords: [{ word: "green", strongNumber: "H3418", lemma: "yaraq", meaning: "green; vegetation" }, { word: "life", strongNumber: "H5315", lemma: "nephesh", meaning: "living creature; life" }] },
      { verseNumber: 31, text: "And God saw every thing that he had made, and, behold, it was very good. And the evening and the morning were the sixth day.", highlightedWords: [{ word: "very", strongNumber: "H3966", lemma: "meod", meaning: "very; exceedingly" }, { word: "sixth", strongNumber: "H8345", lemma: "shishi", meaning: "sixth" }] },
    ]
  }
}
