export const joshuaChapter16 = [
  { verse: 1, text: "And the lot of the children of Joseph fell from Jordan by Jericho, unto the water of Jericho on the east, to the wilderness that goeth up from Jericho throughout mount Bethel,", highlightedWords: [{ word: "Jordan", strongNumber: "H3383", lemma: "Yarden", meaning: "the descender; the Jordan River" }, { word: "Jericho", strongNumber: "H3405", lemma: "Yericho", meaning: "fragrant; Jericho" }] },
  { verse: 2, text: "And goeth out from Bethel to Luz, and passeth along unto the borders of Archi to Ataroth,", highlightedWords: [{ word: "Bethel", strongNumber: "H1008", lemma: "Bet-El", meaning: "house of God" }, { word: "Luz", strongNumber: "H3870", lemma: "Luz", meaning: "almond tree; Luz" }] },
  { verse: 3, text: "And goeth down westward to the coast of Japhleti, unto the coast of Bethhoron the nether, and to Gezer; and the goings out thereof are at the sea.", highlightedWords: [{ word: "Gezer", strongNumber: "H1507", lemma: "Gezer", meaning: "Gezer, a Canaanite city" }, { word: "sea", strongNumber: "H3220", lemma: "yam", meaning: "sea" }] },
  { verse: 4, text: "So the children of Joseph, Manasseh and Ephraim, took their inheritance.", highlightedWords: [{ word: "Joseph", strongNumber: "H3130", lemma: "Yosef", meaning: "he adds; Joseph" }, { word: "inheritance", strongNumber: "H5159", lemma: "nahala", meaning: "inheritance, heritage" }] },
  { verse: 5, text: "And the border of the children of Ephraim according to their families was thus: even the border of their inheritance on the east side was Atarothaddar, unto Bethhoron the upper;", highlightedWords: [{ word: "Ephraim", strongNumber: "H669", lemma: "Ephrayim", meaning: "fruitful; Ephraim" }, { word: "Bethhoron", strongNumber: "H1032", lemma: "Bet-Horon", meaning: "house of the hollow; Beth-horon" }] },
  { verse: 6, text: "And the border went out toward the sea to Michmethah on the north side; and the border went about eastward unto Taanathshiloh, and passed by it on the east to Janohah;", highlightedWords: [{ word: "Michmethah", strongNumber: "H4366", lemma: "Mikmethath", meaning: "concealment; Michmethah" }, { word: "sea", strongNumber: "H3220", lemma: "yam", meaning: "sea" }] },
  { verse: 7, text: "And it went down from Janohah to Ataroth, and to Naarath, and came to Jericho, and went out at Jordan.", highlightedWords: [{ word: "Jericho", strongNumber: "H3405", lemma: "Yericho", meaning: "fragrant; Jericho" }, { word: "Jordan", strongNumber: "H3383", lemma: "Yarden", meaning: "the descender; the Jordan River" }] },
  { verse: 8, text: "The border went out from Tappuah westward unto the river Kanah; and the goings out thereof were at the sea. This is the inheritance of the tribe of the children of Ephraim by their families.", highlightedWords: [{ word: "Tappuah", strongNumber: "H8599", lemma: "Tappuah", meaning: "apple; Tappuah" }, { word: "tribe", strongNumber: "H4294", lemma: "matteh", meaning: "staff, rod; tribe" }] },
  { verse: 9, text: "And the separate cities for the children of Ephraim were among the inheritance of the children of Manasseh, all the cities with their villages.", highlightedWords: [{ word: "cities", strongNumber: "H5892", lemma: "ir", meaning: "city, town" }, { word: "Manasseh", strongNumber: "H4519", lemma: "Menashsheh", meaning: "causing to forget; Manasseh" }] },
  { verse: 10, text: "And they drave not out the Canaanites that dwelt in Gezer: but the Canaanites dwell among the Ephraimites unto this day, and serve under tribute.", highlightedWords: [{ word: "Canaanites", strongNumber: "H3669", lemma: "Kenani", meaning: "inhabitants of Canaan" }, { word: "tribute", strongNumber: "H4522", lemma: "mas", meaning: "forced labor, levy, tribute" }] },
];
