export const joshuaChapter14 = {
  book: 'Joshua',
  chapter: 14,
  chapterTheme: {
    twoWordSummary: "Caleb's Inheritance",
    themeWords: [
      { word: 'Caleb', strongNumber: 'H3612', lemma: 'Kalev', meaning: "Caleb; a leader of Judah (name meaning 'dog')" },
      { word: 'Hebron', strongNumber: 'H2275', lemma: 'Chebron', meaning: 'Hebron; association, alliance' },
    ],
  },
  sentenceTheme: 'Caleb, who wholly followed the LORD, asks for and receives Hebron as his inheritance.',
  verses: [
    { verse: 1, text: 'And these are the countries which the children of Israel inherited in the land of Canaan, which Eleazar the priest, and Joshua the son of Nun, and the heads of the fathers of the tribes of the children of Israel, distributed for inheritance unto them.', highlightedWords: [{ word: 'Israel', strongNumber: 'H3478', lemma: 'Yisrael', meaning: 'Israel; the nation descended from Jacob' }, { word: 'Joshua', strongNumber: 'H3091', lemma: 'Yehoshua', meaning: 'Joshua; Yahweh is salvation' }] },
    { verse: 2, text: 'By lot was their inheritance, as the LORD commanded by the hand of Moses, for the nine tribes, and for the half tribe.', highlightedWords: [{ word: 'lot', strongNumber: 'H1486', lemma: 'goral', meaning: 'lot; allotment decided by casting lots' }, { word: 'Moses', strongNumber: 'H4872', lemma: 'Mosheh', meaning: 'Moses; drawn out' }] },
    { verse: 3, text: 'For Moses had given the inheritance of two tribes and an half tribe on the other side Jordan: but unto the Levites he gave none inheritance among them.', highlightedWords: [{ word: 'Jordan', strongNumber: 'H3383', lemma: 'Yarden', meaning: 'Jordan; the principal river of Palestine' }, { word: 'Levites', strongNumber: 'H3881', lemma: 'Leviyiy', meaning: 'Levite; a descendant of Levi' }] },
    { verse: 4, text: 'For the children of Joseph were two tribes, Manasseh and Ephraim: therefore they gave no part unto the Levites in the land, save cities to dwell in, with their suburbs for their cattle, and for their substance.', highlightedWords: [{ word: 'Joseph', strongNumber: 'H3130', lemma: 'Yoseph', meaning: 'Joseph; he adds' }, { word: 'Levites', strongNumber: 'H3881', lemma: 'Leviyiy', meaning: 'Levite; a descendant of Levi' }] },
    { verse: 5, text: 'As the LORD commanded Moses, so the children of Israel did, and they divided the land.', highlightedWords: [{ word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'The personal name of the God of Israel (Yahweh)' }, { word: 'Israel', strongNumber: 'H3478', lemma: 'Yisrael', meaning: 'Israel; the nation descended from Jacob' }] },
    { verse: 6, text: 'Then the children of Judah came unto Joshua in Gilgal: and Caleb the son of Jephunneh the Kenezite said unto him, Thou knowest the thing that the LORD said unto Moses the man of God concerning me and thee in Kadeshbarnea.', highlightedWords: [{ word: 'Judah', strongNumber: 'H3063', lemma: 'Yehudah', meaning: 'Judah; praise' }, { word: 'Caleb', strongNumber: 'H3612', lemma: 'Kalev', meaning: "Caleb; a leader of Judah (name meaning 'dog')" }] },
    { verse: 7, text: 'Forty years old was I when Moses the servant of the LORD sent me from Kadeshbarnea to espy out the land; and I brought him word again as it was in mine heart.', highlightedWords: [{ word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'The personal name of the God of Israel (Yahweh)' }, { word: 'Kadeshbarnea', strongNumber: 'H6947', lemma: 'Qadesh Barnea', meaning: 'Kadesh-barnea; a place in the southern wilderness' }] },
    { verse: 8, text: 'Nevertheless my brethren that went up with me made the heart of the people melt: but I wholly followed the LORD my God.', highlightedWords: [{ word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'The personal name of the God of Israel (Yahweh)' }, { word: 'God', strongNumber: 'H430', lemma: 'Elohim', meaning: 'God; the supreme God' }] },
    { verse: 9, text: 'And Moses sware on that day, saying, Surely the land whereon thy feet have trodden shall be thine inheritance, and thy children\'s for ever, because thou hast wholly followed the LORD my God.', highlightedWords: [{ word: 'Moses', strongNumber: 'H4872', lemma: 'Mosheh', meaning: 'Moses; drawn out' }, { word: 'inheritance', strongNumber: 'H5159', lemma: 'nachalah', meaning: 'inheritance; possession; heritage' }] },
    { verse: 10, text: 'And now, behold, the LORD hath kept me alive, as he said, these forty and five years, even since the LORD spake this word unto Moses, while the children of Israel wandered in the wilderness: and now, lo, I am this day fourscore and five years old.', highlightedWords: [{ word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'The personal name of the God of Israel (Yahweh)' }, { word: 'wilderness', strongNumber: 'H4057', lemma: 'midbar', meaning: 'wilderness; desert' }] },
    { verse: 11, text: 'As yet I am as strong this day as I was in the day that Moses sent me: as my strength was then, even so is my strength now, for war, both to go out, and to come in.', highlightedWords: [{ word: 'Moses', strongNumber: 'H4872', lemma: 'Mosheh', meaning: 'Moses; drawn out' }, { word: 'war', strongNumber: 'H4421', lemma: 'milchamah', meaning: 'battle; war' }] },
    { verse: 12, text: 'Now therefore give me this mountain, whereof the LORD spake in that day; for thou heardest in that day how the Anakims were there, and that the cities were great and fenced: if so be the LORD will be with me, then I shall be able to drive them out, as the LORD said.', highlightedWords: [{ word: 'Anakims', strongNumber: 'H6062', lemma: 'Anaqiy', meaning: 'Anakim; a race of giants' }, { word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'The personal name of the God of Israel (Yahweh)' }] },
    { verse: 13, text: 'And Joshua blessed him, and gave unto Caleb the son of Jephunneh Hebron for an inheritance.', highlightedWords: [{ word: 'Joshua', strongNumber: 'H3091', lemma: 'Yehoshua', meaning: 'Joshua; Yahweh is salvation' }, { word: 'Hebron', strongNumber: 'H2275', lemma: 'Chebron', meaning: 'Hebron; association, alliance' }] },
    { verse: 14, text: 'Hebron therefore became the inheritance of Caleb the son of Jephunneh the Kenezite unto this day, because that he wholly followed the LORD God of Israel.', highlightedWords: [{ word: 'Hebron', strongNumber: 'H2275', lemma: 'Chebron', meaning: 'Hebron; association, alliance' }, { word: 'Kenezite', strongNumber: 'H7074', lemma: 'Qenizzi', meaning: 'Kenizzite; descendant of Kenaz' }] },
    { verse: 15, text: 'And the name of Hebron before was Kirjatharba; which Arba was a great man among the Anakims. And the land had rest from war.', highlightedWords: [{ word: 'Hebron', strongNumber: 'H2275', lemma: 'Chebron', meaning: 'Hebron; association, alliance' }, { word: 'Anakims', strongNumber: 'H6062', lemma: 'Anaqiy', meaning: 'Anakim; a race of giants' }] },
  ],
}
