export const numbersChapter32 = {
  'Numbers-32': {
    book: 'Numbers',
    chapter: 32,
    chapterTheme: {
      twoWordSummary: 'East Inheritance',
      themeWords: [
        {
          word: 'inheritance',
          strongNumber: 'H5159',
          lemma: 'nahalah',
          meaning: 'inheritance, hereditary possession'
        },
        {
          word: 'Jordan',
          strongNumber: 'H3383',
          lemma: 'Yarden',
          meaning: 'Jordan, the descender (river)'
        }
      ]
    },
    sentenceDescription: 'Reuben, Gad, and half Manasseh receive Gilead and Bashan east of Jordan after vowing to fight for Israel until the conquest is complete.',
    verses: [
      { verseNumber: 1, text: 'Now the children of Reuben and the children of Gad had a very great multitude of cattle: and when they saw the land of Jazer, and the land of Gilead, that, behold, the place was a place for cattle;', highlightedWords: [{ word: 'cattle', strongNumber: 'H4735', lemma: 'miqneh', meaning: 'livestock, cattle, property' }, { word: 'Gilead', strongNumber: 'H1568', lemma: 'Gilead', meaning: 'Gilead, region east of the Jordan' }] },
      { verseNumber: 2, text: 'The children of Gad and the children of Reuben came and spake unto Moses, and to Eleazar the priest, and unto the princes of the congregation, saying,', highlightedWords: [{ word: 'Moses', strongNumber: 'H4872', lemma: 'Mosheh', meaning: 'Moses, leader of Israel' }, { word: 'priest', strongNumber: 'H3548', lemma: 'kohen', meaning: 'priest' }] },
      { verseNumber: 3, text: 'Ataroth, and Dibon, and Jazer, and Nimrah, and Heshbon, and Elealeh, and Shebam, and Nebo, and Beon,', highlightedWords: [{ word: 'Jazer', strongNumber: 'H3270', lemma: 'Yaazer', meaning: 'Jazer, a city east of the Jordan' }, { word: 'Nebo', strongNumber: 'H5015', lemma: 'Nebo', meaning: 'Nebo, a city and mountain east of the Jordan' }] },
      { verseNumber: 4, text: 'Even the country which the LORD smote before the congregation of Israel, is a land for cattle, and thy servants have cattle:', highlightedWords: [{ word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'the personal name of the God of Israel' }, { word: 'Israel', strongNumber: 'H3478', lemma: 'Yisrael', meaning: 'Israel, the people and nation' }] },
      { verseNumber: 5, text: 'Wherefore, said they, if we have found grace in thy sight, let this land be given unto thy servants for a possession, and bring us not over Jordan.', highlightedWords: [{ word: 'possession', strongNumber: 'H272', lemma: 'ahuzzah', meaning: 'possession, property, holding' }, { word: 'Jordan', strongNumber: 'H3383', lemma: 'Yarden', meaning: 'Jordan, the descender (river)' }] },
      { verseNumber: 6, text: 'And Moses said unto the children of Gad and to the children of Reuben, Shall your brethren go to war, and shall ye sit here?', highlightedWords: [{ word: 'Moses', strongNumber: 'H4872', lemma: 'Mosheh', meaning: 'Moses, leader of Israel' }, { word: 'war', strongNumber: 'H4421', lemma: 'milchamah', meaning: 'battle, war' }] },
      { verseNumber: 7, text: 'And wherefore discourage ye the heart of the children of Israel from going over into the land which the LORD hath given them?', highlightedWords: [{ word: 'Israel', strongNumber: 'H3478', lemma: 'Yisrael', meaning: 'Israel, the people and nation' }, { word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'the personal name of the God of Israel' }] },
      { verseNumber: 8, text: 'Thus did your fathers, when I sent them from Kadesh-barnea to see the land.', highlightedWords: [{ word: 'Kadesh-barnea', strongNumber: 'H6947', lemma: 'Qadesh Barnea', meaning: 'Kadesh-barnea, a southern border site' }, { word: 'land', strongNumber: 'H776', lemma: 'erets', meaning: 'land, earth' }] },
      { verseNumber: 9, text: 'For when they went up unto the valley of Eshcol, and saw the land, they discouraged the heart of the children of Israel, that they should not go into the land which the LORD had given them.', highlightedWords: [{ word: 'Eshcol', strongNumber: 'H812', lemma: 'Eshcol', meaning: 'Eshcol, a valley in Canaan' }, { word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'the personal name of the God of Israel' }] },
      { verseNumber: 10, text: 'And the LORD\'s anger was kindled the same time, and he sware, saying,', highlightedWords: [{ word: 'anger', strongNumber: 'H639', lemma: 'aph', meaning: 'nose, anger, wrath' }, { word: 'sware', strongNumber: 'H7650', lemma: 'shava', meaning: 'to swear, take an oath' }] },
      { verseNumber: 11, text: 'Surely none of the men that came up out of Egypt, from twenty years old and upward, shall see the land which I sware unto Abraham, unto Isaac, and unto Jacob; because they have not wholly followed me:', highlightedWords: [{ word: 'Egypt', strongNumber: 'H4714', lemma: 'Mitsrayim', meaning: 'Egypt' }, { word: 'Abraham', strongNumber: 'H85', lemma: 'Avraham', meaning: 'Abraham, patriarch' }] },
      { verseNumber: 12, text: 'Save Caleb the son of Jephunneh the Kenezite, and Joshua the son of Nun: for they have wholly followed the LORD.', highlightedWords: [{ word: 'Caleb', strongNumber: 'H3612', lemma: 'Kalev', meaning: 'Caleb' }, { word: 'Joshua', strongNumber: 'H3091', lemma: 'Yehoshua', meaning: 'Joshua' }] },
      { verseNumber: 13, text: 'And the LORD\'s anger was kindled against Israel, and he made them wander in the wilderness forty years, until all the generation, that had done evil in the sight of the LORD, was consumed.', highlightedWords: [{ word: 'wilderness', strongNumber: 'H4057', lemma: 'midbar', meaning: 'wilderness, desert' }, { word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'the personal name of the God of Israel' }] },
      { verseNumber: 14, text: 'And, behold, ye are risen up in your fathers\' stead, an increase of sinful men, to augment yet the fierce anger of the LORD toward Israel.', highlightedWords: [{ word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'the personal name of the God of Israel' }, { word: 'Israel', strongNumber: 'H3478', lemma: 'Yisrael', meaning: 'Israel, the people and nation' }] },
      { verseNumber: 15, text: 'For if ye turn away from after him, he will yet again leave them in the wilderness; and ye shall destroy all this people.', highlightedWords: [{ word: 'wilderness', strongNumber: 'H4057', lemma: 'midbar', meaning: 'wilderness, desert' }, { word: 'people', strongNumber: 'H5971', lemma: 'am', meaning: 'people, nation' }] },
      { verseNumber: 16, text: 'And they came near unto him, and said, We will build sheepfolds here for our cattle, and cities for our little ones:', highlightedWords: [{ word: 'cattle', strongNumber: 'H4735', lemma: 'miqneh', meaning: 'livestock, cattle, property' }, { word: 'cities', strongNumber: 'H5892', lemma: 'ir', meaning: 'city, town' }] },
      { verseNumber: 17, text: 'But we ourselves will go ready armed before the children of Israel, until we have brought them unto their place: and our little ones shall dwell in the fenced cities because of the inhabitants of the land.', highlightedWords: [{ word: 'Israel', strongNumber: 'H3478', lemma: 'Yisrael', meaning: 'Israel, the people and nation' }, { word: 'land', strongNumber: 'H776', lemma: 'erets', meaning: 'land, earth' }] },
      { verseNumber: 18, text: 'We will not return unto our houses, until the children of Israel have inherited every man his inheritance.', highlightedWords: [{ word: 'inheritance', strongNumber: 'H5159', lemma: 'nahalah', meaning: 'inheritance, hereditary possession' }, { word: 'Israel', strongNumber: 'H3478', lemma: 'Yisrael', meaning: 'Israel, the people and nation' }] },
      { verseNumber: 19, text: 'For we will not inherit with them on yonder side Jordan, or forward; because our inheritance is fallen to us on this side Jordan eastward.', highlightedWords: [{ word: 'inherit', strongNumber: 'H5157', lemma: 'nachal', meaning: 'to inherit, take possession' }, { word: 'Jordan', strongNumber: 'H3383', lemma: 'Yarden', meaning: 'Jordan, the descender (river)' }] },
      { verseNumber: 20, text: 'And Moses said unto them, If ye will do this thing, if ye will go armed before the LORD to war,', highlightedWords: [{ word: 'Moses', strongNumber: 'H4872', lemma: 'Mosheh', meaning: 'Moses, leader of Israel' }, { word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'the personal name of the God of Israel' }] },
      { verseNumber: 21, text: 'And will go all of you armed over Jordan before the LORD, until he hath driven out his enemies from before him,', highlightedWords: [{ word: 'Jordan', strongNumber: 'H3383', lemma: 'Yarden', meaning: 'Jordan, the descender (river)' }, { word: 'enemies', strongNumber: 'H341', lemma: 'oyev', meaning: 'enemy' }] },
      { verseNumber: 22, text: 'And the land be subdued before the LORD: then afterward ye shall return, and be guiltless before the LORD, and before Israel; and this land shall be your possession before the LORD.', highlightedWords: [{ word: 'land', strongNumber: 'H776', lemma: 'erets', meaning: 'land, earth' }, { word: 'possession', strongNumber: 'H272', lemma: 'ahuzzah', meaning: 'possession, property, holding' }] },
      { verseNumber: 23, text: 'But if ye will not do so, behold, ye have sinned against the LORD: and be sure your sin will find you out.', highlightedWords: [{ word: 'sinned', strongNumber: 'H2398', lemma: 'chata', meaning: 'to sin, miss the mark' }, { word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'the personal name of the God of Israel' }] },
      { verseNumber: 24, text: 'Build you cities for your little ones, and folds for your sheep; and do that which hath proceeded out of your mouth.', highlightedWords: [{ word: 'cities', strongNumber: 'H5892', lemma: 'ir', meaning: 'city, town' }, { word: 'sheep', strongNumber: 'H6629', lemma: 'zon', meaning: 'sheep, small livestock' }] },
      { verseNumber: 25, text: 'And the children of Gad and the children of Reuben spake unto Moses, saying, Thy servants will do as my lord commandeth.', highlightedWords: [{ word: 'Moses', strongNumber: 'H4872', lemma: 'Mosheh', meaning: 'Moses, leader of Israel' }, { word: 'servants', strongNumber: 'H5650', lemma: 'eved', meaning: 'servant, bondman' }] },
      { verseNumber: 26, text: 'Our little ones, our wives, our flocks, and all our cattle, shall be there in the cities of Gilead:', highlightedWords: [{ word: 'wives', strongNumber: 'H802', lemma: 'isha', meaning: 'woman, wife' }, { word: 'Gilead', strongNumber: 'H1568', lemma: 'Gilead', meaning: 'Gilead, region east of the Jordan' }] },
      { verseNumber: 27, text: 'But thy servants will pass over, every man armed for war, before the LORD to battle, as my lord saith.', highlightedWords: [{ word: 'battle', strongNumber: 'H4421', lemma: 'milchamah', meaning: 'battle, war' }, { word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'the personal name of the God of Israel' }] },
      { verseNumber: 28, text: 'So concerning them Moses commanded Eleazar the priest, and Joshua the son of Nun, and the chief fathers of the tribes of the children of Israel:', highlightedWords: [{ word: 'Moses', strongNumber: 'H4872', lemma: 'Mosheh', meaning: 'Moses, leader of Israel' }, { word: 'priest', strongNumber: 'H3548', lemma: 'kohen', meaning: 'priest' }] },
      { verseNumber: 29, text: 'And Moses said unto them, If the children of Gad and the children of Reuben will pass with you over Jordan, every man armed to battle, before the LORD, and the land shall be subdued before you; then ye shall give them the land of Gilead for a possession:', highlightedWords: [{ word: 'Gad', strongNumber: 'H1410', lemma: 'Gad', meaning: 'Gad, a tribe of Israel' }, { word: 'possession', strongNumber: 'H272', lemma: 'ahuzzah', meaning: 'possession, property, holding' }] },
      { verseNumber: 30, text: 'But if they will not pass over with you armed, they shall have possessions among you in the land of Canaan.', highlightedWords: [{ word: 'Canaan', strongNumber: 'H3667', lemma: 'Canaan', meaning: 'Canaan, the land west of Jordan' }, { word: 'land', strongNumber: 'H776', lemma: 'erets', meaning: 'land, earth' }] },
      { verseNumber: 31, text: 'And the children of Gad and the children of Reuben answered, saying, As the LORD hath said unto thy servants, so will we do.', highlightedWords: [{ word: 'LORD', strongNumber: 'H3068', lemma: 'YHWH', meaning: 'the personal name of the God of Israel' }, { word: 'servants', strongNumber: 'H5650', lemma: 'eved', meaning: 'servant, bondman' }] },
      { verseNumber: 32, text: 'We will pass over armed before the LORD into the land of Canaan, that the possession of our inheritance on this side Jordan may be ours.', highlightedWords: [{ word: 'Canaan', strongNumber: 'H3667', lemma: 'Canaan', meaning: 'Canaan, the land west of Jordan' }, { word: 'Jordan', strongNumber: 'H3383', lemma: 'Yarden', meaning: 'Jordan, the descender (river)' }] },
      { verseNumber: 33, text: 'And Moses gave unto them, even to the children of Gad, and to the children of Reuben, and unto half the tribe of Manasseh the son of Joseph, the kingdom of Sihon king of the Amorites, and the kingdom of Og king of Bashan, the land, with the cities thereof in the coasts, even the cities of the country round about.', highlightedWords: [{ word: 'Manasseh', strongNumber: 'H4519', lemma: 'Manasseh', meaning: 'Manasseh, a tribe of Israel' }, { word: 'Amorites', strongNumber: 'H567', lemma: 'Emori', meaning: 'Amorites' }] },
      { verseNumber: 34, text: 'And the children of Gad built Dibon, and Ataroth, and Aroer,', highlightedWords: [{ word: 'Gad', strongNumber: 'H1410', lemma: 'Gad', meaning: 'Gad, a tribe of Israel' }, { word: 'Dibon', strongNumber: 'H1769', lemma: 'Dibon', meaning: 'Dibon, a city in Moab' }] },
      { verseNumber: 35, text: 'And Atroth, Shophan, and Jaazer, and Jogbehah,', highlightedWords: [{ word: 'Jaazer', strongNumber: 'H3270', lemma: 'Jaazer', meaning: 'Jaazer, a city east of the Jordan' }, { word: 'Jogbehah', strongNumber: 'H3011', lemma: 'Jogbehah', meaning: 'Jogbehah, a city of Gilead' }] },
      { verseNumber: 36, text: 'And Beth-nimrah, and Beth-haran, fenced cities: and folds for sheep.', highlightedWords: [{ word: 'cities', strongNumber: 'H5892', lemma: 'ir', meaning: 'city, town' }, { word: 'sheep', strongNumber: 'H6629', lemma: 'zon', meaning: 'sheep, small livestock' }] },
      { verseNumber: 37, text: 'And the children of Reuben built Heshbon, and Elealeh, and Kirjathaim,', highlightedWords: [{ word: 'Reuben', strongNumber: 'H7205', lemma: 'Reuben', meaning: 'Reuben, a tribe of Israel' }, { word: 'Heshbon', strongNumber: 'H2809', lemma: 'Heshbon', meaning: 'Heshbon, a city in Transjordan' }] },
      { verseNumber: 38, text: 'And Nebo, and Baal-meon, (their names being changed,) and Shibmah: and gave other names unto the cities which they builded.', highlightedWords: [{ word: 'Nebo', strongNumber: 'H5015', lemma: 'Nebo', meaning: 'Nebo, a city and mountain east of the Jordan' }, { word: 'cities', strongNumber: 'H5892', lemma: 'ir', meaning: 'city, town' }] },
      { verseNumber: 39, text: 'And the children of Machir the son of Manasseh went to Gilead, and took it, and dispossessed the Amorite which was in it.', highlightedWords: [{ word: 'Machir', strongNumber: 'H4353', lemma: 'Machir', meaning: 'Machir, a descendant of Manasseh' }, { word: 'Amorite', strongNumber: 'H567', lemma: 'Emori', meaning: 'Amorite' }] },
      { verseNumber: 40, text: 'And Moses gave Gilead unto Machir the son of Manasseh; and he dwelt therein.', highlightedWords: [{ word: 'Gilead', strongNumber: 'H1568', lemma: 'Gilead', meaning: 'Gilead, region east of the Jordan' }, { word: 'Manasseh', strongNumber: 'H4519', lemma: 'Manasseh', meaning: 'Manasseh, a tribe of Israel' }] },
      { verseNumber: 41, text: 'And Jair the son of Manasseh went and took the small towns thereof, and called them Havoth-jair.', highlightedWords: [{ word: 'Jair', strongNumber: 'H2971', lemma: 'Jair', meaning: 'Jair, a descendant of Manasseh' }, { word: 'Manasseh', strongNumber: 'H4519', lemma: 'Manasseh', meaning: 'Manasseh, a tribe of Israel' }] },
      { verseNumber: 42, text: 'And Nobah went and took Kenath, and the villages thereof, and called it Nobah, after his own name.', highlightedWords: [{ word: 'Nobah', strongNumber: 'H5025', lemma: 'Nobah', meaning: 'Nobah, a Manassite leader' }, { word: 'Kenath', strongNumber: 'H7079', lemma: 'Kenath', meaning: 'Kenath, a city in Bashan' }] }
    ]
  }
}
